/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AspNetUser
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class AspNetUser {
  @SerializedName("id")
  private String id = null;

  @SerializedName("tenantId")
  private Integer tenantId = null;

  @SerializedName("tenant")
  private Tenant tenant = null;

  @SerializedName("accessFailedCount")
  private Integer accessFailedCount = null;

  @SerializedName("concurrencyStamp")
  private String concurrencyStamp = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("emailConfirmed")
  private Boolean emailConfirmed = null;

  @SerializedName("lockoutEnabled")
  private Boolean lockoutEnabled = null;

  @SerializedName("lockoutEnd")
  private OffsetDateTime lockoutEnd = null;

  @SerializedName("normalizedEmail")
  private String normalizedEmail = null;

  @SerializedName("normalizedUserName")
  private String normalizedUserName = null;

  @SerializedName("passwordHash")
  private String passwordHash = null;

  @SerializedName("phoneNumber")
  private String phoneNumber = null;

  @SerializedName("phoneNumberConfirmed")
  private Boolean phoneNumberConfirmed = null;

  @SerializedName("securityStamp")
  private String securityStamp = null;

  @SerializedName("twoFactorEnabled")
  private Boolean twoFactorEnabled = null;

  @SerializedName("userName")
  private String userName = null;

  @SerializedName("aspNetUserProfiles")
  private List<AspNetUserProfile> aspNetUserProfiles = null;

  @SerializedName("commands")
  private List<Command> commands = null;

  @SerializedName("createdCommands")
  private List<Command> createdCommands = null;

  @SerializedName("commandExecutions")
  private List<CommandExecution> commandExecutions = null;

  public AspNetUser id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AspNetUser tenantId(Integer tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @Schema(description = "")
  public Integer getTenantId() {
    return tenantId;
  }

  public void setTenantId(Integer tenantId) {
    this.tenantId = tenantId;
  }

  public AspNetUser tenant(Tenant tenant) {
    this.tenant = tenant;
    return this;
  }

   /**
   * Get tenant
   * @return tenant
  **/
  @Schema(description = "")
  public Tenant getTenant() {
    return tenant;
  }

  public void setTenant(Tenant tenant) {
    this.tenant = tenant;
  }

  public AspNetUser accessFailedCount(Integer accessFailedCount) {
    this.accessFailedCount = accessFailedCount;
    return this;
  }

   /**
   * Get accessFailedCount
   * @return accessFailedCount
  **/
  @Schema(required = true, description = "")
  public Integer getAccessFailedCount() {
    return accessFailedCount;
  }

  public void setAccessFailedCount(Integer accessFailedCount) {
    this.accessFailedCount = accessFailedCount;
  }

  public AspNetUser concurrencyStamp(String concurrencyStamp) {
    this.concurrencyStamp = concurrencyStamp;
    return this;
  }

   /**
   * Get concurrencyStamp
   * @return concurrencyStamp
  **/
  @Schema(description = "")
  public String getConcurrencyStamp() {
    return concurrencyStamp;
  }

  public void setConcurrencyStamp(String concurrencyStamp) {
    this.concurrencyStamp = concurrencyStamp;
  }

  public AspNetUser email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public AspNetUser emailConfirmed(Boolean emailConfirmed) {
    this.emailConfirmed = emailConfirmed;
    return this;
  }

   /**
   * Get emailConfirmed
   * @return emailConfirmed
  **/
  @Schema(description = "")
  public Boolean isEmailConfirmed() {
    return emailConfirmed;
  }

  public void setEmailConfirmed(Boolean emailConfirmed) {
    this.emailConfirmed = emailConfirmed;
  }

  public AspNetUser lockoutEnabled(Boolean lockoutEnabled) {
    this.lockoutEnabled = lockoutEnabled;
    return this;
  }

   /**
   * Get lockoutEnabled
   * @return lockoutEnabled
  **/
  @Schema(description = "")
  public Boolean isLockoutEnabled() {
    return lockoutEnabled;
  }

  public void setLockoutEnabled(Boolean lockoutEnabled) {
    this.lockoutEnabled = lockoutEnabled;
  }

  public AspNetUser lockoutEnd(OffsetDateTime lockoutEnd) {
    this.lockoutEnd = lockoutEnd;
    return this;
  }

   /**
   * Get lockoutEnd
   * @return lockoutEnd
  **/
  @Schema(description = "")
  public OffsetDateTime getLockoutEnd() {
    return lockoutEnd;
  }

  public void setLockoutEnd(OffsetDateTime lockoutEnd) {
    this.lockoutEnd = lockoutEnd;
  }

  public AspNetUser normalizedEmail(String normalizedEmail) {
    this.normalizedEmail = normalizedEmail;
    return this;
  }

   /**
   * Get normalizedEmail
   * @return normalizedEmail
  **/
  @Schema(description = "")
  public String getNormalizedEmail() {
    return normalizedEmail;
  }

  public void setNormalizedEmail(String normalizedEmail) {
    this.normalizedEmail = normalizedEmail;
  }

  public AspNetUser normalizedUserName(String normalizedUserName) {
    this.normalizedUserName = normalizedUserName;
    return this;
  }

   /**
   * Get normalizedUserName
   * @return normalizedUserName
  **/
  @Schema(description = "")
  public String getNormalizedUserName() {
    return normalizedUserName;
  }

  public void setNormalizedUserName(String normalizedUserName) {
    this.normalizedUserName = normalizedUserName;
  }

  public AspNetUser passwordHash(String passwordHash) {
    this.passwordHash = passwordHash;
    return this;
  }

   /**
   * Get passwordHash
   * @return passwordHash
  **/
  @Schema(description = "")
  public String getPasswordHash() {
    return passwordHash;
  }

  public void setPasswordHash(String passwordHash) {
    this.passwordHash = passwordHash;
  }

  public AspNetUser phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @Schema(description = "")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public AspNetUser phoneNumberConfirmed(Boolean phoneNumberConfirmed) {
    this.phoneNumberConfirmed = phoneNumberConfirmed;
    return this;
  }

   /**
   * Get phoneNumberConfirmed
   * @return phoneNumberConfirmed
  **/
  @Schema(description = "")
  public Boolean isPhoneNumberConfirmed() {
    return phoneNumberConfirmed;
  }

  public void setPhoneNumberConfirmed(Boolean phoneNumberConfirmed) {
    this.phoneNumberConfirmed = phoneNumberConfirmed;
  }

  public AspNetUser securityStamp(String securityStamp) {
    this.securityStamp = securityStamp;
    return this;
  }

   /**
   * Get securityStamp
   * @return securityStamp
  **/
  @Schema(description = "")
  public String getSecurityStamp() {
    return securityStamp;
  }

  public void setSecurityStamp(String securityStamp) {
    this.securityStamp = securityStamp;
  }

  public AspNetUser twoFactorEnabled(Boolean twoFactorEnabled) {
    this.twoFactorEnabled = twoFactorEnabled;
    return this;
  }

   /**
   * Get twoFactorEnabled
   * @return twoFactorEnabled
  **/
  @Schema(description = "")
  public Boolean isTwoFactorEnabled() {
    return twoFactorEnabled;
  }

  public void setTwoFactorEnabled(Boolean twoFactorEnabled) {
    this.twoFactorEnabled = twoFactorEnabled;
  }

  public AspNetUser userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @Schema(description = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public AspNetUser aspNetUserProfiles(List<AspNetUserProfile> aspNetUserProfiles) {
    this.aspNetUserProfiles = aspNetUserProfiles;
    return this;
  }

  public AspNetUser addAspNetUserProfilesItem(AspNetUserProfile aspNetUserProfilesItem) {
    if (this.aspNetUserProfiles == null) {
      this.aspNetUserProfiles = new ArrayList<AspNetUserProfile>();
    }
    this.aspNetUserProfiles.add(aspNetUserProfilesItem);
    return this;
  }

   /**
   * Get aspNetUserProfiles
   * @return aspNetUserProfiles
  **/
  @Schema(description = "")
  public List<AspNetUserProfile> getAspNetUserProfiles() {
    return aspNetUserProfiles;
  }

  public void setAspNetUserProfiles(List<AspNetUserProfile> aspNetUserProfiles) {
    this.aspNetUserProfiles = aspNetUserProfiles;
  }

  public AspNetUser commands(List<Command> commands) {
    this.commands = commands;
    return this;
  }

  public AspNetUser addCommandsItem(Command commandsItem) {
    if (this.commands == null) {
      this.commands = new ArrayList<Command>();
    }
    this.commands.add(commandsItem);
    return this;
  }

   /**
   * Get commands
   * @return commands
  **/
  @Schema(description = "")
  public List<Command> getCommands() {
    return commands;
  }

  public void setCommands(List<Command> commands) {
    this.commands = commands;
  }

  public AspNetUser createdCommands(List<Command> createdCommands) {
    this.createdCommands = createdCommands;
    return this;
  }

  public AspNetUser addCreatedCommandsItem(Command createdCommandsItem) {
    if (this.createdCommands == null) {
      this.createdCommands = new ArrayList<Command>();
    }
    this.createdCommands.add(createdCommandsItem);
    return this;
  }

   /**
   * Get createdCommands
   * @return createdCommands
  **/
  @Schema(description = "")
  public List<Command> getCreatedCommands() {
    return createdCommands;
  }

  public void setCreatedCommands(List<Command> createdCommands) {
    this.createdCommands = createdCommands;
  }

  public AspNetUser commandExecutions(List<CommandExecution> commandExecutions) {
    this.commandExecutions = commandExecutions;
    return this;
  }

  public AspNetUser addCommandExecutionsItem(CommandExecution commandExecutionsItem) {
    if (this.commandExecutions == null) {
      this.commandExecutions = new ArrayList<CommandExecution>();
    }
    this.commandExecutions.add(commandExecutionsItem);
    return this;
  }

   /**
   * Get commandExecutions
   * @return commandExecutions
  **/
  @Schema(description = "")
  public List<CommandExecution> getCommandExecutions() {
    return commandExecutions;
  }

  public void setCommandExecutions(List<CommandExecution> commandExecutions) {
    this.commandExecutions = commandExecutions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AspNetUser aspNetUser = (AspNetUser) o;
    return Objects.equals(this.id, aspNetUser.id) &&
        Objects.equals(this.tenantId, aspNetUser.tenantId) &&
        Objects.equals(this.tenant, aspNetUser.tenant) &&
        Objects.equals(this.accessFailedCount, aspNetUser.accessFailedCount) &&
        Objects.equals(this.concurrencyStamp, aspNetUser.concurrencyStamp) &&
        Objects.equals(this.email, aspNetUser.email) &&
        Objects.equals(this.emailConfirmed, aspNetUser.emailConfirmed) &&
        Objects.equals(this.lockoutEnabled, aspNetUser.lockoutEnabled) &&
        Objects.equals(this.lockoutEnd, aspNetUser.lockoutEnd) &&
        Objects.equals(this.normalizedEmail, aspNetUser.normalizedEmail) &&
        Objects.equals(this.normalizedUserName, aspNetUser.normalizedUserName) &&
        Objects.equals(this.passwordHash, aspNetUser.passwordHash) &&
        Objects.equals(this.phoneNumber, aspNetUser.phoneNumber) &&
        Objects.equals(this.phoneNumberConfirmed, aspNetUser.phoneNumberConfirmed) &&
        Objects.equals(this.securityStamp, aspNetUser.securityStamp) &&
        Objects.equals(this.twoFactorEnabled, aspNetUser.twoFactorEnabled) &&
        Objects.equals(this.userName, aspNetUser.userName) &&
        Objects.equals(this.aspNetUserProfiles, aspNetUser.aspNetUserProfiles) &&
        Objects.equals(this.commands, aspNetUser.commands) &&
        Objects.equals(this.createdCommands, aspNetUser.createdCommands) &&
        Objects.equals(this.commandExecutions, aspNetUser.commandExecutions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tenantId, tenant, accessFailedCount, concurrencyStamp, email, emailConfirmed, lockoutEnabled, lockoutEnd, normalizedEmail, normalizedUserName, passwordHash, phoneNumber, phoneNumberConfirmed, securityStamp, twoFactorEnabled, userName, aspNetUserProfiles, commands, createdCommands, commandExecutions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AspNetUser {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    accessFailedCount: ").append(toIndentedString(accessFailedCount)).append("\n");
    sb.append("    concurrencyStamp: ").append(toIndentedString(concurrencyStamp)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    emailConfirmed: ").append(toIndentedString(emailConfirmed)).append("\n");
    sb.append("    lockoutEnabled: ").append(toIndentedString(lockoutEnabled)).append("\n");
    sb.append("    lockoutEnd: ").append(toIndentedString(lockoutEnd)).append("\n");
    sb.append("    normalizedEmail: ").append(toIndentedString(normalizedEmail)).append("\n");
    sb.append("    normalizedUserName: ").append(toIndentedString(normalizedUserName)).append("\n");
    sb.append("    passwordHash: ").append(toIndentedString(passwordHash)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    phoneNumberConfirmed: ").append(toIndentedString(phoneNumberConfirmed)).append("\n");
    sb.append("    securityStamp: ").append(toIndentedString(securityStamp)).append("\n");
    sb.append("    twoFactorEnabled: ").append(toIndentedString(twoFactorEnabled)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    aspNetUserProfiles: ").append(toIndentedString(aspNetUserProfiles)).append("\n");
    sb.append("    commands: ").append(toIndentedString(commands)).append("\n");
    sb.append("    createdCommands: ").append(toIndentedString(createdCommands)).append("\n");
    sb.append("    commandExecutions: ").append(toIndentedString(commandExecutions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
