/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AspNetUserProfile
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class AspNetUserProfile {
  @SerializedName("userId")
  private String userId = null;

  @SerializedName("aspNetUser")
  private AspNetUser aspNetUser = null;

  @SerializedName("fullName")
  private String fullName = null;

  @SerializedName("gender")
  private Integer gender = null;

  @SerializedName("dob")
  private OffsetDateTime dob = null;

  @SerializedName("employmentStartDate")
  private OffsetDateTime employmentStartDate = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("department")
  private String department = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  public AspNetUserProfile userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(required = true, description = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public AspNetUserProfile aspNetUser(AspNetUser aspNetUser) {
    this.aspNetUser = aspNetUser;
    return this;
  }

   /**
   * Get aspNetUser
   * @return aspNetUser
  **/
  @Schema(description = "")
  public AspNetUser getAspNetUser() {
    return aspNetUser;
  }

  public void setAspNetUser(AspNetUser aspNetUser) {
    this.aspNetUser = aspNetUser;
  }

  public AspNetUserProfile fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @Schema(required = true, description = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public AspNetUserProfile gender(Integer gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @Schema(description = "")
  public Integer getGender() {
    return gender;
  }

  public void setGender(Integer gender) {
    this.gender = gender;
  }

  public AspNetUserProfile dob(OffsetDateTime dob) {
    this.dob = dob;
    return this;
  }

   /**
   * Get dob
   * @return dob
  **/
  @Schema(description = "")
  public OffsetDateTime getDob() {
    return dob;
  }

  public void setDob(OffsetDateTime dob) {
    this.dob = dob;
  }

  public AspNetUserProfile employmentStartDate(OffsetDateTime employmentStartDate) {
    this.employmentStartDate = employmentStartDate;
    return this;
  }

   /**
   * Get employmentStartDate
   * @return employmentStartDate
  **/
  @Schema(description = "")
  public OffsetDateTime getEmploymentStartDate() {
    return employmentStartDate;
  }

  public void setEmploymentStartDate(OffsetDateTime employmentStartDate) {
    this.employmentStartDate = employmentStartDate;
  }

  public AspNetUserProfile phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @Schema(description = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public AspNetUserProfile address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public AspNetUserProfile department(String department) {
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  @Schema(description = "")
  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }

  public AspNetUserProfile extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AspNetUserProfile aspNetUserProfile = (AspNetUserProfile) o;
    return Objects.equals(this.userId, aspNetUserProfile.userId) &&
        Objects.equals(this.aspNetUser, aspNetUserProfile.aspNetUser) &&
        Objects.equals(this.fullName, aspNetUserProfile.fullName) &&
        Objects.equals(this.gender, aspNetUserProfile.gender) &&
        Objects.equals(this.dob, aspNetUserProfile.dob) &&
        Objects.equals(this.employmentStartDate, aspNetUserProfile.employmentStartDate) &&
        Objects.equals(this.phone, aspNetUserProfile.phone) &&
        Objects.equals(this.address, aspNetUserProfile.address) &&
        Objects.equals(this.department, aspNetUserProfile.department) &&
        Objects.equals(this.extInfo, aspNetUserProfile.extInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, aspNetUser, fullName, gender, dob, employmentStartDate, phone, address, department, extInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AspNetUserProfile {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    aspNetUser: ").append(toIndentedString(aspNetUser)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    dob: ").append(toIndentedString(dob)).append("\n");
    sb.append("    employmentStartDate: ").append(toIndentedString(employmentStartDate)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
