/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Transient;
import io.swagger.v3.oas.annotations.media.Schema;
//import org.threeten.bp.Date;
/**
 * Batch
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")
@Entity
public class Batch {
  @Id
  @SerializedName("id")
  private long id = 0;

  @SerializedName("batchNo")
  private String batchNo = null;

  @SerializedName("lotNo")
  private String lotNo = null;

  @Transient
  @SerializedName("lot")
  private Lot lot = null;

  @SerializedName("itemId")
  private Integer itemId = null;

  @Transient
  @SerializedName("item")
  private Item item = null;

  @SerializedName("expiryDate")
  private Date expiryDate = null;

  @SerializedName("manufactureDate")
  private Date manufactureDate = null;

  @SerializedName("qcStatus")
  private String qcStatus = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("transactionDetails")
  private List<TransactionDetail> transactionDetails = null;

  public Batch id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Batch batchNo(String batchNo) {
    this.batchNo = batchNo;
    return this;
  }

   /**
   * Get batchNo
   * @return batchNo
  **/
  @Schema(required = true, description = "")
  public String getBatchNo() {
    return batchNo;
  }

  public void setBatchNo(String batchNo) {
    this.batchNo = batchNo;
  }

  public Batch lotNo(String lotNo) {
    this.lotNo = lotNo;
    return this;
  }

   /**
   * Get lotNo
   * @return lotNo
  **/
  @Schema(description = "")
  public String getLotNo() {
    return lotNo;
  }

  public void setLotNo(String lotNo) {
    this.lotNo = lotNo;
  }

  public Batch lot(Lot lot) {
    this.lot = lot;
    return this;
  }

   /**
   * Get lot
   * @return lot
  **/
  @Schema(description = "")
  public Lot getLot() {
    return lot;
  }

  public void setLot(Lot lot) {
    this.lot = lot;
  }

  public Batch itemId(Integer itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * Get itemId
   * @return itemId
  **/
  @Schema(required = true, description = "")
  public Integer getItemId() {
    return itemId;
  }

  public void setItemId(Integer itemId) {
    this.itemId = itemId;
  }

  public Batch item(Item item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @Schema(description = "")
  public Item getItem() {
    return item;
  }

  public void setItem(Item item) {
    this.item = item;
  }

  public Batch expiryDate(Date expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @Schema(description = "")
  public Date getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(Date expiryDate) {
    this.expiryDate = expiryDate;
  }

  public Batch manufactureDate(Date manufactureDate) {
    this.manufactureDate = manufactureDate;
    return this;
  }

   /**
   * Get manufactureDate
   * @return manufactureDate
  **/
  @Schema(description = "")
  public Date getManufactureDate() {
    return manufactureDate;
  }

  public void setManufactureDate(Date manufactureDate) {
    this.manufactureDate = manufactureDate;
  }

  public Batch qcStatus(String qcStatus) {
    this.qcStatus = qcStatus;
    return this;
  }

   /**
   * Get qcStatus
   * @return qcStatus
  **/
  @Schema(required = true, description = "")
  public String getQcStatus() {
    return qcStatus;
  }

  public void setQcStatus(String qcStatus) {
    this.qcStatus = qcStatus;
  }

  public Batch note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @Schema(description = "")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public Batch extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public Batch transactionDetails(List<TransactionDetail> transactionDetails) {
    this.transactionDetails = transactionDetails;
    return this;
  }

  public Batch addTransactionDetailsItem(TransactionDetail transactionDetailsItem) {
    if (this.transactionDetails == null) {
      this.transactionDetails = new ArrayList<TransactionDetail>();
    }
    this.transactionDetails.add(transactionDetailsItem);
    return this;
  }

   /**
   * Get transactionDetails
   * @return transactionDetails
  **/
  @Schema(description = "")
  public List<TransactionDetail> getTransactionDetails() {
    return transactionDetails;
  }

  public void setTransactionDetails(List<TransactionDetail> transactionDetails) {
    this.transactionDetails = transactionDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Batch batch = (Batch) o;
    return Objects.equals(this.id, batch.id) &&
        Objects.equals(this.batchNo, batch.batchNo) &&
        Objects.equals(this.lotNo, batch.lotNo) &&
        Objects.equals(this.lot, batch.lot) &&
        Objects.equals(this.itemId, batch.itemId) &&
        Objects.equals(this.item, batch.item) &&
        Objects.equals(this.expiryDate, batch.expiryDate) &&
        Objects.equals(this.manufactureDate, batch.manufactureDate) &&
        Objects.equals(this.qcStatus, batch.qcStatus) &&
        Objects.equals(this.note, batch.note) &&
        Objects.equals(this.extInfo, batch.extInfo) &&
        Objects.equals(this.transactionDetails, batch.transactionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, batchNo, lotNo, lot, itemId, item, expiryDate, manufactureDate, qcStatus, note, extInfo, transactionDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Batch {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    batchNo: ").append(toIndentedString(batchNo)).append("\n");
    sb.append("    lotNo: ").append(toIndentedString(lotNo)).append("\n");
    sb.append("    lot: ").append(toIndentedString(lot)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    manufactureDate: ").append(toIndentedString(manufactureDate)).append("\n");
    sb.append("    qcStatus: ").append(toIndentedString(qcStatus)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    transactionDetails: ").append(toIndentedString(transactionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
