/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * BtSystem
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class BtSystem {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("releaseDate")
  private OffsetDateTime releaseDate = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("systemsInPackages")
  private List<SystemsInPackage> systemsInPackages = null;

  @SerializedName("systemWorkflows")
  private List<SystemWorkflow> systemWorkflows = null;

  public BtSystem id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public BtSystem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BtSystem code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public BtSystem version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(description = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public BtSystem releaseDate(OffsetDateTime releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @Schema(description = "")
  public OffsetDateTime getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(OffsetDateTime releaseDate) {
    this.releaseDate = releaseDate;
  }

  public BtSystem description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public BtSystem image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(description = "")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public BtSystem extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public BtSystem systemsInPackages(List<SystemsInPackage> systemsInPackages) {
    this.systemsInPackages = systemsInPackages;
    return this;
  }

  public BtSystem addSystemsInPackagesItem(SystemsInPackage systemsInPackagesItem) {
    if (this.systemsInPackages == null) {
      this.systemsInPackages = new ArrayList<SystemsInPackage>();
    }
    this.systemsInPackages.add(systemsInPackagesItem);
    return this;
  }

   /**
   * Get systemsInPackages
   * @return systemsInPackages
  **/
  @Schema(description = "")
  public List<SystemsInPackage> getSystemsInPackages() {
    return systemsInPackages;
  }

  public void setSystemsInPackages(List<SystemsInPackage> systemsInPackages) {
    this.systemsInPackages = systemsInPackages;
  }

  public BtSystem systemWorkflows(List<SystemWorkflow> systemWorkflows) {
    this.systemWorkflows = systemWorkflows;
    return this;
  }

  public BtSystem addSystemWorkflowsItem(SystemWorkflow systemWorkflowsItem) {
    if (this.systemWorkflows == null) {
      this.systemWorkflows = new ArrayList<SystemWorkflow>();
    }
    this.systemWorkflows.add(systemWorkflowsItem);
    return this;
  }

   /**
   * Get systemWorkflows
   * @return systemWorkflows
  **/
  @Schema(description = "")
  public List<SystemWorkflow> getSystemWorkflows() {
    return systemWorkflows;
  }

  public void setSystemWorkflows(List<SystemWorkflow> systemWorkflows) {
    this.systemWorkflows = systemWorkflows;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BtSystem btSystem = (BtSystem) o;
    return Objects.equals(this.id, btSystem.id) &&
        Objects.equals(this.name, btSystem.name) &&
        Objects.equals(this.code, btSystem.code) &&
        Objects.equals(this.version, btSystem.version) &&
        Objects.equals(this.releaseDate, btSystem.releaseDate) &&
        Objects.equals(this.description, btSystem.description) &&
        Objects.equals(this.image, btSystem.image) &&
        Objects.equals(this.extInfo, btSystem.extInfo) &&
        Objects.equals(this.systemsInPackages, btSystem.systemsInPackages) &&
        Objects.equals(this.systemWorkflows, btSystem.systemWorkflows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, code, version, releaseDate, description, image, extInfo, systemsInPackages, systemWorkflows);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BtSystem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    systemsInPackages: ").append(toIndentedString(systemsInPackages)).append("\n");
    sb.append("    systemWorkflows: ").append(toIndentedString(systemWorkflows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
