/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Transient;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CategoryOfItem
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")
@Entity
public class CategoryOfItem {
  @Id
  @SerializedName("id")
  private long id = 0;

  @SerializedName("codeId")
  private Integer codeId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("parentId")
  private Integer parentId = null;

  @Transient
  @SerializedName("parent")
  private CategoryOfItem parent = null;

  @SerializedName("categoryType")
  private Integer categoryType = null;

  @SerializedName("itemClass")
  private String itemClass = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("items")
  private List<Item> items = null;

  @SerializedName("children")
  private List<CategoryOfItem> children = null;

  public CategoryOfItem id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public CategoryOfItem codeId(Integer codeId) {
    this.codeId = codeId;
    return this;
  }

   /**
   * Get codeId
   * @return codeId
  **/
  @Schema(description = "")
  public Integer getCodeId() {
    return codeId;
  }

  public void setCodeId(Integer codeId) {
    this.codeId = codeId;
  }

  public CategoryOfItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CategoryOfItem description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CategoryOfItem parentId(Integer parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @Schema(description = "")
  public Integer getParentId() {
    return parentId;
  }

  public void setParentId(Integer parentId) {
    this.parentId = parentId;
  }

  public CategoryOfItem parent(CategoryOfItem parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @Schema(description = "")
  public CategoryOfItem getParent() {
    return parent;
  }

  public void setParent(CategoryOfItem parent) {
    this.parent = parent;
  }

  public CategoryOfItem categoryType(Integer categoryType) {
    this.categoryType = categoryType;
    return this;
  }

   /**
   * Get categoryType
   * @return categoryType
  **/
  @Schema(required = true, description = "")
  public Integer getCategoryType() {
    return categoryType;
  }

  public void setCategoryType(Integer categoryType) {
    this.categoryType = categoryType;
  }

  public CategoryOfItem itemClass(String itemClass) {
    this.itemClass = itemClass;
    return this;
  }

   /**
   * Get itemClass
   * @return itemClass
  **/
  @Schema(description = "")
  public String getItemClass() {
    return itemClass;
  }

  public void setItemClass(String itemClass) {
    this.itemClass = itemClass;
  }

  public CategoryOfItem extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public CategoryOfItem items(List<Item> items) {
    this.items = items;
    return this;
  }

  public CategoryOfItem addItemsItem(Item itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<Item>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @Schema(description = "")
  public List<Item> getItems() {
    return items;
  }

  public void setItems(List<Item> items) {
    this.items = items;
  }

  public CategoryOfItem children(List<CategoryOfItem> children) {
    this.children = children;
    return this;
  }

  public CategoryOfItem addChildrenItem(CategoryOfItem childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<CategoryOfItem>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @Schema(description = "")
  public List<CategoryOfItem> getChildren() {
    return children;
  }

  public void setChildren(List<CategoryOfItem> children) {
    this.children = children;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryOfItem categoryOfItem = (CategoryOfItem) o;
    return Objects.equals(this.id, categoryOfItem.id) &&
        Objects.equals(this.codeId, categoryOfItem.codeId) &&
        Objects.equals(this.name, categoryOfItem.name) &&
        Objects.equals(this.description, categoryOfItem.description) &&
        Objects.equals(this.parentId, categoryOfItem.parentId) &&
        Objects.equals(this.parent, categoryOfItem.parent) &&
        Objects.equals(this.categoryType, categoryOfItem.categoryType) &&
        Objects.equals(this.itemClass, categoryOfItem.itemClass) &&
        Objects.equals(this.extInfo, categoryOfItem.extInfo) &&
        Objects.equals(this.items, categoryOfItem.items) &&
        Objects.equals(this.children, categoryOfItem.children);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, codeId, name, description, parentId, parent, categoryType, itemClass, extInfo, items, children);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryOfItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    codeId: ").append(toIndentedString(codeId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    categoryType: ").append(toIndentedString(categoryType)).append("\n");
    sb.append("    itemClass: ").append(toIndentedString(itemClass)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
