/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CommandExecutionDetail
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class CommandExecutionDetail {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("commandExecutionId")
  private Integer commandExecutionId = null;

  @SerializedName("commandExecution")
  private CommandExecution commandExecution = null;

  @SerializedName("commandDetailId")
  private Integer commandDetailId = null;

  @SerializedName("commandDetail")
  private CommandDetail commandDetail = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("resultDetails")
  private String resultDetails = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  public CommandExecutionDetail id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public CommandExecutionDetail commandExecutionId(Integer commandExecutionId) {
    this.commandExecutionId = commandExecutionId;
    return this;
  }

   /**
   * Get commandExecutionId
   * @return commandExecutionId
  **/
  @Schema(required = true, description = "")
  public Integer getCommandExecutionId() {
    return commandExecutionId;
  }

  public void setCommandExecutionId(Integer commandExecutionId) {
    this.commandExecutionId = commandExecutionId;
  }

  public CommandExecutionDetail commandExecution(CommandExecution commandExecution) {
    this.commandExecution = commandExecution;
    return this;
  }

   /**
   * Get commandExecution
   * @return commandExecution
  **/
  @Schema(description = "")
  public CommandExecution getCommandExecution() {
    return commandExecution;
  }

  public void setCommandExecution(CommandExecution commandExecution) {
    this.commandExecution = commandExecution;
  }

  public CommandExecutionDetail commandDetailId(Integer commandDetailId) {
    this.commandDetailId = commandDetailId;
    return this;
  }

   /**
   * Get commandDetailId
   * @return commandDetailId
  **/
  @Schema(required = true, description = "")
  public Integer getCommandDetailId() {
    return commandDetailId;
  }

  public void setCommandDetailId(Integer commandDetailId) {
    this.commandDetailId = commandDetailId;
  }

  public CommandExecutionDetail commandDetail(CommandDetail commandDetail) {
    this.commandDetail = commandDetail;
    return this;
  }

   /**
   * Get commandDetail
   * @return commandDetail
  **/
  @Schema(description = "")
  public CommandDetail getCommandDetail() {
    return commandDetail;
  }

  public void setCommandDetail(CommandDetail commandDetail) {
    this.commandDetail = commandDetail;
  }

  public CommandExecutionDetail status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public CommandExecutionDetail resultDetails(String resultDetails) {
    this.resultDetails = resultDetails;
    return this;
  }

   /**
   * Get resultDetails
   * @return resultDetails
  **/
  @Schema(description = "")
  public String getResultDetails() {
    return resultDetails;
  }

  public void setResultDetails(String resultDetails) {
    this.resultDetails = resultDetails;
  }

  public CommandExecutionDetail note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @Schema(description = "")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public CommandExecutionDetail extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandExecutionDetail commandExecutionDetail = (CommandExecutionDetail) o;
    return Objects.equals(this.id, commandExecutionDetail.id) &&
        Objects.equals(this.commandExecutionId, commandExecutionDetail.commandExecutionId) &&
        Objects.equals(this.commandExecution, commandExecutionDetail.commandExecution) &&
        Objects.equals(this.commandDetailId, commandExecutionDetail.commandDetailId) &&
        Objects.equals(this.commandDetail, commandExecutionDetail.commandDetail) &&
        Objects.equals(this.status, commandExecutionDetail.status) &&
        Objects.equals(this.resultDetails, commandExecutionDetail.resultDetails) &&
        Objects.equals(this.note, commandExecutionDetail.note) &&
        Objects.equals(this.extInfo, commandExecutionDetail.extInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, commandExecutionId, commandExecution, commandDetailId, commandDetail, status, resultDetails, note, extInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandExecutionDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    commandExecutionId: ").append(toIndentedString(commandExecutionId)).append("\n");
    sb.append("    commandExecution: ").append(toIndentedString(commandExecution)).append("\n");
    sb.append("    commandDetailId: ").append(toIndentedString(commandDetailId)).append("\n");
    sb.append("    commandDetail: ").append(toIndentedString(commandDetail)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    resultDetails: ").append(toIndentedString(resultDetails)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
