/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CommandDetail
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class CommandDetail {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("commandId")
  private Integer commandId = null;

  @SerializedName("itemCodeId")
  private Integer itemCodeId = null;

  @SerializedName("itemUomId")
  private Integer itemUomId = null;

  @SerializedName("itemUom")
  private ItemUom itemUom = null;

  @SerializedName("itemName")
  private String itemName = null;

  @SerializedName("itemCode")
  private String itemCode = null;

  @SerializedName("codeType")
  private String codeType = null;

  @SerializedName("command")
  private Command command = null;

  @SerializedName("isPickExactly")
  private Boolean isPickExactly = null;

  @SerializedName("tagTypeId")
  private Integer tagTypeId = null;

  @SerializedName("tagType")
  private TagType tagType = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("specificItemIds")
  private String specificItemIds = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("commandExecutionDetails")
  private List<CommandExecutionDetail> commandExecutionDetails = null;

  public CommandDetail id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public CommandDetail commandId(Integer commandId) {
    this.commandId = commandId;
    return this;
  }

   /**
   * Get commandId
   * @return commandId
  **/
  @Schema(required = true, description = "")
  public Integer getCommandId() {
    return commandId;
  }

  public void setCommandId(Integer commandId) {
    this.commandId = commandId;
  }

  public CommandDetail itemCodeId(Integer itemCodeId) {
    this.itemCodeId = itemCodeId;
    return this;
  }

   /**
   * Get itemCodeId
   * @return itemCodeId
  **/
  @Schema(description = "")
  public Integer getItemCodeId() {
    return itemCodeId;
  }

  public void setItemCodeId(Integer itemCodeId) {
    this.itemCodeId = itemCodeId;
  }

  public CommandDetail itemUomId(Integer itemUomId) {
    this.itemUomId = itemUomId;
    return this;
  }

   /**
   * Get itemUomId
   * @return itemUomId
  **/
  @Schema(description = "")
  public Integer getItemUomId() {
    return itemUomId;
  }

  public void setItemUomId(Integer itemUomId) {
    this.itemUomId = itemUomId;
  }

  public CommandDetail itemUom(ItemUom itemUom) {
    this.itemUom = itemUom;
    return this;
  }

   /**
   * Get itemUom
   * @return itemUom
  **/
  @Schema(description = "")
  public ItemUom getItemUom() {
    return itemUom;
  }

  public void setItemUom(ItemUom itemUom) {
    this.itemUom = itemUom;
  }

  public CommandDetail itemName(String itemName) {
    this.itemName = itemName;
    return this;
  }

   /**
   * Get itemName
   * @return itemName
  **/
  @Schema(description = "")
  public String getItemName() {
    return itemName;
  }

  public void setItemName(String itemName) {
    this.itemName = itemName;
  }

  public CommandDetail itemCode(String itemCode) {
    this.itemCode = itemCode;
    return this;
  }

   /**
   * Get itemCode
   * @return itemCode
  **/
  @Schema(description = "")
  public String getItemCode() {
    return itemCode;
  }

  public void setItemCode(String itemCode) {
    this.itemCode = itemCode;
  }

  public CommandDetail codeType(String codeType) {
    this.codeType = codeType;
    return this;
  }

   /**
   * Get codeType
   * @return codeType
  **/
  @Schema(description = "")
  public String getCodeType() {
    return codeType;
  }

  public void setCodeType(String codeType) {
    this.codeType = codeType;
  }

  public CommandDetail command(Command command) {
    this.command = command;
    return this;
  }

   /**
   * Get command
   * @return command
  **/
  @Schema(description = "")
  public Command getCommand() {
    return command;
  }

  public void setCommand(Command command) {
    this.command = command;
  }

  public CommandDetail isPickExactly(Boolean isPickExactly) {
    this.isPickExactly = isPickExactly;
    return this;
  }

   /**
   * Get isPickExactly
   * @return isPickExactly
  **/
  @Schema(description = "")
  public Boolean isIsPickExactly() {
    return isPickExactly;
  }

  public void setIsPickExactly(Boolean isPickExactly) {
    this.isPickExactly = isPickExactly;
  }

  public CommandDetail tagTypeId(Integer tagTypeId) {
    this.tagTypeId = tagTypeId;
    return this;
  }

   /**
   * Get tagTypeId
   * @return tagTypeId
  **/
  @Schema(description = "")
  public Integer getTagTypeId() {
    return tagTypeId;
  }

  public void setTagTypeId(Integer tagTypeId) {
    this.tagTypeId = tagTypeId;
  }

  public CommandDetail tagType(TagType tagType) {
    this.tagType = tagType;
    return this;
  }

   /**
   * Get tagType
   * @return tagType
  **/
  @Schema(description = "")
  public TagType getTagType() {
    return tagType;
  }

  public void setTagType(TagType tagType) {
    this.tagType = tagType;
  }

  public CommandDetail quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(description = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public CommandDetail specificItemIds(String specificItemIds) {
    this.specificItemIds = specificItemIds;
    return this;
  }

   /**
   * Get specificItemIds
   * @return specificItemIds
  **/
  @Schema(description = "")
  public String getSpecificItemIds() {
    return specificItemIds;
  }

  public void setSpecificItemIds(String specificItemIds) {
    this.specificItemIds = specificItemIds;
  }

  public CommandDetail extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public CommandDetail commandExecutionDetails(List<CommandExecutionDetail> commandExecutionDetails) {
    this.commandExecutionDetails = commandExecutionDetails;
    return this;
  }

  public CommandDetail addCommandExecutionDetailsItem(CommandExecutionDetail commandExecutionDetailsItem) {
    if (this.commandExecutionDetails == null) {
      this.commandExecutionDetails = new ArrayList<CommandExecutionDetail>();
    }
    this.commandExecutionDetails.add(commandExecutionDetailsItem);
    return this;
  }

   /**
   * Get commandExecutionDetails
   * @return commandExecutionDetails
  **/
  @Schema(description = "")
  public List<CommandExecutionDetail> getCommandExecutionDetails() {
    return commandExecutionDetails;
  }

  public void setCommandExecutionDetails(List<CommandExecutionDetail> commandExecutionDetails) {
    this.commandExecutionDetails = commandExecutionDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandDetail commandDetail = (CommandDetail) o;
    return Objects.equals(this.id, commandDetail.id) &&
        Objects.equals(this.commandId, commandDetail.commandId) &&
        Objects.equals(this.itemCodeId, commandDetail.itemCodeId) &&
        Objects.equals(this.itemUomId, commandDetail.itemUomId) &&
        Objects.equals(this.itemUom, commandDetail.itemUom) &&
        Objects.equals(this.itemName, commandDetail.itemName) &&
        Objects.equals(this.itemCode, commandDetail.itemCode) &&
        Objects.equals(this.codeType, commandDetail.codeType) &&
        Objects.equals(this.command, commandDetail.command) &&
        Objects.equals(this.isPickExactly, commandDetail.isPickExactly) &&
        Objects.equals(this.tagTypeId, commandDetail.tagTypeId) &&
        Objects.equals(this.tagType, commandDetail.tagType) &&
        Objects.equals(this.quantity, commandDetail.quantity) &&
        Objects.equals(this.specificItemIds, commandDetail.specificItemIds) &&
        Objects.equals(this.extInfo, commandDetail.extInfo) &&
        Objects.equals(this.commandExecutionDetails, commandDetail.commandExecutionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, commandId, itemCodeId, itemUomId, itemUom, itemName, itemCode, codeType, command, isPickExactly, tagTypeId, tagType, quantity, specificItemIds, extInfo, commandExecutionDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    commandId: ").append(toIndentedString(commandId)).append("\n");
    sb.append("    itemCodeId: ").append(toIndentedString(itemCodeId)).append("\n");
    sb.append("    itemUomId: ").append(toIndentedString(itemUomId)).append("\n");
    sb.append("    itemUom: ").append(toIndentedString(itemUom)).append("\n");
    sb.append("    itemName: ").append(toIndentedString(itemName)).append("\n");
    sb.append("    itemCode: ").append(toIndentedString(itemCode)).append("\n");
    sb.append("    codeType: ").append(toIndentedString(codeType)).append("\n");
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    isPickExactly: ").append(toIndentedString(isPickExactly)).append("\n");
    sb.append("    tagTypeId: ").append(toIndentedString(tagTypeId)).append("\n");
    sb.append("    tagType: ").append(toIndentedString(tagType)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    specificItemIds: ").append(toIndentedString(specificItemIds)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    commandExecutionDetails: ").append(toIndentedString(commandExecutionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
