/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CommandExecution
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class CommandExecution {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("commandId")
  private Integer commandId = null;

  @SerializedName("command")
  private Command command = null;

  @SerializedName("executedBy")
  private String executedBy = null;

  @SerializedName("aspNetUser")
  private AspNetUser aspNetUser = null;

  @SerializedName("executedAt")
  private OffsetDateTime executedAt = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("commandExecutionDetails")
  private List<CommandExecutionDetail> commandExecutionDetails = null;

  public CommandExecution id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public CommandExecution commandId(Integer commandId) {
    this.commandId = commandId;
    return this;
  }

   /**
   * Get commandId
   * @return commandId
  **/
  @Schema(required = true, description = "")
  public Integer getCommandId() {
    return commandId;
  }

  public void setCommandId(Integer commandId) {
    this.commandId = commandId;
  }

  public CommandExecution command(Command command) {
    this.command = command;
    return this;
  }

   /**
   * Get command
   * @return command
  **/
  @Schema(description = "")
  public Command getCommand() {
    return command;
  }

  public void setCommand(Command command) {
    this.command = command;
  }

  public CommandExecution executedBy(String executedBy) {
    this.executedBy = executedBy;
    return this;
  }

   /**
   * Get executedBy
   * @return executedBy
  **/
  @Schema(required = true, description = "")
  public String getExecutedBy() {
    return executedBy;
  }

  public void setExecutedBy(String executedBy) {
    this.executedBy = executedBy;
  }

  public CommandExecution aspNetUser(AspNetUser aspNetUser) {
    this.aspNetUser = aspNetUser;
    return this;
  }

   /**
   * Get aspNetUser
   * @return aspNetUser
  **/
  @Schema(description = "")
  public AspNetUser getAspNetUser() {
    return aspNetUser;
  }

  public void setAspNetUser(AspNetUser aspNetUser) {
    this.aspNetUser = aspNetUser;
  }

  public CommandExecution executedAt(OffsetDateTime executedAt) {
    this.executedAt = executedAt;
    return this;
  }

   /**
   * Get executedAt
   * @return executedAt
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getExecutedAt() {
    return executedAt;
  }

  public void setExecutedAt(OffsetDateTime executedAt) {
    this.executedAt = executedAt;
  }

  public CommandExecution status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public CommandExecution note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @Schema(description = "")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public CommandExecution extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public CommandExecution commandExecutionDetails(List<CommandExecutionDetail> commandExecutionDetails) {
    this.commandExecutionDetails = commandExecutionDetails;
    return this;
  }

  public CommandExecution addCommandExecutionDetailsItem(CommandExecutionDetail commandExecutionDetailsItem) {
    if (this.commandExecutionDetails == null) {
      this.commandExecutionDetails = new ArrayList<CommandExecutionDetail>();
    }
    this.commandExecutionDetails.add(commandExecutionDetailsItem);
    return this;
  }

   /**
   * Get commandExecutionDetails
   * @return commandExecutionDetails
  **/
  @Schema(description = "")
  public List<CommandExecutionDetail> getCommandExecutionDetails() {
    return commandExecutionDetails;
  }

  public void setCommandExecutionDetails(List<CommandExecutionDetail> commandExecutionDetails) {
    this.commandExecutionDetails = commandExecutionDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandExecution commandExecution = (CommandExecution) o;
    return Objects.equals(this.id, commandExecution.id) &&
        Objects.equals(this.commandId, commandExecution.commandId) &&
        Objects.equals(this.command, commandExecution.command) &&
        Objects.equals(this.executedBy, commandExecution.executedBy) &&
        Objects.equals(this.aspNetUser, commandExecution.aspNetUser) &&
        Objects.equals(this.executedAt, commandExecution.executedAt) &&
        Objects.equals(this.status, commandExecution.status) &&
        Objects.equals(this.note, commandExecution.note) &&
        Objects.equals(this.extInfo, commandExecution.extInfo) &&
        Objects.equals(this.commandExecutionDetails, commandExecution.commandExecutionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, commandId, command, executedBy, aspNetUser, executedAt, status, note, extInfo, commandExecutionDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandExecution {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    commandId: ").append(toIndentedString(commandId)).append("\n");
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    executedBy: ").append(toIndentedString(executedBy)).append("\n");
    sb.append("    aspNetUser: ").append(toIndentedString(aspNetUser)).append("\n");
    sb.append("    executedAt: ").append(toIndentedString(executedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    commandExecutionDetails: ").append(toIndentedString(commandExecutionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
