/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CommandSchedule
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class CommandSchedule {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("isDefault")
  private Boolean isDefault = null;

  @SerializedName("runContinuous")
  private Boolean runContinuous = null;

  @SerializedName("runEveryDay")
  private Boolean runEveryDay = null;

  @SerializedName("runOnDaysOfWeeks")
  private String runOnDaysOfWeeks = null;

  @SerializedName("runOnDaysOfMonths")
  private String runOnDaysOfMonths = null;

  @SerializedName("runOnce")
  private Boolean runOnce = null;

  @SerializedName("runMany")
  private Boolean runMany = null;

  @SerializedName("atTime")
  private String atTime = null;

  @SerializedName("cancelOnError")
  private Boolean cancelOnError = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("commands")
  private List<Command> commands = null;

  public CommandSchedule id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public CommandSchedule name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CommandSchedule description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CommandSchedule isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Get isDefault
   * @return isDefault
  **/
  @Schema(description = "")
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public CommandSchedule runContinuous(Boolean runContinuous) {
    this.runContinuous = runContinuous;
    return this;
  }

   /**
   * Get runContinuous
   * @return runContinuous
  **/
  @Schema(description = "")
  public Boolean isRunContinuous() {
    return runContinuous;
  }

  public void setRunContinuous(Boolean runContinuous) {
    this.runContinuous = runContinuous;
  }

  public CommandSchedule runEveryDay(Boolean runEveryDay) {
    this.runEveryDay = runEveryDay;
    return this;
  }

   /**
   * Get runEveryDay
   * @return runEveryDay
  **/
  @Schema(description = "")
  public Boolean isRunEveryDay() {
    return runEveryDay;
  }

  public void setRunEveryDay(Boolean runEveryDay) {
    this.runEveryDay = runEveryDay;
  }

  public CommandSchedule runOnDaysOfWeeks(String runOnDaysOfWeeks) {
    this.runOnDaysOfWeeks = runOnDaysOfWeeks;
    return this;
  }

   /**
   * Get runOnDaysOfWeeks
   * @return runOnDaysOfWeeks
  **/
  @Schema(description = "")
  public String getRunOnDaysOfWeeks() {
    return runOnDaysOfWeeks;
  }

  public void setRunOnDaysOfWeeks(String runOnDaysOfWeeks) {
    this.runOnDaysOfWeeks = runOnDaysOfWeeks;
  }

  public CommandSchedule runOnDaysOfMonths(String runOnDaysOfMonths) {
    this.runOnDaysOfMonths = runOnDaysOfMonths;
    return this;
  }

   /**
   * Get runOnDaysOfMonths
   * @return runOnDaysOfMonths
  **/
  @Schema(description = "")
  public String getRunOnDaysOfMonths() {
    return runOnDaysOfMonths;
  }

  public void setRunOnDaysOfMonths(String runOnDaysOfMonths) {
    this.runOnDaysOfMonths = runOnDaysOfMonths;
  }

  public CommandSchedule runOnce(Boolean runOnce) {
    this.runOnce = runOnce;
    return this;
  }

   /**
   * Get runOnce
   * @return runOnce
  **/
  @Schema(description = "")
  public Boolean isRunOnce() {
    return runOnce;
  }

  public void setRunOnce(Boolean runOnce) {
    this.runOnce = runOnce;
  }

  public CommandSchedule runMany(Boolean runMany) {
    this.runMany = runMany;
    return this;
  }

   /**
   * Get runMany
   * @return runMany
  **/
  @Schema(description = "")
  public Boolean isRunMany() {
    return runMany;
  }

  public void setRunMany(Boolean runMany) {
    this.runMany = runMany;
  }

  public CommandSchedule atTime(String atTime) {
    this.atTime = atTime;
    return this;
  }

   /**
   * Get atTime
   * @return atTime
  **/
  @Schema(description = "")
  public String getAtTime() {
    return atTime;
  }

  public void setAtTime(String atTime) {
    this.atTime = atTime;
  }

  public CommandSchedule cancelOnError(Boolean cancelOnError) {
    this.cancelOnError = cancelOnError;
    return this;
  }

   /**
   * Get cancelOnError
   * @return cancelOnError
  **/
  @Schema(description = "")
  public Boolean isCancelOnError() {
    return cancelOnError;
  }

  public void setCancelOnError(Boolean cancelOnError) {
    this.cancelOnError = cancelOnError;
  }

  public CommandSchedule extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public CommandSchedule commands(List<Command> commands) {
    this.commands = commands;
    return this;
  }

  public CommandSchedule addCommandsItem(Command commandsItem) {
    if (this.commands == null) {
      this.commands = new ArrayList<Command>();
    }
    this.commands.add(commandsItem);
    return this;
  }

   /**
   * Get commands
   * @return commands
  **/
  @Schema(description = "")
  public List<Command> getCommands() {
    return commands;
  }

  public void setCommands(List<Command> commands) {
    this.commands = commands;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandSchedule commandSchedule = (CommandSchedule) o;
    return Objects.equals(this.id, commandSchedule.id) &&
        Objects.equals(this.name, commandSchedule.name) &&
        Objects.equals(this.description, commandSchedule.description) &&
        Objects.equals(this.isDefault, commandSchedule.isDefault) &&
        Objects.equals(this.runContinuous, commandSchedule.runContinuous) &&
        Objects.equals(this.runEveryDay, commandSchedule.runEveryDay) &&
        Objects.equals(this.runOnDaysOfWeeks, commandSchedule.runOnDaysOfWeeks) &&
        Objects.equals(this.runOnDaysOfMonths, commandSchedule.runOnDaysOfMonths) &&
        Objects.equals(this.runOnce, commandSchedule.runOnce) &&
        Objects.equals(this.runMany, commandSchedule.runMany) &&
        Objects.equals(this.atTime, commandSchedule.atTime) &&
        Objects.equals(this.cancelOnError, commandSchedule.cancelOnError) &&
        Objects.equals(this.extInfo, commandSchedule.extInfo) &&
        Objects.equals(this.commands, commandSchedule.commands);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, isDefault, runContinuous, runEveryDay, runOnDaysOfWeeks, runOnDaysOfMonths, runOnce, runMany, atTime, cancelOnError, extInfo, commands);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandSchedule {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    runContinuous: ").append(toIndentedString(runContinuous)).append("\n");
    sb.append("    runEveryDay: ").append(toIndentedString(runEveryDay)).append("\n");
    sb.append("    runOnDaysOfWeeks: ").append(toIndentedString(runOnDaysOfWeeks)).append("\n");
    sb.append("    runOnDaysOfMonths: ").append(toIndentedString(runOnDaysOfMonths)).append("\n");
    sb.append("    runOnce: ").append(toIndentedString(runOnce)).append("\n");
    sb.append("    runMany: ").append(toIndentedString(runMany)).append("\n");
    sb.append("    atTime: ").append(toIndentedString(atTime)).append("\n");
    sb.append("    cancelOnError: ").append(toIndentedString(cancelOnError)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    commands: ").append(toIndentedString(commands)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
