/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.Arrays;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Command
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class Command {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("workflowId")
  private String workflowId = null;

  @SerializedName("locationId")
  private long locationId = 0;

  @SerializedName("locationRelationType")
  private Integer locationRelationType = null;

  @SerializedName("locationId1")
  private Integer locationId1 = null;

  @SerializedName("locationRelationType1")
  private Integer locationRelationType1 = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("isBarcodeCommand")
  private Boolean isBarcodeCommand = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("commandTypeId")
  private Integer commandTypeId = null;

  @SerializedName("createBy")
  private String createBy = null;

  @SerializedName("createAt")
  private OffsetDateTime createAt = null;

  @SerializedName("assignTo")
  private String assignTo = null;

  @SerializedName("commandScheduleId")
  private Integer commandScheduleId = null;

  @SerializedName("commandSchedule")
  private CommandSchedule commandSchedule = null;

  @SerializedName("attachment")
  private byte[] attachment = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  public Command id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Command workflowId(String workflowId) {
    this.workflowId = workflowId;
    return this;
  }

   /**
   * Get workflowId
   * @return workflowId
  **/
  @Schema(description = "")
  public String getWorkflowId() {
    return workflowId;
  }

  public void setWorkflowId(String workflowId) {
    this.workflowId = workflowId;
  }

  public Command locationId(Integer locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @Schema(description = "")
  public long getLocationId() {
    return locationId;
  }

  public void setLocationId(long locationId) {
    this.locationId = locationId;
  }

  public Command locationRelationType(Integer locationRelationType) {
    this.locationRelationType = locationRelationType;
    return this;
  }

   /**
   * Get locationRelationType
   * @return locationRelationType
  **/
  @Schema(required = true, description = "")
  public Integer getLocationRelationType() {
    return locationRelationType;
  }

  public void setLocationRelationType(Integer locationRelationType) {
    this.locationRelationType = locationRelationType;
  }

  public Command locationId1(Integer locationId1) {
    this.locationId1 = locationId1;
    return this;
  }

   /**
   * Get locationId1
   * @return locationId1
  **/
  @Schema(description = "")
  public Integer getLocationId1() {
    return locationId1;
  }

  public void setLocationId1(Integer locationId1) {
    this.locationId1 = locationId1;
  }

  public Command locationRelationType1(Integer locationRelationType1) {
    this.locationRelationType1 = locationRelationType1;
    return this;
  }

   /**
   * Get locationRelationType1
   * @return locationRelationType1
  **/
  @Schema(description = "")
  public Integer getLocationRelationType1() {
    return locationRelationType1;
  }

  public void setLocationRelationType1(Integer locationRelationType1) {
    this.locationRelationType1 = locationRelationType1;
  }

  public Command name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Command isBarcodeCommand(Boolean isBarcodeCommand) {
    this.isBarcodeCommand = isBarcodeCommand;
    return this;
  }

   /**
   * Get isBarcodeCommand
   * @return isBarcodeCommand
  **/
  @Schema(description = "")
  public Boolean isIsBarcodeCommand() {
    return isBarcodeCommand;
  }

  public void setIsBarcodeCommand(Boolean isBarcodeCommand) {
    this.isBarcodeCommand = isBarcodeCommand;
  }

  public Command status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Command commandTypeId(Integer commandTypeId) {
    this.commandTypeId = commandTypeId;
    return this;
  }

   /**
   * Get commandTypeId
   * @return commandTypeId
  **/
  @Schema(required = true, description = "")
  public Integer getCommandTypeId() {
    return commandTypeId;
  }

  public void setCommandTypeId(Integer commandTypeId) {
    this.commandTypeId = commandTypeId;
  }

  public Command createBy(String createBy) {
    this.createBy = createBy;
    return this;
  }

   /**
   * Get createBy
   * @return createBy
  **/
  @Schema(description = "")
  public String getCreateBy() {
    return createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Command createAt(OffsetDateTime createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * Get createAt
   * @return createAt
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getCreateAt() {
    return createAt;
  }

  public void setCreateAt(OffsetDateTime createAt) {
    this.createAt = createAt;
  }

  public Command assignTo(String assignTo) {
    this.assignTo = assignTo;
    return this;
  }

   /**
   * Get assignTo
   * @return assignTo
  **/
  @Schema(description = "")
  public String getAssignTo() {
    return assignTo;
  }

  public void setAssignTo(String assignTo) {
    this.assignTo = assignTo;
  }

  public Command commandScheduleId(Integer commandScheduleId) {
    this.commandScheduleId = commandScheduleId;
    return this;
  }

   /**
   * Get commandScheduleId
   * @return commandScheduleId
  **/
  @Schema(description = "")
  public Integer getCommandScheduleId() {
    return commandScheduleId;
  }

  public void setCommandScheduleId(Integer commandScheduleId) {
    this.commandScheduleId = commandScheduleId;
  }

  public Command commandSchedule(CommandSchedule commandSchedule) {
    this.commandSchedule = commandSchedule;
    return this;
  }

   /**
   * Get commandSchedule
   * @return commandSchedule
  **/
  @Schema(description = "")
  public CommandSchedule getCommandSchedule() {
    return commandSchedule;
  }

  public void setCommandSchedule(CommandSchedule commandSchedule) {
    this.commandSchedule = commandSchedule;
  }

  public Command attachment(byte[] attachment) {
    this.attachment = attachment;
    return this;
  }

   /**
   * Get attachment
   * @return attachment
  **/
  @Schema(description = "")
  public byte[] getAttachment() {
    return attachment;
  }

  public void setAttachment(byte[] attachment) {
    this.attachment = attachment;
  }

  public Command note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @Schema(description = "")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public Command extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Command command = (Command) o;
    return Objects.equals(this.id, command.id) &&
        Objects.equals(this.workflowId, command.workflowId) &&
        Objects.equals(this.locationId, command.locationId) &&
        Objects.equals(this.locationRelationType, command.locationRelationType) &&
        Objects.equals(this.locationId1, command.locationId1) &&
        Objects.equals(this.locationRelationType1, command.locationRelationType1) &&
        Objects.equals(this.name, command.name) &&
        Objects.equals(this.isBarcodeCommand, command.isBarcodeCommand) &&
        Objects.equals(this.status, command.status) &&
        Objects.equals(this.commandTypeId, command.commandTypeId) &&
        Objects.equals(this.createBy, command.createBy) &&
        Objects.equals(this.createAt, command.createAt) &&
        Objects.equals(this.assignTo, command.assignTo) &&
        Objects.equals(this.commandScheduleId, command.commandScheduleId) &&
        Objects.equals(this.commandSchedule, command.commandSchedule) &&
        Arrays.equals(this.attachment, command.attachment) &&
        Objects.equals(this.note, command.note) &&
        Objects.equals(this.extInfo, command.extInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, workflowId, locationId, locationRelationType, locationId1, locationRelationType1, name, isBarcodeCommand, status, commandTypeId, createBy, createAt, assignTo, commandScheduleId, commandSchedule, Arrays.hashCode(attachment), note, extInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Command {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    locationRelationType: ").append(toIndentedString(locationRelationType)).append("\n");
    sb.append("    locationId1: ").append(toIndentedString(locationId1)).append("\n");
    sb.append("    locationRelationType1: ").append(toIndentedString(locationRelationType1)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isBarcodeCommand: ").append(toIndentedString(isBarcodeCommand)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    commandTypeId: ").append(toIndentedString(commandTypeId)).append("\n");
    sb.append("    createBy: ").append(toIndentedString(createBy)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    assignTo: ").append(toIndentedString(assignTo)).append("\n");
    sb.append("    commandScheduleId: ").append(toIndentedString(commandScheduleId)).append("\n");
    sb.append("    commandSchedule: ").append(toIndentedString(commandSchedule)).append("\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public void setLocation(Location selectedLocation) {
      location = selectedLocation;
    }
    private Location location;
    public Location getLocation() {
      return location;
    }
}
