/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Guest
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class Guest {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("eventId")
  private Integer eventId = null;

  @SerializedName("event")
  private Event event = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("company")
  private String company = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("rfid")
  private String rfid = null;

  @SerializedName("invitationSent")
  private Boolean invitationSent = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("detectLogs")
  private List<DetectLog> detectLogs = null;

  @SerializedName("jobTitle")
  private String jobTitle = null;

  public Guest id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Guest eventId(Integer eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  @Schema(required = true, description = "")
  public Integer getEventId() {
    return eventId;
  }

  public void setEventId(Integer eventId) {
    this.eventId = eventId;
  }

  public Guest event(Event event) {
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  @Schema(description = "")
  public Event getEvent() {
    return event;
  }

  public void setEvent(Event event) {
    this.event = event;
  }

  public Guest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Guest company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @Schema(description = "")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public Guest address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public Guest email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(required = true, description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Guest phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @Schema(description = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Guest image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(description = "")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public Guest rfid(String rfid) {
    this.rfid = rfid;
    return this;
  }

   /**
   * Get rfid
   * @return rfid
  **/
  @Schema(required = true, description = "")
  public String getRfid() {
    return rfid;
  }

  public void setRfid(String rfid) {
    this.rfid = rfid;
  }

  public Guest invitationSent(Boolean invitationSent) {
    this.invitationSent = invitationSent;
    return this;
  }

   /**
   * Get invitationSent
   * @return invitationSent
  **/
  @Schema(description = "")
  public Boolean isInvitationSent() {
    return invitationSent;
  }

  public void setInvitationSent(Boolean invitationSent) {
    this.invitationSent = invitationSent;
  }

  public Guest extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public Guest detectLogs(List<DetectLog> detectLogs) {
    this.detectLogs = detectLogs;
    return this;
  }

  public Guest addDetectLogsItem(DetectLog detectLogsItem) {
    if (this.detectLogs == null) {
      this.detectLogs = new ArrayList<DetectLog>();
    }
    this.detectLogs.add(detectLogsItem);
    return this;
  }

   /**
   * Get detectLogs
   * @return detectLogs
  **/
  @Schema(description = "")
  public List<DetectLog> getDetectLogs() {
    return detectLogs;
  }

  public void setDetectLogs(List<DetectLog> detectLogs) {
    this.detectLogs = detectLogs;
  }

  public Guest jobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
    return this;
  }

   /**
   * Get jobTitle
   * @return jobTitle
  **/
  @Schema(description = "")
  public String getJobTitle() {
    return jobTitle;
  }

  public void setJobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Guest guest = (Guest) o;
    return Objects.equals(this.id, guest.id) &&
        Objects.equals(this.eventId, guest.eventId) &&
        Objects.equals(this.event, guest.event) &&
        Objects.equals(this.name, guest.name) &&
        Objects.equals(this.company, guest.company) &&
        Objects.equals(this.address, guest.address) &&
        Objects.equals(this.email, guest.email) &&
        Objects.equals(this.phone, guest.phone) &&
        Objects.equals(this.image, guest.image) &&
        Objects.equals(this.rfid, guest.rfid) &&
        Objects.equals(this.invitationSent, guest.invitationSent) &&
        Objects.equals(this.extInfo, guest.extInfo) &&
        Objects.equals(this.detectLogs, guest.detectLogs) &&
        Objects.equals(this.jobTitle, guest.jobTitle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, eventId, event, name, company, address, email, phone, image, rfid, invitationSent, extInfo, detectLogs, jobTitle);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Guest {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    rfid: ").append(toIndentedString(rfid)).append("\n");
    sb.append("    invitationSent: ").append(toIndentedString(invitationSent)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    detectLogs: ").append(toIndentedString(detectLogs)).append("\n");
    sb.append("    jobTitle: ").append(toIndentedString(jobTitle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
