/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Inventory
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class Inventory {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("locationId")
  private Integer locationId = null;

  @SerializedName("location")
  private Location location = null;

  @SerializedName("commandId")
  private Integer commandId = null;

  @SerializedName("commandExecutionId")
  private Integer commandExecutionId = null;

  @SerializedName("workflowInstanceId")
  private String workflowInstanceId = null;

  @SerializedName("commandExecutionDetailId")
  private Integer commandExecutionDetailId = null;

  @SerializedName("commandExecutionDetail")
  private CommandExecutionDetail commandExecutionDetail = null;

  @SerializedName("itemUomId")
  private Integer itemUomId = null;

  @SerializedName("itemUom")
  private ItemUom itemUom = null;

  @SerializedName("requiredQuantity")
  private Integer requiredQuantity = null;

  @SerializedName("execQuantity")
  private Integer execQuantity = null;

  @SerializedName("operationType")
  private Integer operationType = null;

  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("commandExecution")
  private CommandExecution commandExecution = null;

  public Inventory id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Inventory locationId(Integer locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @Schema(required = true, description = "")
  public Integer getLocationId() {
    return locationId;
  }

  public void setLocationId(Integer locationId) {
    this.locationId = locationId;
  }

  public Inventory location(Location location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @Schema(description = "")
  public Location getLocation() {
    return location;
  }

  public void setLocation(Location location) {
    this.location = location;
  }

  public Inventory commandId(Integer commandId) {
    this.commandId = commandId;
    return this;
  }

   /**
   * Get commandId
   * @return commandId
  **/
  @Schema(description = "")
  public Integer getCommandId() {
    return commandId;
  }

  public void setCommandId(Integer commandId) {
    this.commandId = commandId;
  }

  public Inventory commandExecutionId(Integer commandExecutionId) {
    this.commandExecutionId = commandExecutionId;
    return this;
  }

   /**
   * Get commandExecutionId
   * @return commandExecutionId
  **/
  @Schema(description = "")
  public Integer getCommandExecutionId() {
    return commandExecutionId;
  }

  public void setCommandExecutionId(Integer commandExecutionId) {
    this.commandExecutionId = commandExecutionId;
  }

  public Inventory workflowInstanceId(String workflowInstanceId) {
    this.workflowInstanceId = workflowInstanceId;
    return this;
  }

   /**
   * Get workflowInstanceId
   * @return workflowInstanceId
  **/
  @Schema(description = "")
  public String getWorkflowInstanceId() {
    return workflowInstanceId;
  }

  public void setWorkflowInstanceId(String workflowInstanceId) {
    this.workflowInstanceId = workflowInstanceId;
  }

  public Inventory commandExecutionDetailId(Integer commandExecutionDetailId) {
    this.commandExecutionDetailId = commandExecutionDetailId;
    return this;
  }

   /**
   * Get commandExecutionDetailId
   * @return commandExecutionDetailId
  **/
  @Schema(required = true, description = "")
  public Integer getCommandExecutionDetailId() {
    return commandExecutionDetailId;
  }

  public void setCommandExecutionDetailId(Integer commandExecutionDetailId) {
    this.commandExecutionDetailId = commandExecutionDetailId;
  }

  public Inventory commandExecutionDetail(CommandExecutionDetail commandExecutionDetail) {
    this.commandExecutionDetail = commandExecutionDetail;
    return this;
  }

   /**
   * Get commandExecutionDetail
   * @return commandExecutionDetail
  **/
  @Schema(description = "")
  public CommandExecutionDetail getCommandExecutionDetail() {
    return commandExecutionDetail;
  }

  public void setCommandExecutionDetail(CommandExecutionDetail commandExecutionDetail) {
    this.commandExecutionDetail = commandExecutionDetail;
  }

  public Inventory itemUomId(Integer itemUomId) {
    this.itemUomId = itemUomId;
    return this;
  }

   /**
   * Get itemUomId
   * @return itemUomId
  **/
  @Schema(required = true, description = "")
  public Integer getItemUomId() {
    return itemUomId;
  }

  public void setItemUomId(Integer itemUomId) {
    this.itemUomId = itemUomId;
  }

  public Inventory itemUom(ItemUom itemUom) {
    this.itemUom = itemUom;
    return this;
  }

   /**
   * Get itemUom
   * @return itemUom
  **/
  @Schema(description = "")
  public ItemUom getItemUom() {
    return itemUom;
  }

  public void setItemUom(ItemUom itemUom) {
    this.itemUom = itemUom;
  }

  public Inventory requiredQuantity(Integer requiredQuantity) {
    this.requiredQuantity = requiredQuantity;
    return this;
  }

   /**
   * Get requiredQuantity
   * @return requiredQuantity
  **/
  @Schema(required = true, description = "")
  public Integer getRequiredQuantity() {
    return requiredQuantity;
  }

  public void setRequiredQuantity(Integer requiredQuantity) {
    this.requiredQuantity = requiredQuantity;
  }

  public Inventory execQuantity(Integer execQuantity) {
    this.execQuantity = execQuantity;
    return this;
  }

   /**
   * Get execQuantity
   * @return execQuantity
  **/
  @Schema(required = true, description = "")
  public Integer getExecQuantity() {
    return execQuantity;
  }

  public void setExecQuantity(Integer execQuantity) {
    this.execQuantity = execQuantity;
  }

  public Inventory operationType(Integer operationType) {
    this.operationType = operationType;
    return this;
  }

   /**
   * Get operationType
   * @return operationType
  **/
  @Schema(description = "")
  public Integer getOperationType() {
    return operationType;
  }

  public void setOperationType(Integer operationType) {
    this.operationType = operationType;
  }

  public Inventory createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Inventory extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public Inventory commandExecution(CommandExecution commandExecution) {
    this.commandExecution = commandExecution;
    return this;
  }

   /**
   * Get commandExecution
   * @return commandExecution
  **/
  @Schema(description = "")
  public CommandExecution getCommandExecution() {
    return commandExecution;
  }

  public void setCommandExecution(CommandExecution commandExecution) {
    this.commandExecution = commandExecution;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Inventory inventory = (Inventory) o;
    return Objects.equals(this.id, inventory.id) &&
        Objects.equals(this.locationId, inventory.locationId) &&
        Objects.equals(this.location, inventory.location) &&
        Objects.equals(this.commandId, inventory.commandId) &&
        Objects.equals(this.commandExecutionId, inventory.commandExecutionId) &&
        Objects.equals(this.workflowInstanceId, inventory.workflowInstanceId) &&
        Objects.equals(this.commandExecutionDetailId, inventory.commandExecutionDetailId) &&
        Objects.equals(this.commandExecutionDetail, inventory.commandExecutionDetail) &&
        Objects.equals(this.itemUomId, inventory.itemUomId) &&
        Objects.equals(this.itemUom, inventory.itemUom) &&
        Objects.equals(this.requiredQuantity, inventory.requiredQuantity) &&
        Objects.equals(this.execQuantity, inventory.execQuantity) &&
        Objects.equals(this.operationType, inventory.operationType) &&
        Objects.equals(this.createdAt, inventory.createdAt) &&
        Objects.equals(this.extInfo, inventory.extInfo) &&
        Objects.equals(this.commandExecution, inventory.commandExecution);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, locationId, location, commandId, commandExecutionId, workflowInstanceId, commandExecutionDetailId, commandExecutionDetail, itemUomId, itemUom, requiredQuantity, execQuantity, operationType, createdAt, extInfo, commandExecution);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Inventory {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    commandId: ").append(toIndentedString(commandId)).append("\n");
    sb.append("    commandExecutionId: ").append(toIndentedString(commandExecutionId)).append("\n");
    sb.append("    workflowInstanceId: ").append(toIndentedString(workflowInstanceId)).append("\n");
    sb.append("    commandExecutionDetailId: ").append(toIndentedString(commandExecutionDetailId)).append("\n");
    sb.append("    commandExecutionDetail: ").append(toIndentedString(commandExecutionDetail)).append("\n");
    sb.append("    itemUomId: ").append(toIndentedString(itemUomId)).append("\n");
    sb.append("    itemUom: ").append(toIndentedString(itemUom)).append("\n");
    sb.append("    requiredQuantity: ").append(toIndentedString(requiredQuantity)).append("\n");
    sb.append("    execQuantity: ").append(toIndentedString(execQuantity)).append("\n");
    sb.append("    operationType: ").append(toIndentedString(operationType)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    commandExecution: ").append(toIndentedString(commandExecution)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
