/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ItemRelation
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class ItemRelation {
  @SerializedName("itemId")
  private Integer itemId = null;

  @SerializedName("item")
  private Item item = null;

  @SerializedName("relatedItemId")
  private Integer relatedItemId = null;

  @SerializedName("item1")
  private Item item1 = null;

  @SerializedName("relationType")
  private Integer relationType = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  public ItemRelation itemId(Integer itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * Get itemId
   * @return itemId
  **/
  @Schema(required = true, description = "")
  public Integer getItemId() {
    return itemId;
  }

  public void setItemId(Integer itemId) {
    this.itemId = itemId;
  }

  public ItemRelation item(Item item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @Schema(description = "")
  public Item getItem() {
    return item;
  }

  public void setItem(Item item) {
    this.item = item;
  }

  public ItemRelation relatedItemId(Integer relatedItemId) {
    this.relatedItemId = relatedItemId;
    return this;
  }

   /**
   * Get relatedItemId
   * @return relatedItemId
  **/
  @Schema(required = true, description = "")
  public Integer getRelatedItemId() {
    return relatedItemId;
  }

  public void setRelatedItemId(Integer relatedItemId) {
    this.relatedItemId = relatedItemId;
  }

  public ItemRelation item1(Item item1) {
    this.item1 = item1;
    return this;
  }

   /**
   * Get item1
   * @return item1
  **/
  @Schema(description = "")
  public Item getItem1() {
    return item1;
  }

  public void setItem1(Item item1) {
    this.item1 = item1;
  }

  public ItemRelation relationType(Integer relationType) {
    this.relationType = relationType;
    return this;
  }

   /**
   * Get relationType
   * @return relationType
  **/
  @Schema(description = "")
  public Integer getRelationType() {
    return relationType;
  }

  public void setRelationType(Integer relationType) {
    this.relationType = relationType;
  }

  public ItemRelation extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemRelation itemRelation = (ItemRelation) o;
    return Objects.equals(this.itemId, itemRelation.itemId) &&
        Objects.equals(this.item, itemRelation.item) &&
        Objects.equals(this.relatedItemId, itemRelation.relatedItemId) &&
        Objects.equals(this.item1, itemRelation.item1) &&
        Objects.equals(this.relationType, itemRelation.relationType) &&
        Objects.equals(this.extInfo, itemRelation.extInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemId, item, relatedItemId, item1, relationType, extInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemRelation {\n");
    
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    relatedItemId: ").append(toIndentedString(relatedItemId)).append("\n");
    sb.append("    item1: ").append(toIndentedString(item1)).append("\n");
    sb.append("    relationType: ").append(toIndentedString(relationType)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
