/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Transient;
import io.swagger.v3.oas.annotations.media.Schema;
//import org.threeten.bp.Date;
/**
 * Item
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")
@Entity
public class Item {
  @Id
  @SerializedName("id")
  private long id = 0;

  @SerializedName("rfidTagId")
  private Integer rfidTagId = null;

  @Transient
  @SerializedName("rfidTag")
  private RfidTag rfidTag = null;

  @SerializedName("taggedDate")
  private Date taggedDate = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("categoryOfItemId")
  private Integer categoryOfItemId = null;

  @Transient
  @SerializedName("categoryOfItem")
  private CategoryOfItem categoryOfItem = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("data")
  private String data = null;

  @SerializedName("state")
  private Integer state = null;

  @SerializedName("isDeleted")
  private Boolean isDeleted = null;

  @SerializedName("extInfo")
  private String extInfo = null;

//  @SerializedName("itemRelations")
//  private List<ItemRelation> itemRelations = null;

//  @SerializedName("itemRelations1")
//  private List<ItemRelation> itemRelations1 = null;

  @SerializedName("itemMedia")
  private List<ItemMedia> itemMedia = null;

  @SerializedName("itemUoms")
  private List<ItemUom> itemUoms = null;

  @SerializedName("batches")
  private List<Batch> batches = null;

  public Item id(long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Item rfidTagId(Integer rfidTagId) {
    this.rfidTagId = rfidTagId;
    return this;
  }

   /**
   * Get rfidTagId
   * @return rfidTagId
  **/
  @Schema(description = "")
  public Integer getRfidTagId() {
    return rfidTagId;
  }

  public void setRfidTagId(Integer rfidTagId) {
    this.rfidTagId = rfidTagId;
  }

  public Item rfidTag(RfidTag rfidTag) {
    this.rfidTag = rfidTag;
    return this;
  }

   /**
   * Get rfidTag
   * @return rfidTag
  **/
  @Schema(description = "")
  public RfidTag getRfidTag() {
    return rfidTag;
  }

  public void setRfidTag(RfidTag rfidTag) {
    this.rfidTag = rfidTag;
  }

  public Item taggedDate(Date taggedDate) {
    this.taggedDate = taggedDate;
    return this;
  }

   /**
   * Get taggedDate
   * @return taggedDate
  **/
  @Schema(description = "")
  public Date getTaggedDate() {
    return taggedDate;
  }

  public void setTaggedDate(Date taggedDate) {
    this.taggedDate = taggedDate;
  }

  public Item name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Item code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Item categoryOfItemId(Integer categoryOfItemId) {
    this.categoryOfItemId = categoryOfItemId;
    return this;
  }

   /**
   * Get categoryOfItemId
   * @return categoryOfItemId
  **/
  @Schema(description = "")
  public Integer getCategoryOfItemId() {
    return categoryOfItemId;
  }

  public void setCategoryOfItemId(Integer categoryOfItemId) {
    this.categoryOfItemId = categoryOfItemId;
  }

  public Item categoryOfItem(CategoryOfItem categoryOfItem) {
    this.categoryOfItem = categoryOfItem;
    return this;
  }

   /**
   * Get categoryOfItem
   * @return categoryOfItem
  **/
  @Schema(description = "")
  public CategoryOfItem getCategoryOfItem() {
    return categoryOfItem;
  }

  public void setCategoryOfItem(CategoryOfItem categoryOfItem) {
    this.categoryOfItem = categoryOfItem;
  }

  public Item description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Item data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(required = true, description = "")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public Item state(Integer state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @Schema(description = "")
  public Integer getState() {
    return state;
  }

  public void setState(Integer state) {
    this.state = state;
  }

  public Item isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Get isDeleted
   * @return isDeleted
  **/
  @Schema(description = "")
  public Boolean isIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public Item extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

//  public Item itemRelations(List<ItemRelation> itemRelations) {
//    this.itemRelations = itemRelations;
//    return this;
//  }
//
//  public Item addItemRelationsItem(ItemRelation itemRelationsItem) {
//    if (this.itemRelations == null) {
//      this.itemRelations = new ArrayList<ItemRelation>();
//    }
//    this.itemRelations.add(itemRelationsItem);
//    return this;
//  }
//
//   /**
//   * Get itemRelations
//   * @return itemRelations
//  **/
//  @Schema(description = "")
//  public List<ItemRelation> getItemRelations() {
//    return itemRelations;
//  }
//
//  public void setItemRelations(List<ItemRelation> itemRelations) {
//    this.itemRelations = itemRelations;
//  }
//
//  public Item itemRelations1(List<ItemRelation> itemRelations1) {
//    this.itemRelations1 = itemRelations1;
//    return this;
//  }
//
//  public Item addItemRelations1Item(ItemRelation itemRelations1Item) {
//    if (this.itemRelations1 == null) {
//      this.itemRelations1 = new ArrayList<ItemRelation>();
//    }
//    this.itemRelations1.add(itemRelations1Item);
//    return this;
//  }
//
//   /**
//   * Get itemRelations1
//   * @return itemRelations1
//  **/
//  @Schema(description = "")
//  public List<ItemRelation> getItemRelations1() {
//    return itemRelations1;
//  }
//
//  public void setItemRelations1(List<ItemRelation> itemRelations1) {
//    this.itemRelations1 = itemRelations1;
//  }
//
//  public Item itemMedia(List<ItemMedia> itemMedia) {
//    this.itemMedia = itemMedia;
//    return this;
//  }
//
//  public Item addItemMediaItem(ItemMedia itemMediaItem) {
//    if (this.itemMedia == null) {
//      this.itemMedia = new ArrayList<ItemMedia>();
//    }
//    this.itemMedia.add(itemMediaItem);
//    return this;
//  }

   /**
   * Get itemMedia
   * @return itemMedia
  **/
  @Schema(description = "")
  public List<ItemMedia> getItemMedia() {
    return itemMedia;
  }

  public void setItemMedia(List<ItemMedia> itemMedia) {
    this.itemMedia = itemMedia;
  }

  public Item itemUoms(List<ItemUom> itemUoms) {
    this.itemUoms = itemUoms;
    return this;
  }

  public Item addItemUomsItem(ItemUom itemUomsItem) {
    if (this.itemUoms == null) {
      this.itemUoms = new ArrayList<ItemUom>();
    }
    this.itemUoms.add(itemUomsItem);
    return this;
  }

   /**
   * Get itemUoms
   * @return itemUoms
  **/
  @Schema(description = "")
  public List<ItemUom> getItemUoms() {
    return itemUoms;
  }

  public void setItemUoms(List<ItemUom> itemUoms) {
    this.itemUoms = itemUoms;
  }

  public Item batches(List<Batch> batches) {
    this.batches = batches;
    return this;
  }

  public Item addBatchesItem(Batch batchesItem) {
    if (this.batches == null) {
      this.batches = new ArrayList<Batch>();
    }
    this.batches.add(batchesItem);
    return this;
  }

   /**
   * Get batches
   * @return batches
  **/
  @Schema(description = "")
  public List<Batch> getBatches() {
    return batches;
  }

  public void setBatches(List<Batch> batches) {
    this.batches = batches;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Item item = (Item) o;
    return Objects.equals(this.id, item.id) &&
        Objects.equals(this.rfidTagId, item.rfidTagId) &&
        Objects.equals(this.rfidTag, item.rfidTag) &&
        Objects.equals(this.taggedDate, item.taggedDate) &&
        Objects.equals(this.name, item.name) &&
        Objects.equals(this.code, item.code) &&
        Objects.equals(this.categoryOfItemId, item.categoryOfItemId) &&
        Objects.equals(this.categoryOfItem, item.categoryOfItem) &&
        Objects.equals(this.description, item.description) &&
        Objects.equals(this.data, item.data) &&
        Objects.equals(this.state, item.state) &&
        Objects.equals(this.isDeleted, item.isDeleted) &&
        Objects.equals(this.extInfo, item.extInfo) &&
        //Objects.equals(this.itemRelations, item.itemRelations) &&
        //Objects.equals(this.itemRelations1, item.itemRelations1) &&
        Objects.equals(this.itemMedia, item.itemMedia) &&
        Objects.equals(this.itemUoms, item.itemUoms) &&
        Objects.equals(this.batches, item.batches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rfidTagId, rfidTag, taggedDate, name, code, categoryOfItemId, categoryOfItem, description, data, state, isDeleted, extInfo,  itemMedia, itemUoms, batches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Item {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rfidTagId: ").append(toIndentedString(rfidTagId)).append("\n");
    sb.append("    rfidTag: ").append(toIndentedString(rfidTag)).append("\n");
    sb.append("    taggedDate: ").append(toIndentedString(taggedDate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    categoryOfItemId: ").append(toIndentedString(categoryOfItemId)).append("\n");
    sb.append("    categoryOfItem: ").append(toIndentedString(categoryOfItem)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    //sb.append("    itemRelations: ").append(toIndentedString(itemRelations)).append("\n");
    //sb.append("    itemRelations1: ").append(toIndentedString(itemRelations1)).append("\n");
    sb.append("    itemMedia: ").append(toIndentedString(itemMedia)).append("\n");
    sb.append("    itemUoms: ").append(toIndentedString(itemUoms)).append("\n");
    sb.append("    batches: ").append(toIndentedString(batches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
