/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Transient;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ItemUom
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

@Entity
public class ItemUom {
  @Id
  @SerializedName("id")
  private long id = 0;

  @SerializedName("itemId")
  private Integer itemId = null;

  @Transient
  @SerializedName("item")
  private Item item = null;

  @SerializedName("uomId")
  private Integer uomId = null;

  @Transient
  @SerializedName("uom")
  private Uom uom = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("unitPrice")
  private Double unitPrice = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @Transient
  @SerializedName("inventories")
  private List<Inventory> inventories = null;

  @SerializedName("transactionDetails")
  private List<TransactionDetail> transactionDetails = null;

  public ItemUom id(long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public ItemUom itemId(Integer itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * Get itemId
   * @return itemId
  **/
  @Schema(required = true, description = "")
  public Integer getItemId() {
    return itemId;
  }

  public void setItemId(Integer itemId) {
    this.itemId = itemId;
  }

  public ItemUom item(Item item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @Schema(description = "")
  public Item getItem() {
    return item;
  }

  public void setItem(Item item) {
    this.item = item;
  }

  public ItemUom uomId(Integer uomId) {
    this.uomId = uomId;
    return this;
  }

   /**
   * Get uomId
   * @return uomId
  **/
  @Schema(required = true, description = "")
  public Integer getUomId() {
    return uomId;
  }

  public void setUomId(Integer uomId) {
    this.uomId = uomId;
  }

  public ItemUom uom(Uom uom) {
    this.uom = uom;
    return this;
  }

   /**
   * Get uom
   * @return uom
  **/
  @Schema(description = "")
  public Uom getUom() {
    return uom;
  }

  public void setUom(Uom uom) {
    this.uom = uom;
  }

  public ItemUom code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ItemUom description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ItemUom unitPrice(Double unitPrice) {
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  @Schema(description = "")
  public Double getUnitPrice() {
    return unitPrice;
  }

  public void setUnitPrice(Double unitPrice) {
    this.unitPrice = unitPrice;
  }

  public ItemUom extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public ItemUom inventories(List<Inventory> inventories) {
    this.inventories = inventories;
    return this;
  }

  public ItemUom addInventoriesItem(Inventory inventoriesItem) {
    if (this.inventories == null) {
      this.inventories = new ArrayList<Inventory>();
    }
    this.inventories.add(inventoriesItem);
    return this;
  }

   /**
   * Get inventories
   * @return inventories
  **/
  @Schema(description = "")
  public List<Inventory> getInventories() {
    return inventories;
  }

  public void setInventories(List<Inventory> inventories) {
    this.inventories = inventories;
  }

  public ItemUom transactionDetails(List<TransactionDetail> transactionDetails) {
    this.transactionDetails = transactionDetails;
    return this;
  }

  public ItemUom addTransactionDetailsItem(TransactionDetail transactionDetailsItem) {
    if (this.transactionDetails == null) {
      this.transactionDetails = new ArrayList<TransactionDetail>();
    }
    this.transactionDetails.add(transactionDetailsItem);
    return this;
  }

   /**
   * Get transactionDetails
   * @return transactionDetails
  **/
  @Schema(description = "")
  public List<TransactionDetail> getTransactionDetails() {
    return transactionDetails;
  }

  public void setTransactionDetails(List<TransactionDetail> transactionDetails) {
    this.transactionDetails = transactionDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemUom itemUom = (ItemUom) o;
    return Objects.equals(this.id, itemUom.id) &&
        Objects.equals(this.itemId, itemUom.itemId) &&
        Objects.equals(this.item, itemUom.item) &&
        Objects.equals(this.uomId, itemUom.uomId) &&
        Objects.equals(this.uom, itemUom.uom) &&
        Objects.equals(this.code, itemUom.code) &&
        Objects.equals(this.description, itemUom.description) &&
        Objects.equals(this.unitPrice, itemUom.unitPrice) &&
        Objects.equals(this.extInfo, itemUom.extInfo) &&
        Objects.equals(this.inventories, itemUom.inventories) &&
        Objects.equals(this.transactionDetails, itemUom.transactionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, itemId, item, uomId, uom, code, description, unitPrice, extInfo, inventories, transactionDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemUom {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    uomId: ").append(toIndentedString(uomId)).append("\n");
    sb.append("    uom: ").append(toIndentedString(uom)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    inventories: ").append(toIndentedString(inventories)).append("\n");
    sb.append("    transactionDetails: ").append(toIndentedString(transactionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public String getItemName() {
      if(item == null) return "";
      return item.getName();
    }

  public String getUomName() {
    if(uom == null) return "";
    return uom.getName();
  }

  public String getSerial() {
    return serial;
  }
  public void setSerial(String serial) {
    this.serial = serial;
  }
  private String serial;
}
