/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Transient;
import io.swagger.v3.oas.annotations.media.Schema;

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")
@Entity
public class Location {
  @Id
  //@SerializedName("id")
  private long id = 0;

  //@SerializedName("parentId")
  private long parentId = 0;

  //@SerializedName("locationTypeId")
  private Integer locationTypeId = null;

  //@SerializedName("name")
  private String name = null;

  //@SerializedName("code")
  private String code = null;

  //@SerializedName("barCode")
  private String barCode = null;

  //@SerializedName("rfidCode")
  private String rfidCode = null;

  //@SerializedName("description")
  private String description = null;

  //@SerializedName("isContainer")
  private boolean isContainer;

  //@SerializedName("coordinates")
  private String coordinates = null;

  //@SerializedName("width")
  private Integer width = null;

  //@SerializedName("length")
  private Integer length = null;

  //@SerializedName("height")
  private Integer height = null;

  //@SerializedName("radious")
  private Integer radious = null;

  //@SerializedName("image")
  private String image = null;

  //@SerializedName("backgroundImage")
  private String backgroundImage = null;

  //@SerializedName("itemUomId")
  private Integer itemUomId = null;

  @Transient
  //@SerializedName("itemUom")
  private ItemUom itemUom = null;

  //@SerializedName("capacity")
  private Double capacity = null;

  //@SerializedName("extInfo")
  private String extInfo = null;

  @Transient
  //@SerializedName("monitorPoints")
  private List<MonitorPoint> monitorPoints = null;

  public Location id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Location parentId(long parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @Schema(description = "")
  public long getParentId() {
    return parentId;
  }

  public void setParentId(long parentId) {
    this.parentId = parentId;
  }

  public Location locationTypeId(Integer locationTypeId) {
    this.locationTypeId = locationTypeId;
    return this;
  }

   /**
   * Get locationTypeId
   * @return locationTypeId
  **/
  @Schema(required = true, description = "")
  public Integer getLocationTypeId() {
    return locationTypeId;
  }

  public void setLocationTypeId(Integer locationTypeId) {
    this.locationTypeId = locationTypeId;
  }

  public Location name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Location code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Location barCode(String barCode) {
    this.barCode = barCode;
    return this;
  }

   /**
   * Get barCode
   * @return barCode
  **/
  @Schema(description = "")
  public String getBarCode() {
    return barCode;
  }

  public void setBarCode(String barCode) {
    this.barCode = barCode;
  }

  public Location rfidCode(String rfidCode) {
    this.rfidCode = rfidCode;
    return this;
  }

   /**
   * Get rfidCode
   * @return rfidCode
  **/
  @Schema(description = "")
  public String getRfidCode() {
    return rfidCode;
  }

  public void setRfidCode(String rfidCode) {
    this.rfidCode = rfidCode;
  }

  public Location description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Location coordinates(String coordinates) {
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @Schema(description = "")
  public String getCoordinates() {
    return coordinates;
  }

  public void setCoordinates(String coordinates) {
    this.coordinates = coordinates;
  }

  public Location width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @Schema(description = "")
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public Location length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @Schema(description = "")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public Location height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @Schema(description = "")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public Location radious(Integer radious) {
    this.radious = radious;
    return this;
  }

   /**
   * Get radious
   * @return radious
  **/
  @Schema(description = "")
  public Integer getRadious() {
    return radious;
  }

  public void setRadious(Integer radious) {
    this.radious = radious;
  }

  public Location image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(description = "")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public Location backgroundImage(String backgroundImage) {
    this.backgroundImage = backgroundImage;
    return this;
  }

   /**
   * Get backgroundImage
   * @return backgroundImage
  **/
  @Schema(description = "")
  public String getBackgroundImage() {
    return backgroundImage;
  }

  public void setBackgroundImage(String backgroundImage) {
    this.backgroundImage = backgroundImage;
  }

  public Location itemUomId(Integer itemUomId) {
    this.itemUomId = itemUomId;
    return this;
  }

   /**
   * Get itemUomId
   * @return itemUomId
  **/
  @Schema(description = "")
  public Integer getItemUomId() {
    return itemUomId;
  }

  public void setItemUomId(Integer itemUomId) {
    this.itemUomId = itemUomId;
  }

  public Location itemUom(ItemUom itemUom) {
    this.itemUom = itemUom;
    return this;
  }

   /**
   * Get itemUom
   * @return itemUom
  **/
  @Schema(description = "")
  public ItemUom getItemUom() {
    return itemUom;
  }

  public void setItemUom(ItemUom itemUom) {
    this.itemUom = itemUom;
  }

  public Location capacity(Double capacity) {
    this.capacity = capacity;
    return this;
  }

   /**
   * Get capacity
   * @return capacity
  **/
  @Schema(description = "")
  public Double getCapacity() {
    return capacity;
  }

  public void setCapacity(Double capacity) {
    this.capacity = capacity;
  }

  public Location extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public Location monitorPoints(List<MonitorPoint> monitorPoints) {
    this.monitorPoints = monitorPoints;
    return this;
  }

  public Location addMonitorPointsItem(MonitorPoint monitorPointsItem) {
    if (this.monitorPoints == null) {
      this.monitorPoints = new ArrayList<MonitorPoint>();
    }
    this.monitorPoints.add(monitorPointsItem);
    return this;
  }

   /**
   * Get monitorPoints
   * @return monitorPoints
  **/
  @Schema(description = "")
  public List<MonitorPoint> getMonitorPoints() {
    return monitorPoints;
  }

  public void setMonitorPoints(List<MonitorPoint> monitorPoints) {
    this.monitorPoints = monitorPoints;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Location location = (Location) o;
    return Objects.equals(this.id, location.id) &&
        Objects.equals(this.parentId, location.parentId) &&
        Objects.equals(this.locationTypeId, location.locationTypeId) &&
        Objects.equals(this.name, location.name) &&
        Objects.equals(this.code, location.code) &&
        Objects.equals(this.barCode, location.barCode) &&
        Objects.equals(this.rfidCode, location.rfidCode) &&
        Objects.equals(this.description, location.description) &&
        Objects.equals(this.coordinates, location.coordinates) &&
        Objects.equals(this.width, location.width) &&
        Objects.equals(this.length, location.length) &&
        Objects.equals(this.height, location.height) &&
        Objects.equals(this.radious, location.radious) &&
        Objects.equals(this.image, location.image) &&
        Objects.equals(this.backgroundImage, location.backgroundImage) &&
        Objects.equals(this.itemUomId, location.itemUomId) &&
        Objects.equals(this.itemUom, location.itemUom) &&
        Objects.equals(this.capacity, location.capacity) &&
        Objects.equals(this.extInfo, location.extInfo) &&
        Objects.equals(this.monitorPoints, location.monitorPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parentId, locationTypeId, name, code, barCode, rfidCode, description, coordinates, width, length, height, radious, image, backgroundImage, itemUomId, itemUom, capacity, extInfo, monitorPoints);
  }


  @Override
  public String toString() {
    return code + "/" +  name;
//    StringBuilder sb = new StringBuilder();
//    sb.append("class Location {\n");
//
//    sb.append("    id: ").append(toIndentedString(id)).append("\n");
//    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
//    sb.append("    locationTypeId: ").append(toIndentedString(locationTypeId)).append("\n");
//    sb.append("    name: ").append(toIndentedString(name)).append("\n");
//    sb.append("    code: ").append(toIndentedString(code)).append("\n");
//    sb.append("    barCode: ").append(toIndentedString(barCode)).append("\n");
//    sb.append("    rfidCode: ").append(toIndentedString(rfidCode)).append("\n");
//    sb.append("    description: ").append(toIndentedString(description)).append("\n");
//    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
//    sb.append("    width: ").append(toIndentedString(width)).append("\n");
//    sb.append("    length: ").append(toIndentedString(length)).append("\n");
//    sb.append("    height: ").append(toIndentedString(height)).append("\n");
//    sb.append("    radious: ").append(toIndentedString(radious)).append("\n");
//    sb.append("    image: ").append(toIndentedString(image)).append("\n");
//    sb.append("    backgroundImage: ").append(toIndentedString(backgroundImage)).append("\n");
//    sb.append("    itemUomId: ").append(toIndentedString(itemUomId)).append("\n");
//    sb.append("    itemUom: ").append(toIndentedString(itemUom)).append("\n");
//    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
//    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
//    sb.append("    monitorPoints: ").append(toIndentedString(monitorPoints)).append("\n");
//    sb.append("}");
//    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public boolean isContainer() {
      LocationType type = Arrays.stream(LocationType.values()).filter(v -> v.getValue() == locationTypeId)
              .findFirst().get();
        return type.getIsContainer();
    }
}
