/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Transient;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Lot
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")
@Entity
public class Lot {
  @Id
  private long id = 0;
  @SerializedName("lotNo")
  private String lotNo = null;

  @SerializedName("itemId")
  private Integer itemId = null;

  @Transient
  @SerializedName("item")
  private Item item = null;

  @SerializedName("expiryDate")
  private Date expiryDate = null;

  @SerializedName("manufactureDate")
  private Date manufactureDate = null;

  @SerializedName("qcStatus")
  private String qcStatus = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("batches")
  private List<Batch> batches = null;

  public Lot lotNo(String lotNo) {
    this.lotNo = lotNo;
    return this;
  }

   /**
   * Get lotNo
   * @return lotNo
  **/
  @Schema(required = true, description = "")
  public String getLotNo() {
    return lotNo;
  }

  public void setLotNo(String lotNo) {
    this.lotNo = lotNo;
  }

  public Lot itemId(Integer itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * Get itemId
   * @return itemId
  **/
  @Schema(required = true, description = "")
  public Integer getItemId() {
    return itemId;
  }

  public void setItemId(Integer itemId) {
    this.itemId = itemId;
  }

  public Lot item(Item item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @Schema(description = "")
  public Item getItem() {
    return item;
  }

  public void setItem(Item item) {
    this.item = item;
  }

  public Lot expiryDate(Date expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @Schema(required = true, description = "")
  public Date getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(Date expiryDate) {
    this.expiryDate = expiryDate;
  }

  public Lot manufactureDate(Date manufactureDate) {
    this.manufactureDate = manufactureDate;
    return this;
  }

   /**
   * Get manufactureDate
   * @return manufactureDate
  **/
  @Schema(required = true, description = "")
  public Date getManufactureDate() {
    return manufactureDate;
  }

  public void setManufactureDate(Date manufactureDate) {
    this.manufactureDate = manufactureDate;
  }

  public Lot qcStatus(String qcStatus) {
    this.qcStatus = qcStatus;
    return this;
  }

   /**
   * Get qcStatus
   * @return qcStatus
  **/
  @Schema(required = true, description = "")
  public String getQcStatus() {
    return qcStatus;
  }

  public void setQcStatus(String qcStatus) {
    this.qcStatus = qcStatus;
  }

  public Lot note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @Schema(description = "")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public Lot extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public Lot batches(List<Batch> batches) {
    this.batches = batches;
    return this;
  }

  public Lot addBatchesItem(Batch batchesItem) {
    if (this.batches == null) {
      this.batches = new ArrayList<Batch>();
    }
    this.batches.add(batchesItem);
    return this;
  }

   /**
   * Get batches
   * @return batches
  **/
  @Schema(description = "")
  public List<Batch> getBatches() {
    return batches;
  }

  public void setBatches(List<Batch> batches) {
    this.batches = batches;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Lot lot = (Lot) o;
    return Objects.equals(this.lotNo, lot.lotNo) &&
        Objects.equals(this.itemId, lot.itemId) &&
        Objects.equals(this.item, lot.item) &&
        Objects.equals(this.expiryDate, lot.expiryDate) &&
        Objects.equals(this.manufactureDate, lot.manufactureDate) &&
        Objects.equals(this.qcStatus, lot.qcStatus) &&
        Objects.equals(this.note, lot.note) &&
        Objects.equals(this.extInfo, lot.extInfo) &&
        Objects.equals(this.batches, lot.batches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lotNo, itemId, item, expiryDate, manufactureDate, qcStatus, note, extInfo, batches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Lot {\n");
    
    sb.append("    lotNo: ").append(toIndentedString(lotNo)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    manufactureDate: ").append(toIndentedString(manufactureDate)).append("\n");
    sb.append("    qcStatus: ").append(toIndentedString(qcStatus)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    batches: ").append(toIndentedString(batches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
