/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Manufacturer
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class Manufacturer {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("contactInfo")
  private String contactInfo = null;

  @SerializedName("countryCode")
  private String countryCode = null;

  @SerializedName("countryName")
  private String countryName = null;

  @SerializedName("region")
  private String region = null;

  @SerializedName("logo")
  private String logo = null;

  @SerializedName("specializations")
  private Integer specializations = null;

  @SerializedName("specs")
  private List<Specializations> specs = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("rfidTags")
  private List<RfidTag> rfidTags = null;

  @SerializedName("supportedReaderModels")
  private List<SupportedReaderModel> supportedReaderModels = null;

  public Manufacturer id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Manufacturer name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Manufacturer description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Manufacturer contactInfo(String contactInfo) {
    this.contactInfo = contactInfo;
    return this;
  }

   /**
   * Get contactInfo
   * @return contactInfo
  **/
  @Schema(description = "")
  public String getContactInfo() {
    return contactInfo;
  }

  public void setContactInfo(String contactInfo) {
    this.contactInfo = contactInfo;
  }

  public Manufacturer countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @Schema(description = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public Manufacturer countryName(String countryName) {
    this.countryName = countryName;
    return this;
  }

   /**
   * Get countryName
   * @return countryName
  **/
  @Schema(description = "")
  public String getCountryName() {
    return countryName;
  }

  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }

  public Manufacturer region(String region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @Schema(description = "")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public Manufacturer logo(String logo) {
    this.logo = logo;
    return this;
  }

   /**
   * Get logo
   * @return logo
  **/
  @Schema(description = "")
  public String getLogo() {
    return logo;
  }

  public void setLogo(String logo) {
    this.logo = logo;
  }

  public Manufacturer specializations(Integer specializations) {
    this.specializations = specializations;
    return this;
  }

   /**
   * Get specializations
   * @return specializations
  **/
  @Schema(description = "")
  public Integer getSpecializations() {
    return specializations;
  }

  public void setSpecializations(Integer specializations) {
    this.specializations = specializations;
  }

  public Manufacturer specs(List<Specializations> specs) {
    this.specs = specs;
    return this;
  }

  public Manufacturer addSpecsItem(Specializations specsItem) {
    if (this.specs == null) {
      this.specs = new ArrayList<Specializations>();
    }
    this.specs.add(specsItem);
    return this;
  }

   /**
   * Get specs
   * @return specs
  **/
  @Schema(description = "")
  public List<Specializations> getSpecs() {
    return specs;
  }

  public void setSpecs(List<Specializations> specs) {
    this.specs = specs;
  }

  public Manufacturer extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public Manufacturer rfidTags(List<RfidTag> rfidTags) {
    this.rfidTags = rfidTags;
    return this;
  }

  public Manufacturer addRfidTagsItem(RfidTag rfidTagsItem) {
    if (this.rfidTags == null) {
      this.rfidTags = new ArrayList<RfidTag>();
    }
    this.rfidTags.add(rfidTagsItem);
    return this;
  }

   /**
   * Get rfidTags
   * @return rfidTags
  **/
  @Schema(description = "")
  public List<RfidTag> getRfidTags() {
    return rfidTags;
  }

  public void setRfidTags(List<RfidTag> rfidTags) {
    this.rfidTags = rfidTags;
  }

  public Manufacturer supportedReaderModels(List<SupportedReaderModel> supportedReaderModels) {
    this.supportedReaderModels = supportedReaderModels;
    return this;
  }

  public Manufacturer addSupportedReaderModelsItem(SupportedReaderModel supportedReaderModelsItem) {
    if (this.supportedReaderModels == null) {
      this.supportedReaderModels = new ArrayList<SupportedReaderModel>();
    }
    this.supportedReaderModels.add(supportedReaderModelsItem);
    return this;
  }

   /**
   * Get supportedReaderModels
   * @return supportedReaderModels
  **/
  @Schema(description = "")
  public List<SupportedReaderModel> getSupportedReaderModels() {
    return supportedReaderModels;
  }

  public void setSupportedReaderModels(List<SupportedReaderModel> supportedReaderModels) {
    this.supportedReaderModels = supportedReaderModels;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Manufacturer manufacturer = (Manufacturer) o;
    return Objects.equals(this.id, manufacturer.id) &&
        Objects.equals(this.name, manufacturer.name) &&
        Objects.equals(this.description, manufacturer.description) &&
        Objects.equals(this.contactInfo, manufacturer.contactInfo) &&
        Objects.equals(this.countryCode, manufacturer.countryCode) &&
        Objects.equals(this.countryName, manufacturer.countryName) &&
        Objects.equals(this.region, manufacturer.region) &&
        Objects.equals(this.logo, manufacturer.logo) &&
        Objects.equals(this.specializations, manufacturer.specializations) &&
        Objects.equals(this.specs, manufacturer.specs) &&
        Objects.equals(this.extInfo, manufacturer.extInfo) &&
        Objects.equals(this.rfidTags, manufacturer.rfidTags) &&
        Objects.equals(this.supportedReaderModels, manufacturer.supportedReaderModels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, contactInfo, countryCode, countryName, region, logo, specializations, specs, extInfo, rfidTags, supportedReaderModels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Manufacturer {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    contactInfo: ").append(toIndentedString(contactInfo)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    specializations: ").append(toIndentedString(specializations)).append("\n");
    sb.append("    specs: ").append(toIndentedString(specs)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    rfidTags: ").append(toIndentedString(rfidTags)).append("\n");
    sb.append("    supportedReaderModels: ").append(toIndentedString(supportedReaderModels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
