/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * MonitorPoint
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class MonitorPoint {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("monitorTypeId")
  private Integer monitorTypeId = null;

  @SerializedName("monitorType")
  private MonitorType monitorType = null;

  @SerializedName("locationId")
  private Integer locationId = null;

  @SerializedName("location")
  private Location location = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("readers")
  private List<Reader> readers = null;

  public MonitorPoint id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MonitorPoint name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MonitorPoint description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public MonitorPoint monitorTypeId(Integer monitorTypeId) {
    this.monitorTypeId = monitorTypeId;
    return this;
  }

   /**
   * Get monitorTypeId
   * @return monitorTypeId
  **/
  @Schema(description = "")
  public Integer getMonitorTypeId() {
    return monitorTypeId;
  }

  public void setMonitorTypeId(Integer monitorTypeId) {
    this.monitorTypeId = monitorTypeId;
  }

  public MonitorPoint monitorType(MonitorType monitorType) {
    this.monitorType = monitorType;
    return this;
  }

   /**
   * Get monitorType
   * @return monitorType
  **/
  @Schema(description = "")
  public MonitorType getMonitorType() {
    return monitorType;
  }

  public void setMonitorType(MonitorType monitorType) {
    this.monitorType = monitorType;
  }

  public MonitorPoint locationId(Integer locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @Schema(required = true, description = "")
  public Integer getLocationId() {
    return locationId;
  }

  public void setLocationId(Integer locationId) {
    this.locationId = locationId;
  }

  public MonitorPoint location(Location location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @Schema(description = "")
  public Location getLocation() {
    return location;
  }

  public void setLocation(Location location) {
    this.location = location;
  }

  public MonitorPoint extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public MonitorPoint readers(List<Reader> readers) {
    this.readers = readers;
    return this;
  }

  public MonitorPoint addReadersItem(Reader readersItem) {
    if (this.readers == null) {
      this.readers = new ArrayList<Reader>();
    }
    this.readers.add(readersItem);
    return this;
  }

   /**
   * Get readers
   * @return readers
  **/
  @Schema(description = "")
  public List<Reader> getReaders() {
    return readers;
  }

  public void setReaders(List<Reader> readers) {
    this.readers = readers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonitorPoint monitorPoint = (MonitorPoint) o;
    return Objects.equals(this.id, monitorPoint.id) &&
        Objects.equals(this.name, monitorPoint.name) &&
        Objects.equals(this.description, monitorPoint.description) &&
        Objects.equals(this.monitorTypeId, monitorPoint.monitorTypeId) &&
        Objects.equals(this.monitorType, monitorPoint.monitorType) &&
        Objects.equals(this.locationId, monitorPoint.locationId) &&
        Objects.equals(this.location, monitorPoint.location) &&
        Objects.equals(this.extInfo, monitorPoint.extInfo) &&
        Objects.equals(this.readers, monitorPoint.readers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, monitorTypeId, monitorType, locationId, location, extInfo, readers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonitorPoint {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    monitorTypeId: ").append(toIndentedString(monitorTypeId)).append("\n");
    sb.append("    monitorType: ").append(toIndentedString(monitorType)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    readers: ").append(toIndentedString(readers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
