/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * MonitorType
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class MonitorType {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("monitorPoints")
  private List<MonitorPoint> monitorPoints = null;

  public MonitorType id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MonitorType name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MonitorType description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public MonitorType extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public MonitorType monitorPoints(List<MonitorPoint> monitorPoints) {
    this.monitorPoints = monitorPoints;
    return this;
  }

  public MonitorType addMonitorPointsItem(MonitorPoint monitorPointsItem) {
    if (this.monitorPoints == null) {
      this.monitorPoints = new ArrayList<MonitorPoint>();
    }
    this.monitorPoints.add(monitorPointsItem);
    return this;
  }

   /**
   * Get monitorPoints
   * @return monitorPoints
  **/
  @Schema(description = "")
  public List<MonitorPoint> getMonitorPoints() {
    return monitorPoints;
  }

  public void setMonitorPoints(List<MonitorPoint> monitorPoints) {
    this.monitorPoints = monitorPoints;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonitorType monitorType = (MonitorType) o;
    return Objects.equals(this.id, monitorType.id) &&
        Objects.equals(this.name, monitorType.name) &&
        Objects.equals(this.description, monitorType.description) &&
        Objects.equals(this.extInfo, monitorType.extInfo) &&
        Objects.equals(this.monitorPoints, monitorType.monitorPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, extInfo, monitorPoints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonitorType {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    monitorPoints: ").append(toIndentedString(monitorPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
