/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * MyAntennaConfigGroup
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class MyAntennaConfigGroup {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("readerProfileId")
  private Integer readerProfileId = null;

  @SerializedName("txPowerInDbm")
  private Double txPowerInDbm = null;

  @SerializedName("rxSensitivityInDbm")
  private Double rxSensitivityInDbm = null;

  @SerializedName("txPowerMax")
  private Boolean txPowerMax = null;

  @SerializedName("rxSensitivityMax")
  private Boolean rxSensitivityMax = null;

  @SerializedName("myAntennaConfigs")
  private List<MyAntennaConfig> myAntennaConfigs = null;

  @SerializedName("readerProfiles")
  private List<ReaderProfile> readerProfiles = null;

  public MyAntennaConfigGroup id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MyAntennaConfigGroup name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MyAntennaConfigGroup description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public MyAntennaConfigGroup readerProfileId(Integer readerProfileId) {
    this.readerProfileId = readerProfileId;
    return this;
  }

   /**
   * Get readerProfileId
   * @return readerProfileId
  **/
  @Schema(required = true, description = "")
  public Integer getReaderProfileId() {
    return readerProfileId;
  }

  public void setReaderProfileId(Integer readerProfileId) {
    this.readerProfileId = readerProfileId;
  }

  public MyAntennaConfigGroup txPowerInDbm(Double txPowerInDbm) {
    this.txPowerInDbm = txPowerInDbm;
    return this;
  }

   /**
   * Get txPowerInDbm
   * @return txPowerInDbm
  **/
  @Schema(required = true, description = "")
  public Double getTxPowerInDbm() {
    return txPowerInDbm;
  }

  public void setTxPowerInDbm(Double txPowerInDbm) {
    this.txPowerInDbm = txPowerInDbm;
  }

  public MyAntennaConfigGroup rxSensitivityInDbm(Double rxSensitivityInDbm) {
    this.rxSensitivityInDbm = rxSensitivityInDbm;
    return this;
  }

   /**
   * Get rxSensitivityInDbm
   * @return rxSensitivityInDbm
  **/
  @Schema(required = true, description = "")
  public Double getRxSensitivityInDbm() {
    return rxSensitivityInDbm;
  }

  public void setRxSensitivityInDbm(Double rxSensitivityInDbm) {
    this.rxSensitivityInDbm = rxSensitivityInDbm;
  }

  public MyAntennaConfigGroup txPowerMax(Boolean txPowerMax) {
    this.txPowerMax = txPowerMax;
    return this;
  }

   /**
   * Get txPowerMax
   * @return txPowerMax
  **/
  @Schema(description = "")
  public Boolean isTxPowerMax() {
    return txPowerMax;
  }

  public void setTxPowerMax(Boolean txPowerMax) {
    this.txPowerMax = txPowerMax;
  }

  public MyAntennaConfigGroup rxSensitivityMax(Boolean rxSensitivityMax) {
    this.rxSensitivityMax = rxSensitivityMax;
    return this;
  }

   /**
   * Get rxSensitivityMax
   * @return rxSensitivityMax
  **/
  @Schema(description = "")
  public Boolean isRxSensitivityMax() {
    return rxSensitivityMax;
  }

  public void setRxSensitivityMax(Boolean rxSensitivityMax) {
    this.rxSensitivityMax = rxSensitivityMax;
  }

  public MyAntennaConfigGroup myAntennaConfigs(List<MyAntennaConfig> myAntennaConfigs) {
    this.myAntennaConfigs = myAntennaConfigs;
    return this;
  }

  public MyAntennaConfigGroup addMyAntennaConfigsItem(MyAntennaConfig myAntennaConfigsItem) {
    if (this.myAntennaConfigs == null) {
      this.myAntennaConfigs = new ArrayList<MyAntennaConfig>();
    }
    this.myAntennaConfigs.add(myAntennaConfigsItem);
    return this;
  }

   /**
   * Get myAntennaConfigs
   * @return myAntennaConfigs
  **/
  @Schema(description = "")
  public List<MyAntennaConfig> getMyAntennaConfigs() {
    return myAntennaConfigs;
  }

  public void setMyAntennaConfigs(List<MyAntennaConfig> myAntennaConfigs) {
    this.myAntennaConfigs = myAntennaConfigs;
  }

  public MyAntennaConfigGroup readerProfiles(List<ReaderProfile> readerProfiles) {
    this.readerProfiles = readerProfiles;
    return this;
  }

  public MyAntennaConfigGroup addReaderProfilesItem(ReaderProfile readerProfilesItem) {
    if (this.readerProfiles == null) {
      this.readerProfiles = new ArrayList<ReaderProfile>();
    }
    this.readerProfiles.add(readerProfilesItem);
    return this;
  }

   /**
   * Get readerProfiles
   * @return readerProfiles
  **/
  @Schema(description = "")
  public List<ReaderProfile> getReaderProfiles() {
    return readerProfiles;
  }

  public void setReaderProfiles(List<ReaderProfile> readerProfiles) {
    this.readerProfiles = readerProfiles;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MyAntennaConfigGroup myAntennaConfigGroup = (MyAntennaConfigGroup) o;
    return Objects.equals(this.id, myAntennaConfigGroup.id) &&
        Objects.equals(this.name, myAntennaConfigGroup.name) &&
        Objects.equals(this.description, myAntennaConfigGroup.description) &&
        Objects.equals(this.readerProfileId, myAntennaConfigGroup.readerProfileId) &&
        Objects.equals(this.txPowerInDbm, myAntennaConfigGroup.txPowerInDbm) &&
        Objects.equals(this.rxSensitivityInDbm, myAntennaConfigGroup.rxSensitivityInDbm) &&
        Objects.equals(this.txPowerMax, myAntennaConfigGroup.txPowerMax) &&
        Objects.equals(this.rxSensitivityMax, myAntennaConfigGroup.rxSensitivityMax) &&
        Objects.equals(this.myAntennaConfigs, myAntennaConfigGroup.myAntennaConfigs) &&
        Objects.equals(this.readerProfiles, myAntennaConfigGroup.readerProfiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, readerProfileId, txPowerInDbm, rxSensitivityInDbm, txPowerMax, rxSensitivityMax, myAntennaConfigs, readerProfiles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MyAntennaConfigGroup {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    readerProfileId: ").append(toIndentedString(readerProfileId)).append("\n");
    sb.append("    txPowerInDbm: ").append(toIndentedString(txPowerInDbm)).append("\n");
    sb.append("    rxSensitivityInDbm: ").append(toIndentedString(rxSensitivityInDbm)).append("\n");
    sb.append("    txPowerMax: ").append(toIndentedString(txPowerMax)).append("\n");
    sb.append("    rxSensitivityMax: ").append(toIndentedString(rxSensitivityMax)).append("\n");
    sb.append("    myAntennaConfigs: ").append(toIndentedString(myAntennaConfigs)).append("\n");
    sb.append("    readerProfiles: ").append(toIndentedString(readerProfiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
