/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * MyAntennaConfig
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class MyAntennaConfig {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("myAntennaConfigGroupId")
  private Integer myAntennaConfigGroupId = null;

  @SerializedName("myAntennaConfigGroup")
  private MyAntennaConfigGroup myAntennaConfigGroup = null;

  @SerializedName("isEnabled")
  private Boolean isEnabled = null;

  @SerializedName("portNumber")
  private Integer portNumber = null;

  @SerializedName("portName")
  private String portName = null;

  @SerializedName("txPowerInDbm")
  private Double txPowerInDbm = null;

  @SerializedName("rxSensitivityInDbm")
  private Double rxSensitivityInDbm = null;

  @SerializedName("maxRxSensitivity")
  private Boolean maxRxSensitivity = null;

  @SerializedName("maxTxPower")
  private Boolean maxTxPower = null;

  public MyAntennaConfig id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MyAntennaConfig myAntennaConfigGroupId(Integer myAntennaConfigGroupId) {
    this.myAntennaConfigGroupId = myAntennaConfigGroupId;
    return this;
  }

   /**
   * Get myAntennaConfigGroupId
   * @return myAntennaConfigGroupId
  **/
  @Schema(required = true, description = "")
  public Integer getMyAntennaConfigGroupId() {
    return myAntennaConfigGroupId;
  }

  public void setMyAntennaConfigGroupId(Integer myAntennaConfigGroupId) {
    this.myAntennaConfigGroupId = myAntennaConfigGroupId;
  }

  public MyAntennaConfig myAntennaConfigGroup(MyAntennaConfigGroup myAntennaConfigGroup) {
    this.myAntennaConfigGroup = myAntennaConfigGroup;
    return this;
  }

   /**
   * Get myAntennaConfigGroup
   * @return myAntennaConfigGroup
  **/
  @Schema(description = "")
  public MyAntennaConfigGroup getMyAntennaConfigGroup() {
    return myAntennaConfigGroup;
  }

  public void setMyAntennaConfigGroup(MyAntennaConfigGroup myAntennaConfigGroup) {
    this.myAntennaConfigGroup = myAntennaConfigGroup;
  }

  public MyAntennaConfig isEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

   /**
   * Get isEnabled
   * @return isEnabled
  **/
  @Schema(description = "")
  public Boolean isIsEnabled() {
    return isEnabled;
  }

  public void setIsEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }

  public MyAntennaConfig portNumber(Integer portNumber) {
    this.portNumber = portNumber;
    return this;
  }

   /**
   * Get portNumber
   * @return portNumber
  **/
  @Schema(required = true, description = "")
  public Integer getPortNumber() {
    return portNumber;
  }

  public void setPortNumber(Integer portNumber) {
    this.portNumber = portNumber;
  }

  public MyAntennaConfig portName(String portName) {
    this.portName = portName;
    return this;
  }

   /**
   * Get portName
   * @return portName
  **/
  @Schema(description = "")
  public String getPortName() {
    return portName;
  }

  public void setPortName(String portName) {
    this.portName = portName;
  }

  public MyAntennaConfig txPowerInDbm(Double txPowerInDbm) {
    this.txPowerInDbm = txPowerInDbm;
    return this;
  }

   /**
   * Get txPowerInDbm
   * @return txPowerInDbm
  **/
  @Schema(required = true, description = "")
  public Double getTxPowerInDbm() {
    return txPowerInDbm;
  }

  public void setTxPowerInDbm(Double txPowerInDbm) {
    this.txPowerInDbm = txPowerInDbm;
  }

  public MyAntennaConfig rxSensitivityInDbm(Double rxSensitivityInDbm) {
    this.rxSensitivityInDbm = rxSensitivityInDbm;
    return this;
  }

   /**
   * Get rxSensitivityInDbm
   * @return rxSensitivityInDbm
  **/
  @Schema(required = true, description = "")
  public Double getRxSensitivityInDbm() {
    return rxSensitivityInDbm;
  }

  public void setRxSensitivityInDbm(Double rxSensitivityInDbm) {
    this.rxSensitivityInDbm = rxSensitivityInDbm;
  }

  public MyAntennaConfig maxRxSensitivity(Boolean maxRxSensitivity) {
    this.maxRxSensitivity = maxRxSensitivity;
    return this;
  }

   /**
   * Get maxRxSensitivity
   * @return maxRxSensitivity
  **/
  @Schema(description = "")
  public Boolean isMaxRxSensitivity() {
    return maxRxSensitivity;
  }

  public void setMaxRxSensitivity(Boolean maxRxSensitivity) {
    this.maxRxSensitivity = maxRxSensitivity;
  }

  public MyAntennaConfig maxTxPower(Boolean maxTxPower) {
    this.maxTxPower = maxTxPower;
    return this;
  }

   /**
   * Get maxTxPower
   * @return maxTxPower
  **/
  @Schema(description = "")
  public Boolean isMaxTxPower() {
    return maxTxPower;
  }

  public void setMaxTxPower(Boolean maxTxPower) {
    this.maxTxPower = maxTxPower;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MyAntennaConfig myAntennaConfig = (MyAntennaConfig) o;
    return Objects.equals(this.id, myAntennaConfig.id) &&
        Objects.equals(this.myAntennaConfigGroupId, myAntennaConfig.myAntennaConfigGroupId) &&
        Objects.equals(this.myAntennaConfigGroup, myAntennaConfig.myAntennaConfigGroup) &&
        Objects.equals(this.isEnabled, myAntennaConfig.isEnabled) &&
        Objects.equals(this.portNumber, myAntennaConfig.portNumber) &&
        Objects.equals(this.portName, myAntennaConfig.portName) &&
        Objects.equals(this.txPowerInDbm, myAntennaConfig.txPowerInDbm) &&
        Objects.equals(this.rxSensitivityInDbm, myAntennaConfig.rxSensitivityInDbm) &&
        Objects.equals(this.maxRxSensitivity, myAntennaConfig.maxRxSensitivity) &&
        Objects.equals(this.maxTxPower, myAntennaConfig.maxTxPower);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, myAntennaConfigGroupId, myAntennaConfigGroup, isEnabled, portNumber, portName, txPowerInDbm, rxSensitivityInDbm, maxRxSensitivity, maxTxPower);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MyAntennaConfig {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    myAntennaConfigGroupId: ").append(toIndentedString(myAntennaConfigGroupId)).append("\n");
    sb.append("    myAntennaConfigGroup: ").append(toIndentedString(myAntennaConfigGroup)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    portNumber: ").append(toIndentedString(portNumber)).append("\n");
    sb.append("    portName: ").append(toIndentedString(portName)).append("\n");
    sb.append("    txPowerInDbm: ").append(toIndentedString(txPowerInDbm)).append("\n");
    sb.append("    rxSensitivityInDbm: ").append(toIndentedString(rxSensitivityInDbm)).append("\n");
    sb.append("    maxRxSensitivity: ").append(toIndentedString(maxRxSensitivity)).append("\n");
    sb.append("    maxTxPower: ").append(toIndentedString(maxTxPower)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
