/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ReaderProfile
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class ReaderProfile {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("session")
  private Integer session = null;

  @SerializedName("readerMode")
  private Integer readerMode = null;

  @SerializedName("searchMode")
  private Integer searchMode = null;

  @SerializedName("antennaConfigGroupId")
  private Integer antennaConfigGroupId = null;

  @SerializedName("myAntennaConfigGroup")
  private MyAntennaConfigGroup myAntennaConfigGroup = null;

  @SerializedName("configData")
  private String configData = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("myAntennaConfigs")
  private List<MyAntennaConfig> myAntennaConfigs = null;

  @SerializedName("readers")
  private List<Reader> readers = null;

  public ReaderProfile id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ReaderProfile name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ReaderProfile description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ReaderProfile session(Integer session) {
    this.session = session;
    return this;
  }

   /**
   * Get session
   * @return session
  **/
  @Schema(required = true, description = "")
  public Integer getSession() {
    return session;
  }

  public void setSession(Integer session) {
    this.session = session;
  }

  public ReaderProfile readerMode(Integer readerMode) {
    this.readerMode = readerMode;
    return this;
  }

   /**
   * Get readerMode
   * @return readerMode
  **/
  @Schema(required = true, description = "")
  public Integer getReaderMode() {
    return readerMode;
  }

  public void setReaderMode(Integer readerMode) {
    this.readerMode = readerMode;
  }

  public ReaderProfile searchMode(Integer searchMode) {
    this.searchMode = searchMode;
    return this;
  }

   /**
   * Get searchMode
   * @return searchMode
  **/
  @Schema(required = true, description = "")
  public Integer getSearchMode() {
    return searchMode;
  }

  public void setSearchMode(Integer searchMode) {
    this.searchMode = searchMode;
  }

  public ReaderProfile antennaConfigGroupId(Integer antennaConfigGroupId) {
    this.antennaConfigGroupId = antennaConfigGroupId;
    return this;
  }

   /**
   * Get antennaConfigGroupId
   * @return antennaConfigGroupId
  **/
  @Schema(description = "")
  public Integer getAntennaConfigGroupId() {
    return antennaConfigGroupId;
  }

  public void setAntennaConfigGroupId(Integer antennaConfigGroupId) {
    this.antennaConfigGroupId = antennaConfigGroupId;
  }

  public ReaderProfile myAntennaConfigGroup(MyAntennaConfigGroup myAntennaConfigGroup) {
    this.myAntennaConfigGroup = myAntennaConfigGroup;
    return this;
  }

   /**
   * Get myAntennaConfigGroup
   * @return myAntennaConfigGroup
  **/
  @Schema(description = "")
  public MyAntennaConfigGroup getMyAntennaConfigGroup() {
    return myAntennaConfigGroup;
  }

  public void setMyAntennaConfigGroup(MyAntennaConfigGroup myAntennaConfigGroup) {
    this.myAntennaConfigGroup = myAntennaConfigGroup;
  }

  public ReaderProfile configData(String configData) {
    this.configData = configData;
    return this;
  }

   /**
   * Get configData
   * @return configData
  **/
  @Schema(description = "")
  public String getConfigData() {
    return configData;
  }

  public void setConfigData(String configData) {
    this.configData = configData;
  }

  public ReaderProfile extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public ReaderProfile myAntennaConfigs(List<MyAntennaConfig> myAntennaConfigs) {
    this.myAntennaConfigs = myAntennaConfigs;
    return this;
  }

  public ReaderProfile addMyAntennaConfigsItem(MyAntennaConfig myAntennaConfigsItem) {
    if (this.myAntennaConfigs == null) {
      this.myAntennaConfigs = new ArrayList<MyAntennaConfig>();
    }
    this.myAntennaConfigs.add(myAntennaConfigsItem);
    return this;
  }

   /**
   * Get myAntennaConfigs
   * @return myAntennaConfigs
  **/
  @Schema(description = "")
  public List<MyAntennaConfig> getMyAntennaConfigs() {
    return myAntennaConfigs;
  }

  public void setMyAntennaConfigs(List<MyAntennaConfig> myAntennaConfigs) {
    this.myAntennaConfigs = myAntennaConfigs;
  }

  public ReaderProfile readers(List<Reader> readers) {
    this.readers = readers;
    return this;
  }

  public ReaderProfile addReadersItem(Reader readersItem) {
    if (this.readers == null) {
      this.readers = new ArrayList<Reader>();
    }
    this.readers.add(readersItem);
    return this;
  }

   /**
   * Get readers
   * @return readers
  **/
  @Schema(description = "")
  public List<Reader> getReaders() {
    return readers;
  }

  public void setReaders(List<Reader> readers) {
    this.readers = readers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReaderProfile readerProfile = (ReaderProfile) o;
    return Objects.equals(this.id, readerProfile.id) &&
        Objects.equals(this.name, readerProfile.name) &&
        Objects.equals(this.description, readerProfile.description) &&
        Objects.equals(this.session, readerProfile.session) &&
        Objects.equals(this.readerMode, readerProfile.readerMode) &&
        Objects.equals(this.searchMode, readerProfile.searchMode) &&
        Objects.equals(this.antennaConfigGroupId, readerProfile.antennaConfigGroupId) &&
        Objects.equals(this.myAntennaConfigGroup, readerProfile.myAntennaConfigGroup) &&
        Objects.equals(this.configData, readerProfile.configData) &&
        Objects.equals(this.extInfo, readerProfile.extInfo) &&
        Objects.equals(this.myAntennaConfigs, readerProfile.myAntennaConfigs) &&
        Objects.equals(this.readers, readerProfile.readers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, session, readerMode, searchMode, antennaConfigGroupId, myAntennaConfigGroup, configData, extInfo, myAntennaConfigs, readers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReaderProfile {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    readerMode: ").append(toIndentedString(readerMode)).append("\n");
    sb.append("    searchMode: ").append(toIndentedString(searchMode)).append("\n");
    sb.append("    antennaConfigGroupId: ").append(toIndentedString(antennaConfigGroupId)).append("\n");
    sb.append("    myAntennaConfigGroup: ").append(toIndentedString(myAntennaConfigGroup)).append("\n");
    sb.append("    configData: ").append(toIndentedString(configData)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    myAntennaConfigs: ").append(toIndentedString(myAntennaConfigs)).append("\n");
    sb.append("    readers: ").append(toIndentedString(readers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
