/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Reader
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class Reader {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("supportedReaderModel")
  private SupportedReaderModel supportedReaderModel = null;

  @SerializedName("supportedReaderModelId")
  private Integer supportedReaderModelId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("serialNumber")
  private String serialNumber = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("readerAddress")
  private String readerAddress = null;

  @SerializedName("readerProfileId")
  private Integer readerProfileId = null;

  @SerializedName("readerProfile")
  private ReaderProfile readerProfile = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("monitorPointId")
  private Integer monitorPointId = null;

  @SerializedName("monitorPoint")
  private MonitorPoint monitorPoint = null;

  @SerializedName("currentStatus")
  private Integer currentStatus = null;

  @SerializedName("userName")
  private String userName = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("tagDetectionLogs")
  private List<TagDetectionLog> tagDetectionLogs = null;

  public Reader id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Reader supportedReaderModel(SupportedReaderModel supportedReaderModel) {
    this.supportedReaderModel = supportedReaderModel;
    return this;
  }

   /**
   * Get supportedReaderModel
   * @return supportedReaderModel
  **/
  @Schema(description = "")
  public SupportedReaderModel getSupportedReaderModel() {
    return supportedReaderModel;
  }

  public void setSupportedReaderModel(SupportedReaderModel supportedReaderModel) {
    this.supportedReaderModel = supportedReaderModel;
  }

  public Reader supportedReaderModelId(Integer supportedReaderModelId) {
    this.supportedReaderModelId = supportedReaderModelId;
    return this;
  }

   /**
   * Get supportedReaderModelId
   * @return supportedReaderModelId
  **/
  @Schema(description = "")
  public Integer getSupportedReaderModelId() {
    return supportedReaderModelId;
  }

  public void setSupportedReaderModelId(Integer supportedReaderModelId) {
    this.supportedReaderModelId = supportedReaderModelId;
  }

  public Reader name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Reader serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @Schema(description = "")
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public Reader description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Reader readerAddress(String readerAddress) {
    this.readerAddress = readerAddress;
    return this;
  }

   /**
   * Get readerAddress
   * @return readerAddress
  **/
  @Schema(required = true, description = "")
  public String getReaderAddress() {
    return readerAddress;
  }

  public void setReaderAddress(String readerAddress) {
    this.readerAddress = readerAddress;
  }

  public Reader readerProfileId(Integer readerProfileId) {
    this.readerProfileId = readerProfileId;
    return this;
  }

   /**
   * Get readerProfileId
   * @return readerProfileId
  **/
  @Schema(required = true, description = "")
  public Integer getReaderProfileId() {
    return readerProfileId;
  }

  public void setReaderProfileId(Integer readerProfileId) {
    this.readerProfileId = readerProfileId;
  }

  public Reader readerProfile(ReaderProfile readerProfile) {
    this.readerProfile = readerProfile;
    return this;
  }

   /**
   * Get readerProfile
   * @return readerProfile
  **/
  @Schema(description = "")
  public ReaderProfile getReaderProfile() {
    return readerProfile;
  }

  public void setReaderProfile(ReaderProfile readerProfile) {
    this.readerProfile = readerProfile;
  }

  public Reader extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public Reader monitorPointId(Integer monitorPointId) {
    this.monitorPointId = monitorPointId;
    return this;
  }

   /**
   * Get monitorPointId
   * @return monitorPointId
  **/
  @Schema(required = true, description = "")
  public Integer getMonitorPointId() {
    return monitorPointId;
  }

  public void setMonitorPointId(Integer monitorPointId) {
    this.monitorPointId = monitorPointId;
  }

  public Reader monitorPoint(MonitorPoint monitorPoint) {
    this.monitorPoint = monitorPoint;
    return this;
  }

   /**
   * Get monitorPoint
   * @return monitorPoint
  **/
  @Schema(description = "")
  public MonitorPoint getMonitorPoint() {
    return monitorPoint;
  }

  public void setMonitorPoint(MonitorPoint monitorPoint) {
    this.monitorPoint = monitorPoint;
  }

  public Reader currentStatus(Integer currentStatus) {
    this.currentStatus = currentStatus;
    return this;
  }

   /**
   * Get currentStatus
   * @return currentStatus
  **/
  @Schema(description = "")
  public Integer getCurrentStatus() {
    return currentStatus;
  }

  public void setCurrentStatus(Integer currentStatus) {
    this.currentStatus = currentStatus;
  }

  public Reader userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @Schema(description = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public Reader password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @Schema(description = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public Reader tagDetectionLogs(List<TagDetectionLog> tagDetectionLogs) {
    this.tagDetectionLogs = tagDetectionLogs;
    return this;
  }

  public Reader addTagDetectionLogsItem(TagDetectionLog tagDetectionLogsItem) {
    if (this.tagDetectionLogs == null) {
      this.tagDetectionLogs = new ArrayList<TagDetectionLog>();
    }
    this.tagDetectionLogs.add(tagDetectionLogsItem);
    return this;
  }

   /**
   * Get tagDetectionLogs
   * @return tagDetectionLogs
  **/
  @Schema(description = "")
  public List<TagDetectionLog> getTagDetectionLogs() {
    return tagDetectionLogs;
  }

  public void setTagDetectionLogs(List<TagDetectionLog> tagDetectionLogs) {
    this.tagDetectionLogs = tagDetectionLogs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reader reader = (Reader) o;
    return Objects.equals(this.id, reader.id) &&
        Objects.equals(this.supportedReaderModel, reader.supportedReaderModel) &&
        Objects.equals(this.supportedReaderModelId, reader.supportedReaderModelId) &&
        Objects.equals(this.name, reader.name) &&
        Objects.equals(this.serialNumber, reader.serialNumber) &&
        Objects.equals(this.description, reader.description) &&
        Objects.equals(this.readerAddress, reader.readerAddress) &&
        Objects.equals(this.readerProfileId, reader.readerProfileId) &&
        Objects.equals(this.readerProfile, reader.readerProfile) &&
        Objects.equals(this.extInfo, reader.extInfo) &&
        Objects.equals(this.monitorPointId, reader.monitorPointId) &&
        Objects.equals(this.monitorPoint, reader.monitorPoint) &&
        Objects.equals(this.currentStatus, reader.currentStatus) &&
        Objects.equals(this.userName, reader.userName) &&
        Objects.equals(this.password, reader.password) &&
        Objects.equals(this.tagDetectionLogs, reader.tagDetectionLogs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, supportedReaderModel, supportedReaderModelId, name, serialNumber, description, readerAddress, readerProfileId, readerProfile, extInfo, monitorPointId, monitorPoint, currentStatus, userName, password, tagDetectionLogs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reader {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    supportedReaderModel: ").append(toIndentedString(supportedReaderModel)).append("\n");
    sb.append("    supportedReaderModelId: ").append(toIndentedString(supportedReaderModelId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    readerAddress: ").append(toIndentedString(readerAddress)).append("\n");
    sb.append("    readerProfileId: ").append(toIndentedString(readerProfileId)).append("\n");
    sb.append("    readerProfile: ").append(toIndentedString(readerProfile)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    monitorPointId: ").append(toIndentedString(monitorPointId)).append("\n");
    sb.append("    monitorPoint: ").append(toIndentedString(monitorPoint)).append("\n");
    sb.append("    currentStatus: ").append(toIndentedString(currentStatus)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    tagDetectionLogs: ").append(toIndentedString(tagDetectionLogs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
