/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * RfidTag
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class RfidTag {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("manufacturerId")
  private Integer manufacturerId = null;

  @SerializedName("manufacturer")
  private Manufacturer manufacturer = null;

  @SerializedName("tagTypeId")
  private Integer tagTypeId = null;

  @SerializedName("tagType")
  private TagType tagType = null;

  @SerializedName("tid")
  private String tid = null;

  @SerializedName("epc")
  private String epc = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("importDate")
  private OffsetDateTime importDate = null;

  @SerializedName("initiationTime")
  private OffsetDateTime initiationTime = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("accessPassword")
  private String accessPassword = null;

  @SerializedName("taggedItems")
  private List<TaggedItem> taggedItems = null;

  public RfidTag id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public RfidTag manufacturerId(Integer manufacturerId) {
    this.manufacturerId = manufacturerId;
    return this;
  }

   /**
   * Get manufacturerId
   * @return manufacturerId
  **/
  @Schema(required = true, description = "")
  public Integer getManufacturerId() {
    return manufacturerId;
  }

  public void setManufacturerId(Integer manufacturerId) {
    this.manufacturerId = manufacturerId;
  }

  public RfidTag manufacturer(Manufacturer manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

   /**
   * Get manufacturer
   * @return manufacturer
  **/
  @Schema(description = "")
  public Manufacturer getManufacturer() {
    return manufacturer;
  }

  public void setManufacturer(Manufacturer manufacturer) {
    this.manufacturer = manufacturer;
  }

  public RfidTag tagTypeId(Integer tagTypeId) {
    this.tagTypeId = tagTypeId;
    return this;
  }

   /**
   * Get tagTypeId
   * @return tagTypeId
  **/
  @Schema(description = "")
  public Integer getTagTypeId() {
    return tagTypeId;
  }

  public void setTagTypeId(Integer tagTypeId) {
    this.tagTypeId = tagTypeId;
  }

  public RfidTag tagType(TagType tagType) {
    this.tagType = tagType;
    return this;
  }

   /**
   * Get tagType
   * @return tagType
  **/
  @Schema(description = "")
  public TagType getTagType() {
    return tagType;
  }

  public void setTagType(TagType tagType) {
    this.tagType = tagType;
  }

  public RfidTag tid(String tid) {
    this.tid = tid;
    return this;
  }

   /**
   * Get tid
   * @return tid
  **/
  @Schema(required = true, description = "")
  public String getTid() {
    return tid;
  }

  public void setTid(String tid) {
    this.tid = tid;
  }

  public RfidTag epc(String epc) {
    this.epc = epc;
    return this;
  }

   /**
   * Get epc
   * @return epc
  **/
  @Schema(description = "")
  public String getEpc() {
    return epc;
  }

  public void setEpc(String epc) {
    this.epc = epc;
  }

  public RfidTag extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public RfidTag importDate(OffsetDateTime importDate) {
    this.importDate = importDate;
    return this;
  }

   /**
   * Get importDate
   * @return importDate
  **/
  @Schema(description = "")
  public OffsetDateTime getImportDate() {
    return importDate;
  }

  public void setImportDate(OffsetDateTime importDate) {
    this.importDate = importDate;
  }

  public RfidTag initiationTime(OffsetDateTime initiationTime) {
    this.initiationTime = initiationTime;
    return this;
  }

   /**
   * Get initiationTime
   * @return initiationTime
  **/
  @Schema(description = "")
  public OffsetDateTime getInitiationTime() {
    return initiationTime;
  }

  public void setInitiationTime(OffsetDateTime initiationTime) {
    this.initiationTime = initiationTime;
  }

  public RfidTag status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public RfidTag accessPassword(String accessPassword) {
    this.accessPassword = accessPassword;
    return this;
  }

   /**
   * Get accessPassword
   * @return accessPassword
  **/
  @Schema(description = "")
  public String getAccessPassword() {
    return accessPassword;
  }

  public void setAccessPassword(String accessPassword) {
    this.accessPassword = accessPassword;
  }

  public RfidTag taggedItems(List<TaggedItem> taggedItems) {
    this.taggedItems = taggedItems;
    return this;
  }

  public RfidTag addTaggedItemsItem(TaggedItem taggedItemsItem) {
    if (this.taggedItems == null) {
      this.taggedItems = new ArrayList<TaggedItem>();
    }
    this.taggedItems.add(taggedItemsItem);
    return this;
  }

   /**
   * Get taggedItems
   * @return taggedItems
  **/
  @Schema(description = "")
  public List<TaggedItem> getTaggedItems() {
    return taggedItems;
  }

  public void setTaggedItems(List<TaggedItem> taggedItems) {
    this.taggedItems = taggedItems;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RfidTag rfidTag = (RfidTag) o;
    return Objects.equals(this.id, rfidTag.id) &&
        Objects.equals(this.manufacturerId, rfidTag.manufacturerId) &&
        Objects.equals(this.manufacturer, rfidTag.manufacturer) &&
        Objects.equals(this.tagTypeId, rfidTag.tagTypeId) &&
        Objects.equals(this.tagType, rfidTag.tagType) &&
        Objects.equals(this.tid, rfidTag.tid) &&
        Objects.equals(this.epc, rfidTag.epc) &&
        Objects.equals(this.extInfo, rfidTag.extInfo) &&
        Objects.equals(this.importDate, rfidTag.importDate) &&
        Objects.equals(this.initiationTime, rfidTag.initiationTime) &&
        Objects.equals(this.status, rfidTag.status) &&
        Objects.equals(this.accessPassword, rfidTag.accessPassword) &&
        Objects.equals(this.taggedItems, rfidTag.taggedItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, manufacturerId, manufacturer, tagTypeId, tagType, tid, epc, extInfo, importDate, initiationTime, status, accessPassword, taggedItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RfidTag {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    manufacturerId: ").append(toIndentedString(manufacturerId)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    tagTypeId: ").append(toIndentedString(tagTypeId)).append("\n");
    sb.append("    tagType: ").append(toIndentedString(tagType)).append("\n");
    sb.append("    tid: ").append(toIndentedString(tid)).append("\n");
    sb.append("    epc: ").append(toIndentedString(epc)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    importDate: ").append(toIndentedString(importDate)).append("\n");
    sb.append("    initiationTime: ").append(toIndentedString(initiationTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    accessPassword: ").append(toIndentedString(accessPassword)).append("\n");
    sb.append("    taggedItems: ").append(toIndentedString(taggedItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
