/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SoftwarePackage
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class SoftwarePackage {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("trialIntervalInDays")
  private Integer trialIntervalInDays = null;

  @SerializedName("monthlyPrice")
  private Double monthlyPrice = null;

  @SerializedName("sixMonthPrice")
  private Double sixMonthPrice = null;

  @SerializedName("annualPrice")
  private Double annualPrice = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("systemsInPackages")
  private List<SystemsInPackage> systemsInPackages = null;

  @SerializedName("tenantSubscriptions")
  private List<TenantSubscription> tenantSubscriptions = null;

  @SerializedName("image")
  private String image = null;

  public SoftwarePackage id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public SoftwarePackage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SoftwarePackage description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SoftwarePackage trialIntervalInDays(Integer trialIntervalInDays) {
    this.trialIntervalInDays = trialIntervalInDays;
    return this;
  }

   /**
   * Get trialIntervalInDays
   * @return trialIntervalInDays
  **/
  @Schema(description = "")
  public Integer getTrialIntervalInDays() {
    return trialIntervalInDays;
  }

  public void setTrialIntervalInDays(Integer trialIntervalInDays) {
    this.trialIntervalInDays = trialIntervalInDays;
  }

  public SoftwarePackage monthlyPrice(Double monthlyPrice) {
    this.monthlyPrice = monthlyPrice;
    return this;
  }

   /**
   * Get monthlyPrice
   * @return monthlyPrice
  **/
  @Schema(description = "")
  public Double getMonthlyPrice() {
    return monthlyPrice;
  }

  public void setMonthlyPrice(Double monthlyPrice) {
    this.monthlyPrice = monthlyPrice;
  }

  public SoftwarePackage sixMonthPrice(Double sixMonthPrice) {
    this.sixMonthPrice = sixMonthPrice;
    return this;
  }

   /**
   * Get sixMonthPrice
   * @return sixMonthPrice
  **/
  @Schema(description = "")
  public Double getSixMonthPrice() {
    return sixMonthPrice;
  }

  public void setSixMonthPrice(Double sixMonthPrice) {
    this.sixMonthPrice = sixMonthPrice;
  }

  public SoftwarePackage annualPrice(Double annualPrice) {
    this.annualPrice = annualPrice;
    return this;
  }

   /**
   * Get annualPrice
   * @return annualPrice
  **/
  @Schema(description = "")
  public Double getAnnualPrice() {
    return annualPrice;
  }

  public void setAnnualPrice(Double annualPrice) {
    this.annualPrice = annualPrice;
  }

  public SoftwarePackage extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public SoftwarePackage systemsInPackages(List<SystemsInPackage> systemsInPackages) {
    this.systemsInPackages = systemsInPackages;
    return this;
  }

  public SoftwarePackage addSystemsInPackagesItem(SystemsInPackage systemsInPackagesItem) {
    if (this.systemsInPackages == null) {
      this.systemsInPackages = new ArrayList<SystemsInPackage>();
    }
    this.systemsInPackages.add(systemsInPackagesItem);
    return this;
  }

   /**
   * Get systemsInPackages
   * @return systemsInPackages
  **/
  @Schema(description = "")
  public List<SystemsInPackage> getSystemsInPackages() {
    return systemsInPackages;
  }

  public void setSystemsInPackages(List<SystemsInPackage> systemsInPackages) {
    this.systemsInPackages = systemsInPackages;
  }

  public SoftwarePackage tenantSubscriptions(List<TenantSubscription> tenantSubscriptions) {
    this.tenantSubscriptions = tenantSubscriptions;
    return this;
  }

  public SoftwarePackage addTenantSubscriptionsItem(TenantSubscription tenantSubscriptionsItem) {
    if (this.tenantSubscriptions == null) {
      this.tenantSubscriptions = new ArrayList<TenantSubscription>();
    }
    this.tenantSubscriptions.add(tenantSubscriptionsItem);
    return this;
  }

   /**
   * Get tenantSubscriptions
   * @return tenantSubscriptions
  **/
  @Schema(description = "")
  public List<TenantSubscription> getTenantSubscriptions() {
    return tenantSubscriptions;
  }

  public void setTenantSubscriptions(List<TenantSubscription> tenantSubscriptions) {
    this.tenantSubscriptions = tenantSubscriptions;
  }

  public SoftwarePackage image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(description = "")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SoftwarePackage softwarePackage = (SoftwarePackage) o;
    return Objects.equals(this.id, softwarePackage.id) &&
        Objects.equals(this.name, softwarePackage.name) &&
        Objects.equals(this.description, softwarePackage.description) &&
        Objects.equals(this.trialIntervalInDays, softwarePackage.trialIntervalInDays) &&
        Objects.equals(this.monthlyPrice, softwarePackage.monthlyPrice) &&
        Objects.equals(this.sixMonthPrice, softwarePackage.sixMonthPrice) &&
        Objects.equals(this.annualPrice, softwarePackage.annualPrice) &&
        Objects.equals(this.extInfo, softwarePackage.extInfo) &&
        Objects.equals(this.systemsInPackages, softwarePackage.systemsInPackages) &&
        Objects.equals(this.tenantSubscriptions, softwarePackage.tenantSubscriptions) &&
        Objects.equals(this.image, softwarePackage.image);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, trialIntervalInDays, monthlyPrice, sixMonthPrice, annualPrice, extInfo, systemsInPackages, tenantSubscriptions, image);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SoftwarePackage {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    trialIntervalInDays: ").append(toIndentedString(trialIntervalInDays)).append("\n");
    sb.append("    monthlyPrice: ").append(toIndentedString(monthlyPrice)).append("\n");
    sb.append("    sixMonthPrice: ").append(toIndentedString(sixMonthPrice)).append("\n");
    sb.append("    annualPrice: ").append(toIndentedString(annualPrice)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    systemsInPackages: ").append(toIndentedString(systemsInPackages)).append("\n");
    sb.append("    tenantSubscriptions: ").append(toIndentedString(tenantSubscriptions)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
