/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets Specializations
 */
@JsonAdapter(Specializations.Adapter.class)
public enum Specializations {
  @SerializedName("1")
  NUMBER_1(1),
  @SerializedName("2")
  NUMBER_2(2),
  @SerializedName("4")
  NUMBER_4(4),
  @SerializedName("8")
  NUMBER_8(8),
  @SerializedName("16")
  NUMBER_16(16),
  @SerializedName("32")
  NUMBER_32(32);

  private Integer value;

  Specializations(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Specializations fromValue(Integer input) {
    for (Specializations b : Specializations.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Specializations> {
    @Override
    public void write(final JsonWriter jsonWriter, final Specializations enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public Specializations read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextInt();
      return Specializations.fromValue((Integer)(value));
    }
  }
}
