/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SupportedReaderModel
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class SupportedReaderModel {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("manufacturerId")
  private Integer manufacturerId = null;

  @SerializedName("manufacturer")
  private Manufacturer manufacturer = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("model")
  private String model = null;

  @SerializedName("rfidType")
  private Integer rfidType = null;

  @SerializedName("readerType")
  private Integer readerType = null;

  @SerializedName("images")
  private String images = null;

  @SerializedName("canReadRfid")
  private Boolean canReadRfid = null;

  @SerializedName("canScanBarCode")
  private Boolean canScanBarCode = null;

  @SerializedName("canTrackZone")
  private Boolean canTrackZone = null;

  @SerializedName("canTrackLocation")
  private Boolean canTrackLocation = null;

  @SerializedName("canTakePhoto")
  private Boolean canTakePhoto = null;

  @SerializedName("canTrackDirection")
  private Boolean canTrackDirection = null;

  @SerializedName("imageNames")
  private List<String> imageNames = null;

  @SerializedName("documentUrl")
  private String documentUrl = null;

  @SerializedName("implementClass")
  private String implementClass = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("readers")
  private List<Reader> readers = null;

  public SupportedReaderModel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public SupportedReaderModel manufacturerId(Integer manufacturerId) {
    this.manufacturerId = manufacturerId;
    return this;
  }

   /**
   * Get manufacturerId
   * @return manufacturerId
  **/
  @Schema(required = true, description = "")
  public Integer getManufacturerId() {
    return manufacturerId;
  }

  public void setManufacturerId(Integer manufacturerId) {
    this.manufacturerId = manufacturerId;
  }

  public SupportedReaderModel manufacturer(Manufacturer manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

   /**
   * Get manufacturer
   * @return manufacturer
  **/
  @Schema(description = "")
  public Manufacturer getManufacturer() {
    return manufacturer;
  }

  public void setManufacturer(Manufacturer manufacturer) {
    this.manufacturer = manufacturer;
  }

  public SupportedReaderModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SupportedReaderModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SupportedReaderModel model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @Schema(required = true, description = "")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public SupportedReaderModel rfidType(Integer rfidType) {
    this.rfidType = rfidType;
    return this;
  }

   /**
   * Get rfidType
   * @return rfidType
  **/
  @Schema(required = true, description = "")
  public Integer getRfidType() {
    return rfidType;
  }

  public void setRfidType(Integer rfidType) {
    this.rfidType = rfidType;
  }

  public SupportedReaderModel readerType(Integer readerType) {
    this.readerType = readerType;
    return this;
  }

   /**
   * Get readerType
   * @return readerType
  **/
  @Schema(required = true, description = "")
  public Integer getReaderType() {
    return readerType;
  }

  public void setReaderType(Integer readerType) {
    this.readerType = readerType;
  }

  public SupportedReaderModel images(String images) {
    this.images = images;
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @Schema(description = "")
  public String getImages() {
    return images;
  }

  public void setImages(String images) {
    this.images = images;
  }

  public SupportedReaderModel canReadRfid(Boolean canReadRfid) {
    this.canReadRfid = canReadRfid;
    return this;
  }

   /**
   * Get canReadRfid
   * @return canReadRfid
  **/
  @Schema(description = "")
  public Boolean isCanReadRfid() {
    return canReadRfid;
  }

  public void setCanReadRfid(Boolean canReadRfid) {
    this.canReadRfid = canReadRfid;
  }

  public SupportedReaderModel canScanBarCode(Boolean canScanBarCode) {
    this.canScanBarCode = canScanBarCode;
    return this;
  }

   /**
   * Get canScanBarCode
   * @return canScanBarCode
  **/
  @Schema(description = "")
  public Boolean isCanScanBarCode() {
    return canScanBarCode;
  }

  public void setCanScanBarCode(Boolean canScanBarCode) {
    this.canScanBarCode = canScanBarCode;
  }

  public SupportedReaderModel canTrackZone(Boolean canTrackZone) {
    this.canTrackZone = canTrackZone;
    return this;
  }

   /**
   * Get canTrackZone
   * @return canTrackZone
  **/
  @Schema(description = "")
  public Boolean isCanTrackZone() {
    return canTrackZone;
  }

  public void setCanTrackZone(Boolean canTrackZone) {
    this.canTrackZone = canTrackZone;
  }

  public SupportedReaderModel canTrackLocation(Boolean canTrackLocation) {
    this.canTrackLocation = canTrackLocation;
    return this;
  }

   /**
   * Get canTrackLocation
   * @return canTrackLocation
  **/
  @Schema(description = "")
  public Boolean isCanTrackLocation() {
    return canTrackLocation;
  }

  public void setCanTrackLocation(Boolean canTrackLocation) {
    this.canTrackLocation = canTrackLocation;
  }

  public SupportedReaderModel canTakePhoto(Boolean canTakePhoto) {
    this.canTakePhoto = canTakePhoto;
    return this;
  }

   /**
   * Get canTakePhoto
   * @return canTakePhoto
  **/
  @Schema(description = "")
  public Boolean isCanTakePhoto() {
    return canTakePhoto;
  }

  public void setCanTakePhoto(Boolean canTakePhoto) {
    this.canTakePhoto = canTakePhoto;
  }

  public SupportedReaderModel canTrackDirection(Boolean canTrackDirection) {
    this.canTrackDirection = canTrackDirection;
    return this;
  }

   /**
   * Get canTrackDirection
   * @return canTrackDirection
  **/
  @Schema(description = "")
  public Boolean isCanTrackDirection() {
    return canTrackDirection;
  }

  public void setCanTrackDirection(Boolean canTrackDirection) {
    this.canTrackDirection = canTrackDirection;
  }

   /**
   * Get imageNames
   * @return imageNames
  **/
  @Schema(description = "")
  public List<String> getImageNames() {
    return imageNames;
  }

  public SupportedReaderModel documentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
    return this;
  }

   /**
   * Get documentUrl
   * @return documentUrl
  **/
  @Schema(description = "")
  public String getDocumentUrl() {
    return documentUrl;
  }

  public void setDocumentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
  }

  public SupportedReaderModel implementClass(String implementClass) {
    this.implementClass = implementClass;
    return this;
  }

   /**
   * Get implementClass
   * @return implementClass
  **/
  @Schema(required = true, description = "")
  public String getImplementClass() {
    return implementClass;
  }

  public void setImplementClass(String implementClass) {
    this.implementClass = implementClass;
  }

  public SupportedReaderModel extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public SupportedReaderModel readers(List<Reader> readers) {
    this.readers = readers;
    return this;
  }

  public SupportedReaderModel addReadersItem(Reader readersItem) {
    if (this.readers == null) {
      this.readers = new ArrayList<Reader>();
    }
    this.readers.add(readersItem);
    return this;
  }

   /**
   * Get readers
   * @return readers
  **/
  @Schema(description = "")
  public List<Reader> getReaders() {
    return readers;
  }

  public void setReaders(List<Reader> readers) {
    this.readers = readers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupportedReaderModel supportedReaderModel = (SupportedReaderModel) o;
    return Objects.equals(this.id, supportedReaderModel.id) &&
        Objects.equals(this.manufacturerId, supportedReaderModel.manufacturerId) &&
        Objects.equals(this.manufacturer, supportedReaderModel.manufacturer) &&
        Objects.equals(this.name, supportedReaderModel.name) &&
        Objects.equals(this.description, supportedReaderModel.description) &&
        Objects.equals(this.model, supportedReaderModel.model) &&
        Objects.equals(this.rfidType, supportedReaderModel.rfidType) &&
        Objects.equals(this.readerType, supportedReaderModel.readerType) &&
        Objects.equals(this.images, supportedReaderModel.images) &&
        Objects.equals(this.canReadRfid, supportedReaderModel.canReadRfid) &&
        Objects.equals(this.canScanBarCode, supportedReaderModel.canScanBarCode) &&
        Objects.equals(this.canTrackZone, supportedReaderModel.canTrackZone) &&
        Objects.equals(this.canTrackLocation, supportedReaderModel.canTrackLocation) &&
        Objects.equals(this.canTakePhoto, supportedReaderModel.canTakePhoto) &&
        Objects.equals(this.canTrackDirection, supportedReaderModel.canTrackDirection) &&
        Objects.equals(this.imageNames, supportedReaderModel.imageNames) &&
        Objects.equals(this.documentUrl, supportedReaderModel.documentUrl) &&
        Objects.equals(this.implementClass, supportedReaderModel.implementClass) &&
        Objects.equals(this.extInfo, supportedReaderModel.extInfo) &&
        Objects.equals(this.readers, supportedReaderModel.readers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, manufacturerId, manufacturer, name, description, model, rfidType, readerType, images, canReadRfid, canScanBarCode, canTrackZone, canTrackLocation, canTakePhoto, canTrackDirection, imageNames, documentUrl, implementClass, extInfo, readers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupportedReaderModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    manufacturerId: ").append(toIndentedString(manufacturerId)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    rfidType: ").append(toIndentedString(rfidType)).append("\n");
    sb.append("    readerType: ").append(toIndentedString(readerType)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    canReadRfid: ").append(toIndentedString(canReadRfid)).append("\n");
    sb.append("    canScanBarCode: ").append(toIndentedString(canScanBarCode)).append("\n");
    sb.append("    canTrackZone: ").append(toIndentedString(canTrackZone)).append("\n");
    sb.append("    canTrackLocation: ").append(toIndentedString(canTrackLocation)).append("\n");
    sb.append("    canTakePhoto: ").append(toIndentedString(canTakePhoto)).append("\n");
    sb.append("    canTrackDirection: ").append(toIndentedString(canTrackDirection)).append("\n");
    sb.append("    imageNames: ").append(toIndentedString(imageNames)).append("\n");
    sb.append("    documentUrl: ").append(toIndentedString(documentUrl)).append("\n");
    sb.append("    implementClass: ").append(toIndentedString(implementClass)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    readers: ").append(toIndentedString(readers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
