/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SystemsInPackage
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class SystemsInPackage {
  @SerializedName("softwarePackageId")
  private Integer softwarePackageId = null;

  @SerializedName("softwarePackage")
  private SoftwarePackage softwarePackage = null;

  @SerializedName("systemId")
  private Integer systemId = null;

  @SerializedName("btSystem")
  private BtSystem btSystem = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  public SystemsInPackage softwarePackageId(Integer softwarePackageId) {
    this.softwarePackageId = softwarePackageId;
    return this;
  }

   /**
   * Get softwarePackageId
   * @return softwarePackageId
  **/
  @Schema(required = true, description = "")
  public Integer getSoftwarePackageId() {
    return softwarePackageId;
  }

  public void setSoftwarePackageId(Integer softwarePackageId) {
    this.softwarePackageId = softwarePackageId;
  }

  public SystemsInPackage softwarePackage(SoftwarePackage softwarePackage) {
    this.softwarePackage = softwarePackage;
    return this;
  }

   /**
   * Get softwarePackage
   * @return softwarePackage
  **/
  @Schema(description = "")
  public SoftwarePackage getSoftwarePackage() {
    return softwarePackage;
  }

  public void setSoftwarePackage(SoftwarePackage softwarePackage) {
    this.softwarePackage = softwarePackage;
  }

  public SystemsInPackage systemId(Integer systemId) {
    this.systemId = systemId;
    return this;
  }

   /**
   * Get systemId
   * @return systemId
  **/
  @Schema(required = true, description = "")
  public Integer getSystemId() {
    return systemId;
  }

  public void setSystemId(Integer systemId) {
    this.systemId = systemId;
  }

  public SystemsInPackage btSystem(BtSystem btSystem) {
    this.btSystem = btSystem;
    return this;
  }

   /**
   * Get btSystem
   * @return btSystem
  **/
  @Schema(description = "")
  public BtSystem getBtSystem() {
    return btSystem;
  }

  public void setBtSystem(BtSystem btSystem) {
    this.btSystem = btSystem;
  }

  public SystemsInPackage extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemsInPackage systemsInPackage = (SystemsInPackage) o;
    return Objects.equals(this.softwarePackageId, systemsInPackage.softwarePackageId) &&
        Objects.equals(this.softwarePackage, systemsInPackage.softwarePackage) &&
        Objects.equals(this.systemId, systemsInPackage.systemId) &&
        Objects.equals(this.btSystem, systemsInPackage.btSystem) &&
        Objects.equals(this.extInfo, systemsInPackage.extInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(softwarePackageId, softwarePackage, systemId, btSystem, extInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemsInPackage {\n");
    
    sb.append("    softwarePackageId: ").append(toIndentedString(softwarePackageId)).append("\n");
    sb.append("    softwarePackage: ").append(toIndentedString(softwarePackage)).append("\n");
    sb.append("    systemId: ").append(toIndentedString(systemId)).append("\n");
    sb.append("    btSystem: ").append(toIndentedString(btSystem)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
