/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TagDetectionLog
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class TagDetectionLog {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("taggedItemId")
  private Integer taggedItemId = null;

  @SerializedName("taggedItem")
  private TaggedItem taggedItem = null;

  @SerializedName("monitorPointId")
  private Integer monitorPointId = null;

  @SerializedName("byReaderId")
  private Integer byReaderId = null;

  @SerializedName("reader")
  private Reader reader = null;

  @SerializedName("antennaPort")
  private Integer antennaPort = null;

  @SerializedName("detectedTime")
  private OffsetDateTime detectedTime = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  public TagDetectionLog id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TagDetectionLog taggedItemId(Integer taggedItemId) {
    this.taggedItemId = taggedItemId;
    return this;
  }

   /**
   * Get taggedItemId
   * @return taggedItemId
  **/
  @Schema(required = true, description = "")
  public Integer getTaggedItemId() {
    return taggedItemId;
  }

  public void setTaggedItemId(Integer taggedItemId) {
    this.taggedItemId = taggedItemId;
  }

  public TagDetectionLog taggedItem(TaggedItem taggedItem) {
    this.taggedItem = taggedItem;
    return this;
  }

   /**
   * Get taggedItem
   * @return taggedItem
  **/
  @Schema(description = "")
  public TaggedItem getTaggedItem() {
    return taggedItem;
  }

  public void setTaggedItem(TaggedItem taggedItem) {
    this.taggedItem = taggedItem;
  }

  public TagDetectionLog monitorPointId(Integer monitorPointId) {
    this.monitorPointId = monitorPointId;
    return this;
  }

   /**
   * Get monitorPointId
   * @return monitorPointId
  **/
  @Schema(required = true, description = "")
  public Integer getMonitorPointId() {
    return monitorPointId;
  }

  public void setMonitorPointId(Integer monitorPointId) {
    this.monitorPointId = monitorPointId;
  }

  public TagDetectionLog byReaderId(Integer byReaderId) {
    this.byReaderId = byReaderId;
    return this;
  }

   /**
   * Get byReaderId
   * @return byReaderId
  **/
  @Schema(required = true, description = "")
  public Integer getByReaderId() {
    return byReaderId;
  }

  public void setByReaderId(Integer byReaderId) {
    this.byReaderId = byReaderId;
  }

  public TagDetectionLog reader(Reader reader) {
    this.reader = reader;
    return this;
  }

   /**
   * Get reader
   * @return reader
  **/
  @Schema(description = "")
  public Reader getReader() {
    return reader;
  }

  public void setReader(Reader reader) {
    this.reader = reader;
  }

  public TagDetectionLog antennaPort(Integer antennaPort) {
    this.antennaPort = antennaPort;
    return this;
  }

   /**
   * Get antennaPort
   * @return antennaPort
  **/
  @Schema(required = true, description = "")
  public Integer getAntennaPort() {
    return antennaPort;
  }

  public void setAntennaPort(Integer antennaPort) {
    this.antennaPort = antennaPort;
  }

  public TagDetectionLog detectedTime(OffsetDateTime detectedTime) {
    this.detectedTime = detectedTime;
    return this;
  }

   /**
   * Get detectedTime
   * @return detectedTime
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getDetectedTime() {
    return detectedTime;
  }

  public void setDetectedTime(OffsetDateTime detectedTime) {
    this.detectedTime = detectedTime;
  }

  public TagDetectionLog extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(required = true, description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagDetectionLog tagDetectionLog = (TagDetectionLog) o;
    return Objects.equals(this.id, tagDetectionLog.id) &&
        Objects.equals(this.taggedItemId, tagDetectionLog.taggedItemId) &&
        Objects.equals(this.taggedItem, tagDetectionLog.taggedItem) &&
        Objects.equals(this.monitorPointId, tagDetectionLog.monitorPointId) &&
        Objects.equals(this.byReaderId, tagDetectionLog.byReaderId) &&
        Objects.equals(this.reader, tagDetectionLog.reader) &&
        Objects.equals(this.antennaPort, tagDetectionLog.antennaPort) &&
        Objects.equals(this.detectedTime, tagDetectionLog.detectedTime) &&
        Objects.equals(this.extInfo, tagDetectionLog.extInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, taggedItemId, taggedItem, monitorPointId, byReaderId, reader, antennaPort, detectedTime, extInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagDetectionLog {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    taggedItemId: ").append(toIndentedString(taggedItemId)).append("\n");
    sb.append("    taggedItem: ").append(toIndentedString(taggedItem)).append("\n");
    sb.append("    monitorPointId: ").append(toIndentedString(monitorPointId)).append("\n");
    sb.append("    byReaderId: ").append(toIndentedString(byReaderId)).append("\n");
    sb.append("    reader: ").append(toIndentedString(reader)).append("\n");
    sb.append("    antennaPort: ").append(toIndentedString(antennaPort)).append("\n");
    sb.append("    detectedTime: ").append(toIndentedString(detectedTime)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
