/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TaggedItem
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class TaggedItem {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("rfidTagId")
  private Integer rfidTagId = null;

  @SerializedName("rfidTag")
  private RfidTag rfidTag = null;

  @SerializedName("companyCode")
  private String companyCode = null;

  @SerializedName("barCode")
  private String barCode = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("taggedDate")
  private OffsetDateTime taggedDate = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("discriminator")
  private String discriminator = null;

  public TaggedItem id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TaggedItem rfidTagId(Integer rfidTagId) {
    this.rfidTagId = rfidTagId;
    return this;
  }

   /**
   * Get rfidTagId
   * @return rfidTagId
  **/
  @Schema(required = true, description = "")
  public Integer getRfidTagId() {
    return rfidTagId;
  }

  public void setRfidTagId(Integer rfidTagId) {
    this.rfidTagId = rfidTagId;
  }

  public TaggedItem rfidTag(RfidTag rfidTag) {
    this.rfidTag = rfidTag;
    return this;
  }

   /**
   * Get rfidTag
   * @return rfidTag
  **/
  @Schema(description = "")
  public RfidTag getRfidTag() {
    return rfidTag;
  }

  public void setRfidTag(RfidTag rfidTag) {
    this.rfidTag = rfidTag;
  }

  public TaggedItem companyCode(String companyCode) {
    this.companyCode = companyCode;
    return this;
  }

   /**
   * Get companyCode
   * @return companyCode
  **/
  @Schema(description = "")
  public String getCompanyCode() {
    return companyCode;
  }

  public void setCompanyCode(String companyCode) {
    this.companyCode = companyCode;
  }

  public TaggedItem barCode(String barCode) {
    this.barCode = barCode;
    return this;
  }

   /**
   * Get barCode
   * @return barCode
  **/
  @Schema(description = "")
  public String getBarCode() {
    return barCode;
  }

  public void setBarCode(String barCode) {
    this.barCode = barCode;
  }

  public TaggedItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TaggedItem description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TaggedItem taggedDate(OffsetDateTime taggedDate) {
    this.taggedDate = taggedDate;
    return this;
  }

   /**
   * Get taggedDate
   * @return taggedDate
  **/
  @Schema(description = "")
  public OffsetDateTime getTaggedDate() {
    return taggedDate;
  }

  public void setTaggedDate(OffsetDateTime taggedDate) {
    this.taggedDate = taggedDate;
  }

  public TaggedItem extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public TaggedItem discriminator(String discriminator) {
    this.discriminator = discriminator;
    return this;
  }

   /**
   * Get discriminator
   * @return discriminator
  **/
  @Schema(required = true, description = "")
  public String getDiscriminator() {
    return discriminator;
  }

  public void setDiscriminator(String discriminator) {
    this.discriminator = discriminator;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaggedItem taggedItem = (TaggedItem) o;
    return Objects.equals(this.id, taggedItem.id) &&
        Objects.equals(this.rfidTagId, taggedItem.rfidTagId) &&
        Objects.equals(this.rfidTag, taggedItem.rfidTag) &&
        Objects.equals(this.companyCode, taggedItem.companyCode) &&
        Objects.equals(this.barCode, taggedItem.barCode) &&
        Objects.equals(this.name, taggedItem.name) &&
        Objects.equals(this.description, taggedItem.description) &&
        Objects.equals(this.taggedDate, taggedItem.taggedDate) &&
        Objects.equals(this.extInfo, taggedItem.extInfo) &&
        Objects.equals(this.discriminator, taggedItem.discriminator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rfidTagId, rfidTag, companyCode, barCode, name, description, taggedDate, extInfo, discriminator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaggedItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rfidTagId: ").append(toIndentedString(rfidTagId)).append("\n");
    sb.append("    rfidTag: ").append(toIndentedString(rfidTag)).append("\n");
    sb.append("    companyCode: ").append(toIndentedString(companyCode)).append("\n");
    sb.append("    barCode: ").append(toIndentedString(barCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    taggedDate: ").append(toIndentedString(taggedDate)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    discriminator: ").append(toIndentedString(discriminator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
