/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TagType
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class TagType {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("rfidType")
  private Integer rfidType = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("mask")
  private String mask = null;

  @SerializedName("accessPassword")
  private String accessPassword = null;

  @SerializedName("lastAllocated")
  private Integer lastAllocated = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("commandDetails")
  private List<CommandDetail> commandDetails = null;

  @SerializedName("rfidTags")
  private List<RfidTag> rfidTags = null;

  public TagType id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TagType name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TagType rfidType(Integer rfidType) {
    this.rfidType = rfidType;
    return this;
  }

   /**
   * Get rfidType
   * @return rfidType
  **/
  @Schema(required = true, description = "")
  public Integer getRfidType() {
    return rfidType;
  }

  public void setRfidType(Integer rfidType) {
    this.rfidType = rfidType;
  }

  public TagType description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TagType mask(String mask) {
    this.mask = mask;
    return this;
  }

   /**
   * Get mask
   * @return mask
  **/
  @Schema(description = "")
  public String getMask() {
    return mask;
  }

  public void setMask(String mask) {
    this.mask = mask;
  }

  public TagType accessPassword(String accessPassword) {
    this.accessPassword = accessPassword;
    return this;
  }

   /**
   * Get accessPassword
   * @return accessPassword
  **/
  @Schema(description = "")
  public String getAccessPassword() {
    return accessPassword;
  }

  public void setAccessPassword(String accessPassword) {
    this.accessPassword = accessPassword;
  }

  public TagType lastAllocated(Integer lastAllocated) {
    this.lastAllocated = lastAllocated;
    return this;
  }

   /**
   * Get lastAllocated
   * @return lastAllocated
  **/
  @Schema(description = "")
  public Integer getLastAllocated() {
    return lastAllocated;
  }

  public void setLastAllocated(Integer lastAllocated) {
    this.lastAllocated = lastAllocated;
  }

  public TagType extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public TagType commandDetails(List<CommandDetail> commandDetails) {
    this.commandDetails = commandDetails;
    return this;
  }

  public TagType addCommandDetailsItem(CommandDetail commandDetailsItem) {
    if (this.commandDetails == null) {
      this.commandDetails = new ArrayList<CommandDetail>();
    }
    this.commandDetails.add(commandDetailsItem);
    return this;
  }

   /**
   * Get commandDetails
   * @return commandDetails
  **/
  @Schema(description = "")
  public List<CommandDetail> getCommandDetails() {
    return commandDetails;
  }

  public void setCommandDetails(List<CommandDetail> commandDetails) {
    this.commandDetails = commandDetails;
  }

  public TagType rfidTags(List<RfidTag> rfidTags) {
    this.rfidTags = rfidTags;
    return this;
  }

  public TagType addRfidTagsItem(RfidTag rfidTagsItem) {
    if (this.rfidTags == null) {
      this.rfidTags = new ArrayList<RfidTag>();
    }
    this.rfidTags.add(rfidTagsItem);
    return this;
  }

   /**
   * Get rfidTags
   * @return rfidTags
  **/
  @Schema(description = "")
  public List<RfidTag> getRfidTags() {
    return rfidTags;
  }

  public void setRfidTags(List<RfidTag> rfidTags) {
    this.rfidTags = rfidTags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagType tagType = (TagType) o;
    return Objects.equals(this.id, tagType.id) &&
        Objects.equals(this.name, tagType.name) &&
        Objects.equals(this.rfidType, tagType.rfidType) &&
        Objects.equals(this.description, tagType.description) &&
        Objects.equals(this.mask, tagType.mask) &&
        Objects.equals(this.accessPassword, tagType.accessPassword) &&
        Objects.equals(this.lastAllocated, tagType.lastAllocated) &&
        Objects.equals(this.extInfo, tagType.extInfo) &&
        Objects.equals(this.commandDetails, tagType.commandDetails) &&
        Objects.equals(this.rfidTags, tagType.rfidTags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, rfidType, description, mask, accessPassword, lastAllocated, extInfo, commandDetails, rfidTags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagType {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rfidType: ").append(toIndentedString(rfidType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    mask: ").append(toIndentedString(mask)).append("\n");
    sb.append("    accessPassword: ").append(toIndentedString(accessPassword)).append("\n");
    sb.append("    lastAllocated: ").append(toIndentedString(lastAllocated)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    commandDetails: ").append(toIndentedString(commandDetails)).append("\n");
    sb.append("    rfidTags: ").append(toIndentedString(rfidTags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
