/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Tenant
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class Tenant {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("tenantType")
  private Integer tenantType = null;

  @SerializedName("address1")
  private String address1 = null;

  @SerializedName("address2")
  private String address2 = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("taxCode")
  private String taxCode = null;

  @SerializedName("gs1Code")
  private String gs1Code = null;

  @SerializedName("isActivated")
  private Boolean isActivated = null;

  @SerializedName("enable")
  private Boolean enable = null;

  @SerializedName("extInfo")
  private String extInfo = null;

  @SerializedName("tenantSubscriptions")
  private List<TenantSubscription> tenantSubscriptions = null;

  public Tenant id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Tenant name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Tenant description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Tenant tenantType(Integer tenantType) {
    this.tenantType = tenantType;
    return this;
  }

   /**
   * Get tenantType
   * @return tenantType
  **/
  @Schema(required = true, description = "")
  public Integer getTenantType() {
    return tenantType;
  }

  public void setTenantType(Integer tenantType) {
    this.tenantType = tenantType;
  }

  public Tenant address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Get address1
   * @return address1
  **/
  @Schema(description = "")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public Tenant address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Get address2
   * @return address2
  **/
  @Schema(description = "")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public Tenant email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Tenant phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @Schema(description = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Tenant taxCode(String taxCode) {
    this.taxCode = taxCode;
    return this;
  }

   /**
   * Get taxCode
   * @return taxCode
  **/
  @Schema(description = "")
  public String getTaxCode() {
    return taxCode;
  }

  public void setTaxCode(String taxCode) {
    this.taxCode = taxCode;
  }

  public Tenant gs1Code(String gs1Code) {
    this.gs1Code = gs1Code;
    return this;
  }

   /**
   * Get gs1Code
   * @return gs1Code
  **/
  @Schema(description = "")
  public String getGs1Code() {
    return gs1Code;
  }

  public void setGs1Code(String gs1Code) {
    this.gs1Code = gs1Code;
  }

  public Tenant isActivated(Boolean isActivated) {
    this.isActivated = isActivated;
    return this;
  }

   /**
   * Get isActivated
   * @return isActivated
  **/
  @Schema(description = "")
  public Boolean isIsActivated() {
    return isActivated;
  }

  public void setIsActivated(Boolean isActivated) {
    this.isActivated = isActivated;
  }

  public Tenant enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  @Schema(description = "")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public Tenant extInfo(String extInfo) {
    this.extInfo = extInfo;
    return this;
  }

   /**
   * Get extInfo
   * @return extInfo
  **/
  @Schema(description = "")
  public String getExtInfo() {
    return extInfo;
  }

  public void setExtInfo(String extInfo) {
    this.extInfo = extInfo;
  }

  public Tenant tenantSubscriptions(List<TenantSubscription> tenantSubscriptions) {
    this.tenantSubscriptions = tenantSubscriptions;
    return this;
  }

  public Tenant addTenantSubscriptionsItem(TenantSubscription tenantSubscriptionsItem) {
    if (this.tenantSubscriptions == null) {
      this.tenantSubscriptions = new ArrayList<TenantSubscription>();
    }
    this.tenantSubscriptions.add(tenantSubscriptionsItem);
    return this;
  }

   /**
   * Get tenantSubscriptions
   * @return tenantSubscriptions
  **/
  @Schema(description = "")
  public List<TenantSubscription> getTenantSubscriptions() {
    return tenantSubscriptions;
  }

  public void setTenantSubscriptions(List<TenantSubscription> tenantSubscriptions) {
    this.tenantSubscriptions = tenantSubscriptions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tenant tenant = (Tenant) o;
    return Objects.equals(this.id, tenant.id) &&
        Objects.equals(this.name, tenant.name) &&
        Objects.equals(this.description, tenant.description) &&
        Objects.equals(this.tenantType, tenant.tenantType) &&
        Objects.equals(this.address1, tenant.address1) &&
        Objects.equals(this.address2, tenant.address2) &&
        Objects.equals(this.email, tenant.email) &&
        Objects.equals(this.phone, tenant.phone) &&
        Objects.equals(this.taxCode, tenant.taxCode) &&
        Objects.equals(this.gs1Code, tenant.gs1Code) &&
        Objects.equals(this.isActivated, tenant.isActivated) &&
        Objects.equals(this.enable, tenant.enable) &&
        Objects.equals(this.extInfo, tenant.extInfo) &&
        Objects.equals(this.tenantSubscriptions, tenant.tenantSubscriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, tenantType, address1, address2, email, phone, taxCode, gs1Code, isActivated, enable, extInfo, tenantSubscriptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tenant {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tenantType: ").append(toIndentedString(tenantType)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    taxCode: ").append(toIndentedString(taxCode)).append("\n");
    sb.append("    gs1Code: ").append(toIndentedString(gs1Code)).append("\n");
    sb.append("    isActivated: ").append(toIndentedString(isActivated)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    tenantSubscriptions: ").append(toIndentedString(tenantSubscriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
