/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TenantSubscription
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

public class TenantSubscription {
  @SerializedName("tenantId")
  private Integer tenantId = null;

  @SerializedName("tenant")
  private Tenant tenant = null;

  @SerializedName("softwarePackageId")
  private Integer softwarePackageId = null;

  @SerializedName("softwarePackage")
  private SoftwarePackage softwarePackage = null;

  @SerializedName("subscriptionDate")
  private OffsetDateTime subscriptionDate = null;

  @SerializedName("license")
  private String license = null;

  public TenantSubscription tenantId(Integer tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @Schema(required = true, description = "")
  public Integer getTenantId() {
    return tenantId;
  }

  public void setTenantId(Integer tenantId) {
    this.tenantId = tenantId;
  }

  public TenantSubscription tenant(Tenant tenant) {
    this.tenant = tenant;
    return this;
  }

   /**
   * Get tenant
   * @return tenant
  **/
  @Schema(description = "")
  public Tenant getTenant() {
    return tenant;
  }

  public void setTenant(Tenant tenant) {
    this.tenant = tenant;
  }

  public TenantSubscription softwarePackageId(Integer softwarePackageId) {
    this.softwarePackageId = softwarePackageId;
    return this;
  }

   /**
   * Get softwarePackageId
   * @return softwarePackageId
  **/
  @Schema(required = true, description = "")
  public Integer getSoftwarePackageId() {
    return softwarePackageId;
  }

  public void setSoftwarePackageId(Integer softwarePackageId) {
    this.softwarePackageId = softwarePackageId;
  }

  public TenantSubscription softwarePackage(SoftwarePackage softwarePackage) {
    this.softwarePackage = softwarePackage;
    return this;
  }

   /**
   * Get softwarePackage
   * @return softwarePackage
  **/
  @Schema(description = "")
  public SoftwarePackage getSoftwarePackage() {
    return softwarePackage;
  }

  public void setSoftwarePackage(SoftwarePackage softwarePackage) {
    this.softwarePackage = softwarePackage;
  }

  public TenantSubscription subscriptionDate(OffsetDateTime subscriptionDate) {
    this.subscriptionDate = subscriptionDate;
    return this;
  }

   /**
   * Get subscriptionDate
   * @return subscriptionDate
  **/
  @Schema(description = "")
  public OffsetDateTime getSubscriptionDate() {
    return subscriptionDate;
  }

  public void setSubscriptionDate(OffsetDateTime subscriptionDate) {
    this.subscriptionDate = subscriptionDate;
  }

  public TenantSubscription license(String license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  @Schema(description = "")
  public String getLicense() {
    return license;
  }

  public void setLicense(String license) {
    this.license = license;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TenantSubscription tenantSubscription = (TenantSubscription) o;
    return Objects.equals(this.tenantId, tenantSubscription.tenantId) &&
        Objects.equals(this.tenant, tenantSubscription.tenant) &&
        Objects.equals(this.softwarePackageId, tenantSubscription.softwarePackageId) &&
        Objects.equals(this.softwarePackage, tenantSubscription.softwarePackage) &&
        Objects.equals(this.subscriptionDate, tenantSubscription.subscriptionDate) &&
        Objects.equals(this.license, tenantSubscription.license);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, tenant, softwarePackageId, softwarePackage, subscriptionDate, license);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TenantSubscription {\n");
    
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    softwarePackageId: ").append(toIndentedString(softwarePackageId)).append("\n");
    sb.append("    softwarePackage: ").append(toIndentedString(softwarePackage)).append("\n");
    sb.append("    subscriptionDate: ").append(toIndentedString(subscriptionDate)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
