/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.swagger.v3.oas.annotations.media.Schema;
//import org.threeten.bp.Date;
/**
 * Transaction
 */

////@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

@Entity
public class Transaction {
  @Id
  @SerializedName("id")
  private long id = 0;

  @SerializedName("requestedDate")
  private Date requestedDate = null;

  @SerializedName("transactionDate")
  private Date transactionDate = null;

  @SerializedName("transactionType")
  private String transactionType = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("executedBy")
  private String executedBy = null;

  @SerializedName("transactionDetails")
  private List<TransactionDetail> transactionDetails = null;

  @SerializedName("note")
  private String note = null;

  public Transaction id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Transaction requestedDate(Date requestedDate) {
    this.requestedDate = requestedDate;
    return this;
  }

   /**
   * Get requestedDate
   * @return requestedDate
  **/
  @Schema(required = true, description = "")
  public Date getRequestedDate() {
    return requestedDate;
  }

  public void setRequestedDate(Date requestedDate) {
    this.requestedDate = requestedDate;
  }

  public Transaction transactionDate(Date transactionDate) {
    this.transactionDate = transactionDate;
    return this;
  }

   /**
   * Get transactionDate
   * @return transactionDate
  **/
  @Schema(required = true, description = "")
  public Date getTransactionDate() {
    return transactionDate;
  }

  public void setTransactionDate(Date transactionDate) {
    this.transactionDate = transactionDate;
  }

  public Transaction transactionType(String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Get transactionType
   * @return transactionType
  **/
  @Schema(required = true, description = "")
  public String getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(String transactionType) {
    this.transactionType = transactionType;
  }

  public Transaction status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Transaction createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @Schema(required = true, description = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public Transaction executedBy(String executedBy) {
    this.executedBy = executedBy;
    return this;
  }

   /**
   * Get executedBy
   * @return executedBy
  **/
  @Schema(required = true, description = "")
  public String getExecutedBy() {
    return executedBy;
  }

  public void setExecutedBy(String executedBy) {
    this.executedBy = executedBy;
  }

  public Transaction transactionDetails(List<TransactionDetail> transactionDetails) {
    this.transactionDetails = transactionDetails;
    return this;
  }

  public Transaction addTransactionDetailsItem(TransactionDetail transactionDetailsItem) {
    if (this.transactionDetails == null) {
      this.transactionDetails = new ArrayList<TransactionDetail>();
    }
    this.transactionDetails.add(transactionDetailsItem);
    return this;
  }

   /**
   * Get transactionDetails
   * @return transactionDetails
  **/
  @Schema(description = "")
  public List<TransactionDetail> getTransactionDetails() {
    return transactionDetails;
  }

  public void setTransactionDetails(List<TransactionDetail> transactionDetails) {
    this.transactionDetails = transactionDetails;
  }

  public Transaction note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @Schema(description = "")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.id, transaction.id) &&
        Objects.equals(this.requestedDate, transaction.requestedDate) &&
        Objects.equals(this.transactionDate, transaction.transactionDate) &&
        Objects.equals(this.transactionType, transaction.transactionType) &&
        Objects.equals(this.status, transaction.status) &&
        Objects.equals(this.createdBy, transaction.createdBy) &&
        Objects.equals(this.executedBy, transaction.executedBy) &&
        Objects.equals(this.transactionDetails, transaction.transactionDetails) &&
        Objects.equals(this.note, transaction.note);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, requestedDate, transactionDate, transactionType, status, createdBy, executedBy, transactionDetails, note);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    requestedDate: ").append(toIndentedString(requestedDate)).append("\n");
    sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    executedBy: ").append(toIndentedString(executedBy)).append("\n");
    sb.append("    transactionDetails: ").append(toIndentedString(transactionDetails)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
