/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.Date;
import java.util.Objects;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Transient;
import io.swagger.v3.oas.annotations.media.Schema;
//import org.threeten.bp.Date;
/**
 * TransactionDetail
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")

@Entity
public class TransactionDetail {
  @Id
  @SerializedName("id")
  private long id = 0;

  @SerializedName("execDate")
  private Date execDate = null;

  @SerializedName("transactionId")
  private Integer transactionId = null;

  @Transient
  @SerializedName("transaction")
  private Transaction transaction = null;

  @SerializedName("rfid")
  private String rfid = null;

  @SerializedName("itemUomId")
  private Integer itemUomId = null;
@Transient
  @SerializedName("itemUom")
  private ItemUom itemUom = null;

  @SerializedName("uomName")
  private String uomName = null;

  @SerializedName("batchNo")
  private String batchNo = null;

  @SerializedName("batchId")
  private Integer batchId = null;

  @Transient
  @SerializedName("batch")
  private Batch batch = null;

  @SerializedName("requiredQuantity")
  private Double requiredQuantity = null;

  @SerializedName("execQuantity")
  private Double execQuantity = null;

  @SerializedName("fromLocationId")
  private Integer fromLocationId = null;

  @Transient
  @SerializedName("fromLocation")
  private Location fromLocation = null;

  @SerializedName("toLocationId")
  private Integer toLocationId = null;

  @Transient
  @SerializedName("toLocation")
  private Location toLocation = null;

  @SerializedName("serialNumber")
  private String serialNumber = null;

  @SerializedName("expiryDate")
  private Date expiryDate = null;

  @SerializedName("manufactureDate")
  private Date manufactureDate = null;

  @SerializedName("qcStatus")
  private String qcStatus = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("itemName")
  private String itemName = null;

  public TransactionDetail id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public TransactionDetail execDate(Date execDate) {
    this.execDate = execDate;
    return this;
  }

   /**
   * Get execDate
   * @return execDate
  **/
  @Schema(required = true, description = "")
  public Date getExecDate() {
    return execDate;
  }

  public void setExecDate(Date execDate) {
    this.execDate = execDate;
  }

  public TransactionDetail transactionId(Integer transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @Schema(description = "")
  public Integer getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(Integer transactionId) {
    this.transactionId = transactionId;
  }

  public TransactionDetail transaction(Transaction transaction) {
    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  @Schema(description = "")
  public Transaction getTransaction() {
    return transaction;
  }

  public void setTransaction(Transaction transaction) {
    this.transaction = transaction;
  }

  public TransactionDetail rfid(String rfid) {
    this.rfid = rfid;
    return this;
  }

   /**
   * Get rfid
   * @return rfid
  **/
  @Schema(description = "")
  public String getRfid() {
    return rfid;
  }

  public void setRfid(String rfid) {
    this.rfid = rfid;
  }

  public TransactionDetail itemUomId(Integer itemUomId) {
    this.itemUomId = itemUomId;
    return this;
  }

   /**
   * Get itemUomId
   * @return itemUomId
  **/
  @Schema(description = "")
  public Integer getItemUomId() {
    return itemUomId;
  }

  public void setItemUomId(Integer itemUomId) {
    this.itemUomId = itemUomId;
  }

  public TransactionDetail itemUom(ItemUom itemUom) {
    this.itemUom = itemUom;
    return this;
  }

   /**
   * Get itemUom
   * @return itemUom
  **/
  @Schema(description = "")
  public ItemUom getItemUom() {
    return itemUom;
  }

  public void setItemUom(ItemUom itemUom) {
    this.itemUom = itemUom;
  }

  public TransactionDetail uomName(String uomName) {
    this.uomName = uomName;
    return this;
  }

   /**
   * Get uomName
   * @return uomName
  **/
  @Schema(description = "")
  public String getUomName() {
    return uomName;
  }

  public void setUomName(String uomName) {
    this.uomName = uomName;
  }

  public TransactionDetail batchNo(String batchNo) {
    this.batchNo = batchNo;
    return this;
  }

   /**
   * Get batchNo
   * @return batchNo
  **/
  @Schema(description = "")
  public String getBatchNo() {
    return batchNo;
  }

  public void setBatchNo(String batchNo) {
    this.batchNo = batchNo;
  }

  public TransactionDetail batchId(Integer batchId) {
    this.batchId = batchId;
    return this;
  }

   /**
   * Get batchId
   * @return batchId
  **/
  @Schema(description = "")
  public Integer getBatchId() {
    return batchId;
  }

  public void setBatchId(Integer batchId) {
    this.batchId = batchId;
  }

  public TransactionDetail batch(Batch batch) {
    this.batch = batch;
    return this;
  }

   /**
   * Get batch
   * @return batch
  **/
  @Schema(description = "")
  public Batch getBatch() {
    return batch;
  }

  public void setBatch(Batch batch) {
    this.batch = batch;
  }

  public TransactionDetail requiredQuantity(Double requiredQuantity) {
    this.requiredQuantity = requiredQuantity;
    return this;
  }

   /**
   * Get requiredQuantity
   * @return requiredQuantity
  **/
  @Schema(required = true, description = "")
  public Double getRequiredQuantity() {
    return requiredQuantity;
  }

  public void setRequiredQuantity(Double requiredQuantity) {
    this.requiredQuantity = requiredQuantity;
  }

  public TransactionDetail execQuantity(Double execQuantity) {
    this.execQuantity = execQuantity;
    return this;
  }

   /**
   * Get execQuantity
   * @return execQuantity
  **/
  @Schema(required = true, description = "")
  public Double getExecQuantity() {
    return execQuantity;
  }

  public void setExecQuantity(Double execQuantity) {
    this.execQuantity = execQuantity;
  }

  public TransactionDetail fromLocationId(Integer fromLocationId) {
    this.fromLocationId = fromLocationId;
    return this;
  }

   /**
   * Get fromLocationId
   * @return fromLocationId
  **/
  @Schema(description = "")
  public Integer getFromLocationId() {
    return fromLocationId;
  }

  public void setFromLocationId(Integer fromLocationId) {
    this.fromLocationId = fromLocationId;
  }

  public TransactionDetail fromLocation(Location fromLocation) {
    this.fromLocation = fromLocation;
    return this;
  }

   /**
   * Get fromLocation
   * @return fromLocation
  **/
  @Schema(description = "")
  public Location getFromLocation() {
    return fromLocation;
  }

  public void setFromLocation(Location fromLocation) {
    this.fromLocation = fromLocation;
  }

  public TransactionDetail toLocationId(Integer toLocationId) {
    this.toLocationId = toLocationId;
    return this;
  }

   /**
   * Get toLocationId
   * @return toLocationId
  **/
  @Schema(description = "")
  public Integer getToLocationId() {
    return toLocationId;
  }

  public void setToLocationId(Integer toLocationId) {
    this.toLocationId = toLocationId;
  }

  public TransactionDetail toLocation(Location toLocation) {
    this.toLocation = toLocation;
    return this;
  }

   /**
   * Get toLocation
   * @return toLocation
  **/
  @Schema(description = "")
  public Location getToLocation() {
    return toLocation;
  }

  public void setToLocation(Location toLocation) {
    this.toLocation = toLocation;
  }

  public TransactionDetail serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @Schema(description = "")
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public TransactionDetail expiryDate(Date expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @Schema(description = "")
  public Date getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(Date expiryDate) {
    this.expiryDate = expiryDate;
  }

  public TransactionDetail manufactureDate(Date manufactureDate) {
    this.manufactureDate = manufactureDate;
    return this;
  }

   /**
   * Get manufactureDate
   * @return manufactureDate
  **/
  @Schema(description = "")
  public Date getManufactureDate() {
    return manufactureDate;
  }

  public void setManufactureDate(Date manufactureDate) {
    this.manufactureDate = manufactureDate;
  }

  public TransactionDetail qcStatus(String qcStatus) {
    this.qcStatus = qcStatus;
    return this;
  }

   /**
   * Get qcStatus
   * @return qcStatus
  **/
  @Schema(description = "")
  public String getQcStatus() {
    return qcStatus;
  }

  public void setQcStatus(String qcStatus) {
    this.qcStatus = qcStatus;
  }

  public TransactionDetail status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public TransactionDetail note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @Schema(description = "")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public TransactionDetail itemName(String itemName) {
    this.itemName = itemName;
    return this;
  }

   /**
   * Get itemName
   * @return itemName
  **/
  @Schema(description = "")
  public String getItemName() {
    return itemName;
  }

  public void setItemName(String itemName) {
    this.itemName = itemName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionDetail transactionDetail = (TransactionDetail) o;
    return Objects.equals(this.id, transactionDetail.id) &&
        Objects.equals(this.execDate, transactionDetail.execDate) &&
        Objects.equals(this.transactionId, transactionDetail.transactionId) &&
        Objects.equals(this.transaction, transactionDetail.transaction) &&
        Objects.equals(this.rfid, transactionDetail.rfid) &&
        Objects.equals(this.itemUomId, transactionDetail.itemUomId) &&
        Objects.equals(this.itemUom, transactionDetail.itemUom) &&
        Objects.equals(this.uomName, transactionDetail.uomName) &&
        Objects.equals(this.batchNo, transactionDetail.batchNo) &&
        Objects.equals(this.batchId, transactionDetail.batchId) &&
        Objects.equals(this.batch, transactionDetail.batch) &&
        Objects.equals(this.requiredQuantity, transactionDetail.requiredQuantity) &&
        Objects.equals(this.execQuantity, transactionDetail.execQuantity) &&
        Objects.equals(this.fromLocationId, transactionDetail.fromLocationId) &&
        Objects.equals(this.fromLocation, transactionDetail.fromLocation) &&
        Objects.equals(this.toLocationId, transactionDetail.toLocationId) &&
        Objects.equals(this.toLocation, transactionDetail.toLocation) &&
        Objects.equals(this.serialNumber, transactionDetail.serialNumber) &&
        Objects.equals(this.expiryDate, transactionDetail.expiryDate) &&
        Objects.equals(this.manufactureDate, transactionDetail.manufactureDate) &&
        Objects.equals(this.qcStatus, transactionDetail.qcStatus) &&
        Objects.equals(this.status, transactionDetail.status) &&
        Objects.equals(this.note, transactionDetail.note) &&
        Objects.equals(this.itemName, transactionDetail.itemName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, execDate, transactionId, transaction, rfid, itemUomId, itemUom, uomName, batchNo, batchId, batch, requiredQuantity, execQuantity, fromLocationId, fromLocation, toLocationId, toLocation, serialNumber, expiryDate, manufactureDate, qcStatus, status, note, itemName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    execDate: ").append(toIndentedString(execDate)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("    rfid: ").append(toIndentedString(rfid)).append("\n");
    sb.append("    itemUomId: ").append(toIndentedString(itemUomId)).append("\n");
    sb.append("    itemUom: ").append(toIndentedString(itemUom)).append("\n");
    sb.append("    uomName: ").append(toIndentedString(uomName)).append("\n");
    sb.append("    batchNo: ").append(toIndentedString(batchNo)).append("\n");
    sb.append("    batchId: ").append(toIndentedString(batchId)).append("\n");
    sb.append("    batch: ").append(toIndentedString(batch)).append("\n");
    sb.append("    requiredQuantity: ").append(toIndentedString(requiredQuantity)).append("\n");
    sb.append("    execQuantity: ").append(toIndentedString(execQuantity)).append("\n");
    sb.append("    fromLocationId: ").append(toIndentedString(fromLocationId)).append("\n");
    sb.append("    fromLocation: ").append(toIndentedString(fromLocation)).append("\n");
    sb.append("    toLocationId: ").append(toIndentedString(toLocationId)).append("\n");
    sb.append("    toLocation: ").append(toIndentedString(toLocation)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    manufactureDate: ").append(toIndentedString(manufactureDate)).append("\n");
    sb.append("    qcStatus: ").append(toIndentedString(qcStatus)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    itemName: ").append(toIndentedString(itemName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
