/*
 * Beetech.Adv.RfidBase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package beetech.app.core.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Uom
 */

//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-17T21:20:19.264193+07:00[Asia/Bangkok]")
@Entity
public class Uom {
  @Id
  @SerializedName("id")
  private long id = 0;

  @SerializedName("name")
  private String name = null;

  @SerializedName("gs1Code")
  private String gs1Code = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("isBase")
  private Boolean isBase = null;

  @SerializedName("rate")
  private Double rate = null;

  @SerializedName("enable")
  private Boolean enable = null;

  @SerializedName("itemUoms")
  private List<ItemUom> itemUoms = null;

  public Uom id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Uom name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Uom gs1Code(String gs1Code) {
    this.gs1Code = gs1Code;
    return this;
  }

   /**
   * Get gs1Code
   * @return gs1Code
  **/
  @Schema(description = "")
  public String getGs1Code() {
    return gs1Code;
  }

  public void setGs1Code(String gs1Code) {
    this.gs1Code = gs1Code;
  }

  public Uom category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @Schema(required = true, description = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public Uom description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Uom isBase(Boolean isBase) {
    this.isBase = isBase;
    return this;
  }

   /**
   * Get isBase
   * @return isBase
  **/
  @Schema(description = "")
  public Boolean isIsBase() {
    return isBase;
  }

  public void setIsBase(Boolean isBase) {
    this.isBase = isBase;
  }

  public Uom rate(Double rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Get rate
   * @return rate
  **/
  @Schema(required = true, description = "")
  public Double getRate() {
    return rate;
  }

  public void setRate(Double rate) {
    this.rate = rate;
  }

  public Uom enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  @Schema(description = "")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public Uom itemUoms(List<ItemUom> itemUoms) {
    this.itemUoms = itemUoms;
    return this;
  }

  public Uom addItemUomsItem(ItemUom itemUomsItem) {
    if (this.itemUoms == null) {
      this.itemUoms = new ArrayList<ItemUom>();
    }
    this.itemUoms.add(itemUomsItem);
    return this;
  }

   /**
   * Get itemUoms
   * @return itemUoms
  **/
  @Schema(description = "")
  public List<ItemUom> getItemUoms() {
    return itemUoms;
  }

  public void setItemUoms(List<ItemUom> itemUoms) {
    this.itemUoms = itemUoms;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Uom uom = (Uom) o;
    return Objects.equals(this.id, uom.id) &&
        Objects.equals(this.name, uom.name) &&
        Objects.equals(this.gs1Code, uom.gs1Code) &&
        Objects.equals(this.category, uom.category) &&
        Objects.equals(this.description, uom.description) &&
        Objects.equals(this.isBase, uom.isBase) &&
        Objects.equals(this.rate, uom.rate) &&
        Objects.equals(this.enable, uom.enable) &&
        Objects.equals(this.itemUoms, uom.itemUoms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, gs1Code, category, description, isBase, rate, enable, itemUoms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Uom {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    gs1Code: ").append(toIndentedString(gs1Code)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isBase: ").append(toIndentedString(isBase)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    itemUoms: ").append(toIndentedString(itemUoms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
