using System;
using System.Collections.Generic;
using CommunityToolkit.Mvvm.ComponentModel;

namespace Beetech.Tms.Desktop.Services;

public partial class LanguageManager : ObservableObject
{
    private static LanguageManager? _instance;
    public static LanguageManager Instance => _instance ??= new LanguageManager();

    [ObservableProperty]
    private string _currentCulture = "en-US";

    private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["en-US"] = new()
        {
            ["AppTitle"] = "Beetech TMS - Textile Management System",
            ["Reception"] = "RECEPTION",
            ["Processing"] = "PROCESSING",
            ["Dispatch"] = "DISPATCH",
            ["DirtyInbound"] = "Dirty Inbound",
            ["CleanInbound"] = "Clean Inbound",
            ["DirtyOutbound"] = "Dirty Outbound",
            ["CleanOutbound"] = "Clean Outbound",
            ["Inventory"] = "Inventory",
            ["Condemned"] = "Condemned",
            ["Washing"] = "Washing",
            ["Drying"] = "Drying",
            ["Ironing"] = "Ironing",
            ["Folding"] = "Folding",
            ["Packing"] = "Packing",
            ["Return"] = "Return",
            ["Register"] = "Register",
            ["Settings"] = "Settings",
            ["ClearAll"] = "Clear All",
            ["Logout"] = "Logout",
            ["ActiveSession"] = "ACTIVE SESSION",
            ["Mismatch"] = "MISMATCH",
            ["Reader"] = "Reader",
            ["Api"] = "API",
            ["User"] = "User",
            ["Ready"] = "Ready",
            ["Connected"] = "Connected",
            ["Disconnected"] = "Disconnected",
            ["Scanning"] = "Scanning",
            ["StartScanning"] = "Start Scanning",
            ["StopScanning"] = "Stop Scanning",
            ["Submit"] = "SUBMIT SCANS",
            ["Reset"] = "RESET SESSION",
            ["Location"] = "Location",
            ["SelectLocation"] = "Select Location",
            ["Notes"] = "Transaction Notes",
            ["NotesPlaceholder"] = "Enter notes here...",
            ["SearchPlaceholder"] = "Search scanned items...",
            ["SystemSettings"] = "System Settings",
            ["ConfigureConnectivity"] = "Configure connectivity and operational parameters",
            ["ApiEndpointUrl"] = "API Endpoint URL",
            ["ReaderName"] = "Reader Name",
            ["ReaderIpAddress"] = "Reader IP Address",
            ["MonitoringLocation"] = "Monitoring Location",
            ["ReaderOperationalRole"] = "Reader Operational Role",
            ["RoleDescription"] = "This controls which menus and operations are available.",
            ["CheckAndSaveSettings"] = "CHECK & SAVE SETTINGS",
            ["BulkItemRegistration"] = "Bulk Item Registration",
            ["InitializeMultipleTags"] = "Initialize multiple tags and assign metadata in one batch",
            ["Category"] = "Category",
            ["InitialLocation"] = "Initial Location",
            ["Department"] = "Department",
            ["ScannedItems"] = "Scanned Items",
            ["OriginalEPC"] = "Original EPC",
            ["NewRFIDCode"] = "New RFID Code",
            ["StatusHeader"] = "Status",
            ["RegisterApplyTags"] = "Register & Apply Tags",
            ["AppTitleLogin"] = "Beetech TMS - Login",
            ["AppTitleShort"] = "Beetech TMS",
            ["AppSubtitle"] = "Textile Management System",
            ["ServerUrlLabel"] = "Server URL",
            ["UsernameLabel"] = "Username",
            ["UsernameWatermark"] = "Enter your account",
            ["PasswordLabel"] = "Password",
            ["SignIn"] = "Sign In",
            ["ExitApplication"] = "EXIT APPLICATION",
            ["VersionLabel"] = "Version 1.0.0",
            ["ReaderLabel"] = "Reader: ",
            ["ApiLabel"] = "API: ",
            ["UserLabel"] = "User: ",
            ["Processing"] = "PROCESSING",
            ["Dispatch"] = "DISPATCH",
            ["Mismatch"] = "MISMATCH",
            ["PackingContainers"] = "PACKING CONTAINERS",
            ["AddBox"] = "Add Box",
            ["ScansAssigned"] = "Scans assigned to selection",
            ["ReferenceTransaction"] = "Reference Transaction",
            ["SelectSourceTransaction"] = "Select Source Transaction",
            ["Customer"] = "Customer",
            ["SelectCustomer"] = "Select Customer",
            ["TransactionNotes"] = "Transaction Notes",
            ["EnterNotes"] = "Enter notes here...",
            ["SearchScanned"] = "🔍 Search scanned items...",
            ["HashMark"] = "#",
            ["Count"] = "Count",
            ["Time"] = "Time",
            ["ItemCode"] = "Item Code",
            ["CurrentLocation"] = "Current Location",
            ["BoxBag"] = "Box/Bag",
            ["Details"] = "Details",
            ["SimulationMode"] = "Simulation / Test Mode",
            ["Language"] = "Language"
        },
        ["vi-VN"] = new()
        {
            ["AppTitle"] = "Beetech TMS - Hệ thống Quản lý Đồ vải",
            ["Reception"] = "TIẾP NHẬN",
            ["Processing"] = "XỬ LÝ",
            ["Dispatch"] = "ĐIỀU PHỐI",
            ["DirtyInbound"] = "Nhập Đồ Bẩn",
            ["CleanInbound"] = "Nhập Đồ Sạch",
            ["DirtyOutbound"] = "Xuất Đồ Bẩn",
            ["CleanOutbound"] = "Xuất Đồ Sạch",
            ["Inventory"] = "Kiểm kê",
            ["Condemned"] = "Thanh lý",
            ["Washing"] = "Giặt",
            ["Drying"] = "Sấy",
            ["Ironing"] = "Là",
            ["Folding"] = "Gấp",
            ["Packing"] = "Đóng gói",
            ["Return"] = "Trả đồ",
            ["Register"] = "Đăng ký thẻ",
            ["Settings"] = "Cài đặt",
            ["ClearAll"] = "Xóa tất cả",
            ["Logout"] = "Đăng xuất",
            ["ActiveSession"] = "PHIÊN LÀM VIỆC",
            ["Mismatch"] = "SAI LỆCH",
            ["Reader"] = "Đầu đọc",
            ["Api"] = "Máy chủ",
            ["User"] = "Người dùng",
            ["Ready"] = "Sẵn sàng",
            ["Connected"] = "Đã kết nối",
            ["Disconnected"] = "Mất kết nối",
            ["Scanning"] = "Đang quét",
            ["StartScanning"] = "Bắt đầu quét",
            ["StopScanning"] = "Dừng quét",
            ["Submit"] = "GỬI DỮ LIỆU",
            ["Reset"] = "LÀM MỚI PHIÊN",
            ["Location"] = "Địa điểm",
            ["SelectLocation"] = "Chọn địa điểm",
            ["Notes"] = "Ghi chú giao dịch",
            ["NotesPlaceholder"] = "Nhập ghi chú tại đây...",
            ["SearchPlaceholder"] = "Tìm kiếm đồ đã quét...",
            ["SystemSettings"] = "Cài đặt Hệ thống",
            ["ConfigureConnectivity"] = "Cấu hình kết nối và thông số",
            ["ApiEndpointUrl"] = "URL Máy chủ API",
            ["ReaderName"] = "Tên Đầu Đọc",
            ["ReaderIpAddress"] = "Địa chỉ IP Đầu Đọc",
            ["MonitoringLocation"] = "Vị trí Giám sát",
            ["ReaderOperationalRole"] = "Vai trò Quét",
            ["RoleDescription"] = "Điều khiển các menu và hoạt động nào có sẵn.",
            ["CheckAndSaveSettings"] = "KIỂM TRA & LƯU CÀI ĐẶT",
            ["BulkItemRegistration"] = "Đăng ký Thẻ Hàng loạt",
            ["InitializeMultipleTags"] = "Khởi tạo nhiều thẻ và gán siêu dữ liệu cùng lúc",
            ["Category"] = "Danh mục",
            ["InitialLocation"] = "Vị trí Ban đầu",
            ["Department"] = "Phòng ban",
            ["ScannedItems"] = "Các Mục Đã Quét",
            ["OriginalEPC"] = "EPC Gốc",
            ["NewRFIDCode"] = "Mã RFID Mới",
            ["StatusHeader"] = "Trạng thái",
            ["RegisterApplyTags"] = "Đăng ký & Gắn Thẻ",
            ["AppTitleLogin"] = "Beetech TMS - Đăng nhập",
            ["AppTitleShort"] = "Beetech TMS",
            ["AppSubtitle"] = "Hệ thống Quản lý Đồ vải",
            ["ServerUrlLabel"] = "URL Máy chủ",
            ["UsernameLabel"] = "Tên người dùng",
            ["UsernameWatermark"] = "Nhập tài khoản của bạn",
            ["PasswordLabel"] = "Mật khẩu",
            ["SignIn"] = "Đăng nhập",
            ["ExitApplication"] = "THOÁT ỨNG DỤNG",
            ["VersionLabel"] = "Phiên bản 1.0.0",
            ["ReaderLabel"] = "Đầu đọc: ",
            ["ApiLabel"] = "API: ",
            ["UserLabel"] = "Người dùng: ",
            ["Processing"] = "XỬ LÝ",
            ["Dispatch"] = "ĐIỀU PHỐI",
            ["Mismatch"] = "SAI LỆCH",
            ["PackingContainers"] = "THÙNG CHỨA ĐÓNG GÓI",
            ["AddBox"] = "Thêm Thùng",
            ["ScansAssigned"] = "Các lượt quét đã được gán",
            ["ReferenceTransaction"] = "Giao dịch Tham chiếu",
            ["SelectSourceTransaction"] = "Chọn Giao dịch Nguồn",
            ["Customer"] = "Khách hàng",
            ["SelectCustomer"] = "Chọn Khách hàng",
            ["TransactionNotes"] = "Ghi chú Giao dịch",
            ["EnterNotes"] = "Nhập ghi chú tại đây...",
            ["SearchScanned"] = "🔍 Tìm kiếm vật phẩm đã quét...",
            ["HashMark"] = "#",
            ["Count"] = "Số lượng",
            ["Time"] = "Thời gian",
            ["ItemCode"] = "Mã vật phẩm",
            ["CurrentLocation"] = "Vị trí Hiện tại",
            ["BoxBag"] = "Thùng/Túi",
            ["Details"] = "Chi tiết",
            ["SimulationMode"] = "Chế độ Mô phỏng / Thử nghiệm",
            ["Language"] = "Ngôn ngữ"
        }
    };

    public string this[string key]
    {
        get
        {
            if (_translations.TryGetValue(CurrentCulture, out var cultureData) && cultureData.TryGetValue(key, out var value))
            {
                return value;
            }
            return key;
        }
    }

    public void SetLanguage(string culture)
    {
        CurrentCulture = culture;
        OnPropertyChanged("Item[]");
    }
}
